(* ::Package:: *)

(* ::Title:: *)
(*Integration Problems Involving Inverse Secants*)


(* ::Section::Closed:: *)
(*Integrands of the form x^m (a+b ArcSec[c x])^n*)


{x^m*(a + b*ArcSec[c*x]), x, 3, (x^(1 + m)*(a + b*ArcSec[c*x]))/(1 + m) - (b*x^m*Hypergeometric2F1[1/2, -(m/2), 1 - m/2, 1/(c^2*x^2)])/(c*m*(1 + m))}

{x^6*(a + b*ArcSec[c*x]), x, 7, -((5*b*Sqrt[1 - 1/(c^2*x^2)]*x^2)/(112*c^5)) - (5*b*Sqrt[1 - 1/(c^2*x^2)]*x^4)/(168*c^3) - (b*Sqrt[1 - 1/(c^2*x^2)]*x^6)/(42*c) + (1/7)*x^7*(a + b*ArcSec[c*x]) - (5*b*ArcTanh[Sqrt[1 - 1/(c^2*x^2)]])/(112*c^7)}
{x^5*(a + b*ArcSec[c*x]), x, 4, -((4*b*Sqrt[1 - 1/(c^2*x^2)]*x)/(45*c^5)) - (2*b*Sqrt[1 - 1/(c^2*x^2)]*x^3)/(45*c^3) - (b*Sqrt[1 - 1/(c^2*x^2)]*x^5)/(30*c) + (1/6)*x^6*(a + b*ArcSec[c*x])}
{x^4*(a + b*ArcSec[c*x]), x, 6, -((3*b*Sqrt[1 - 1/(c^2*x^2)]*x^2)/(40*c^3)) - (b*Sqrt[1 - 1/(c^2*x^2)]*x^4)/(20*c) + (1/5)*x^5*(a + b*ArcSec[c*x]) - (3*b*ArcTanh[Sqrt[1 - 1/(c^2*x^2)]])/(40*c^5)}
{x^3*(a + b*ArcSec[c*x]), x, 3, -((b*Sqrt[1 - 1/(c^2*x^2)]*x)/(6*c^3)) - (b*Sqrt[1 - 1/(c^2*x^2)]*x^3)/(12*c) + (1/4)*x^4*(a + b*ArcSec[c*x])}
{x^2*(a + b*ArcSec[c*x]), x, 5, -((b*Sqrt[1 - 1/(c^2*x^2)]*x^2)/(6*c)) + (1/3)*x^3*(a + b*ArcSec[c*x]) - (b*ArcTanh[Sqrt[1 - 1/(c^2*x^2)]])/(6*c^3)}
{x^1*(a + b*ArcSec[c*x]), x, 2, -((b*Sqrt[1 - 1/(c^2*x^2)]*x)/(2*c)) + (1/2)*x^2*(a + b*ArcSec[c*x])}
{x^0*(a + b*ArcSec[c*x]), x, 5, a*x + b*x*ArcSec[c*x] - (b*ArcTanh[Sqrt[1 - 1/(c^2*x^2)]])/c}
{(a + b*ArcSec[c*x])/x^1, x, 6, (I*(a + b*ArcSec[c*x])^2)/(2*b) - (a + b*ArcSec[c*x])*Log[1 + E^(2*I*ArcSec[c*x])] + (1/2)*I*b*PolyLog[2, -E^(2*I*ArcSec[c*x])]}
{(a + b*ArcSec[c*x])/x^2, x, 2, b*c*Sqrt[1 - 1/(c^2*x^2)] - (a + b*ArcSec[c*x])/x}
{(a + b*ArcSec[c*x])/x^3, x, 4, (b*c*Sqrt[1 - 1/(c^2*x^2)])/(4*x) - (a + b*ArcSec[c*x])/(2*x^2) - (1/4)*b*c^2*ArcCsc[c*x]}
{(a + b*ArcSec[c*x])/x^4, x, 4, (1/3)*b*c^3*Sqrt[1 - 1/(c^2*x^2)] - (1/9)*b*c^3*(1 - 1/(c^2*x^2))^(3/2) - (a + b*ArcSec[c*x])/(3*x^3)}
{(a + b*ArcSec[c*x])/x^5, x, 5, (b*c*Sqrt[1 - 1/(c^2*x^2)])/(16*x^3) + (3*b*c^3*Sqrt[1 - 1/(c^2*x^2)])/(32*x) - (a + b*ArcSec[c*x])/(4*x^4) - (3/32)*b*c^4*ArcCsc[c*x]}
{(a + b*ArcSec[c*x])/x^6, x, 4, (1/5)*b*c^5*Sqrt[1 - 1/(c^2*x^2)] - (2/15)*b*c^5*(1 - 1/(c^2*x^2))^(3/2) + (1/25)*b*c^5*(1 - 1/(c^2*x^2))^(5/2) - (a + b*ArcSec[c*x])/(5*x^5)}
{(a + b*ArcSec[c*x])/x^7, x, 6, (b*c*Sqrt[1 - 1/(c^2*x^2)])/(36*x^5) + (5*b*c^3*Sqrt[1 - 1/(c^2*x^2)])/(144*x^3) + (5*b*c^5*Sqrt[1 - 1/(c^2*x^2)])/(96*x) - (a + b*ArcSec[c*x])/(6*x^6) - (5/96)*b*c^6*ArcCsc[c*x]}


{x^m*(a + b*ArcSec[c*x])^2, x, 0, Int[x^m*(a + b*ArcSec[c*x])^2, x]}

{x^3*(a + b*ArcSec[c*x])^2, x, 5, (b^2*x^2)/(12*c^2) - (b*Sqrt[1 - 1/(c^2*x^2)]*x*(a + b*ArcSec[c*x]))/(3*c^3) - (b*Sqrt[1 - 1/(c^2*x^2)]*x^3*(a + b*ArcSec[c*x]))/(6*c) + (1/4)*x^4*(a + b*ArcSec[c*x])^2 + (b^2*Log[x])/(3*c^4)}
{x^2*(a + b*ArcSec[c*x])^2, x, 8, (b^2*x)/(3*c^2) - (b*Sqrt[1 - 1/(c^2*x^2)]*x^2*(a + b*ArcSec[c*x]))/(3*c) + (1/3)*x^3*(a + b*ArcSec[c*x])^2 + (2*I*b*(a + b*ArcSec[c*x])*ArcTan[E^(I*ArcSec[c*x])])/(3*c^3) - (I*b^2*PolyLog[2, (-I)*E^(I*ArcSec[c*x])])/(3*c^3) + (I*b^2*PolyLog[2, I*E^(I*ArcSec[c*x])])/(3*c^3)}
{x^1*(a + b*ArcSec[c*x])^2, x, 4, -((b*Sqrt[1 - 1/(c^2*x^2)]*x*(a + b*ArcSec[c*x]))/c) + (1/2)*x^2*(a + b*ArcSec[c*x])^2 + (b^2*Log[x])/c^2}
{x^0*(a + b*ArcSec[c*x])^2, x, 7, x*(a + b*ArcSec[c*x])^2 + (4*I*b*(a + b*ArcSec[c*x])*ArcTan[E^(I*ArcSec[c*x])])/c - (2*I*b^2*PolyLog[2, (-I)*E^(I*ArcSec[c*x])])/c + (2*I*b^2*PolyLog[2, I*E^(I*ArcSec[c*x])])/c}
{(a + b*ArcSec[c*x])^2/x^1, x, 6, (I*(a + b*ArcSec[c*x])^3)/(3*b) - (a + b*ArcSec[c*x])^2*Log[1 + E^(2*I*ArcSec[c*x])] + I*b*(a + b*ArcSec[c*x])*PolyLog[2, -E^(2*I*ArcSec[c*x])] - (1/2)*b^2*PolyLog[3, -E^(2*I*ArcSec[c*x])]}
{(a + b*ArcSec[c*x])^2/x^2, x, 4, (2*b^2)/x + 2*b*c*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x]) - (a + b*ArcSec[c*x])^2/x}
{(a + b*ArcSec[c*x])^2/x^3, x, 4, b^2/(4*x^2) - (1/2)*a*b*c^2*ArcSec[c*x] - (1/4)*b^2*c^2*ArcSec[c*x]^2 + (b*c*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x]))/(2*x) + (1/2)*(c^2 - 1/x^2)*(a + b*ArcSec[c*x])^2}
{(a + b*ArcSec[c*x])^2/x^4, x, 5, (2*b^2)/(27*x^3) + (4*b^2*c^2)/(9*x) + (4/9)*b*c^3*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x]) + (2*b*c*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x]))/(9*x^2) - (a + b*ArcSec[c*x])^2/(3*x^3)}
{(a + b*ArcSec[c*x])^2/x^5, x, 5, b^2/(32*x^4) + (3*b^2*c^2)/(32*x^2) + (3/16)*a*b*c^4*ArcSec[c*x] + (3/32)*b^2*c^4*ArcSec[c*x]^2 + (b*c*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x]))/(8*x^3) + (3*b*c^3*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x]))/(16*x) - (a + b*ArcSec[c*x])^2/(4*x^4)}


{x^m*(a + b*ArcSec[c*x])^3, x, 0, Int[x^m*(a + b*ArcSec[c*x])^3, x]}

{x^3*(a + b*ArcSec[c*x])^3, x, 10, -((b^3*Sqrt[1 - 1/(c^2*x^2)]*x)/(4*c^3)) + (b^2*x^2*(a + b*ArcSec[c*x]))/(4*c^2) + (I*b*(a + b*ArcSec[c*x])^2)/(2*c^4) - (b*Sqrt[1 - 1/(c^2*x^2)]*x*(a + b*ArcSec[c*x])^2)/(2*c^3) - (b*Sqrt[1 - 1/(c^2*x^2)]*x^3*(a + b*ArcSec[c*x])^2)/(4*c) + (1/4)*x^4*(a + b*ArcSec[c*x])^3 - (b^2*(a + b*ArcSec[c*x])*Log[1 + E^(2*I*ArcSec[c*x])])/c^4 + (I*b^3*PolyLog[2, -E^(2*I*ArcSec[c*x])])/(2*c^4)}
{x^2*(a + b*ArcSec[c*x])^3, x, 11, (b^2*x*(a + b*ArcSec[c*x]))/c^2 - (b*Sqrt[1 - 1/(c^2*x^2)]*x^2*(a + b*ArcSec[c*x])^2)/(2*c) + (1/3)*x^3*(a + b*ArcSec[c*x])^3 + (I*b*(a + b*ArcSec[c*x])^2*ArcTan[E^(I*ArcSec[c*x])])/c^3 - (b^3*ArcTanh[Sqrt[1 - 1/(c^2*x^2)]])/c^3 - (I*b^2*(a + b*ArcSec[c*x])*PolyLog[2, (-I)*E^(I*ArcSec[c*x])])/c^3 + (I*b^2*(a + b*ArcSec[c*x])*PolyLog[2, I*E^(I*ArcSec[c*x])])/c^3 + (b^3*PolyLog[3, (-I)*E^(I*ArcSec[c*x])])/c^3 - (b^3*PolyLog[3, I*E^(I*ArcSec[c*x])])/c^3}
{x^1*(a + b*ArcSec[c*x])^3, x, 7, (3*I*b*(a + b*ArcSec[c*x])^2)/(2*c^2) - (3*b*Sqrt[1 - 1/(c^2*x^2)]*x*(a + b*ArcSec[c*x])^2)/(2*c) + (1/2)*x^2*(a + b*ArcSec[c*x])^3 - (3*b^2*(a + b*ArcSec[c*x])*Log[1 + E^(2*I*ArcSec[c*x])])/c^2 + (3*I*b^3*PolyLog[2, -E^(2*I*ArcSec[c*x])])/(2*c^2)}
{x^0*(a + b*ArcSec[c*x])^3, x, 9, x*(a + b*ArcSec[c*x])^3 + (6*I*b*(a + b*ArcSec[c*x])^2*ArcTan[E^(I*ArcSec[c*x])])/c - (6*I*b^2*(a + b*ArcSec[c*x])*PolyLog[2, (-I)*E^(I*ArcSec[c*x])])/c + (6*I*b^2*(a + b*ArcSec[c*x])*PolyLog[2, I*E^(I*ArcSec[c*x])])/c + (6*b^3*PolyLog[3, (-I)*E^(I*ArcSec[c*x])])/c - (6*b^3*PolyLog[3, I*E^(I*ArcSec[c*x])])/c}
{(a + b*ArcSec[c*x])^3/x^1, x, 7, (I*(a + b*ArcSec[c*x])^4)/(4*b) - (a + b*ArcSec[c*x])^3*Log[1 + E^(2*I*ArcSec[c*x])] + (3/2)*I*b*(a + b*ArcSec[c*x])^2*PolyLog[2, -E^(2*I*ArcSec[c*x])] - (3/2)*b^2*(a + b*ArcSec[c*x])*PolyLog[3, -E^(2*I*ArcSec[c*x])] - (3/4)*I*b^3*PolyLog[4, -E^(2*I*ArcSec[c*x])]}
{(a + b*ArcSec[c*x])^3/x^2, x, 5, -6*b^3*c*Sqrt[1 - 1/(c^2*x^2)] + (6*b^2*(a + b*ArcSec[c*x]))/x + 3*b*c*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x])^2 - (a + b*ArcSec[c*x])^3/x}
{(a + b*ArcSec[c*x])^3/x^3, x, 6, -((3*b^3*c*Sqrt[1 - 1/(c^2*x^2)])/(8*x)) + (3/8)*b^3*c^2*ArcSec[c*x] - (3/4)*b^2*(c^2 - 1/x^2)*(a + b*ArcSec[c*x]) + (3*b*c*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x])^2)/(4*x) - (1/4)*c^2*(a + b*ArcSec[c*x])^3 + (1/2)*(c^2 - 1/x^2)*(a + b*ArcSec[c*x])^3}
{(a + b*ArcSec[c*x])^3/x^4, x, 8, (-(14/9))*b^3*c^3*Sqrt[1 - 1/(c^2*x^2)] + (2/27)*b^3*c^3*(1 - 1/(c^2*x^2))^(3/2) + (2*b^2*(a + b*ArcSec[c*x]))/(9*x^3) + (4*b^2*c^2*(a + b*ArcSec[c*x]))/(3*x) + (2/3)*b*c^3*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x])^2 + (b*c*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x])^2)/(3*x^2) - (a + b*ArcSec[c*x])^3/(3*x^3)}
{(a + b*ArcSec[c*x])^3/x^5, x, 10, -((3*b^3*c*Sqrt[1 - 1/(c^2*x^2)])/(128*x^3)) - (45*b^3*c^3*Sqrt[1 - 1/(c^2*x^2)])/(256*x) - (45/256)*b^3*c^4*ArcSec[c*x] + (3*b^2*(a + b*ArcSec[c*x]))/(32*x^4) + (9*b^2*c^2*(a + b*ArcSec[c*x]))/(32*x^2) + (3*b*c*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x])^2)/(16*x^3) + (9*b*c^3*Sqrt[1 - 1/(c^2*x^2)]*(a + b*ArcSec[c*x])^2)/(32*x) + (3/32)*c^4*(a + b*ArcSec[c*x])^3 - (a + b*ArcSec[c*x])^3/(4*x^4)}


(* ::Section::Closed:: *)
(*Integrands of the form x^m (d+e x^2)^p (a+b ArcSec[c x])*)


(* ::Subsection::Closed:: *)
(*Integrands of the form x^m (d+e x^2)^p (a+b ArcSec[c x])*)


(* ::Subsubsection::Closed:: *)
(*p>0*)


{x^m*(d + e*x^2)*(a + b*ArcSec[c*x]), x, 5, -((b*e*x^(2 + m)*Sqrt[-1 + c^2*x^2])/(c*(6 + 5*m + m^2)*Sqrt[c^2*x^2])) + (d*x^(1 + m)*(a + b*ArcSec[c*x]))/(1 + m) + (e*x^(3 + m)*(a + b*ArcSec[c*x]))/(3 + m) + (b*(e*(1 + m)^2 + c^2*d*(2 + m)*(3 + m))*x^(2 + m)*Sqrt[-1 + c^2*x^2]*Hypergeometric2F1[1, (2 + m)/2, (3 + m)/2, c^2*x^2])/(c*(1 + m)^2*(2 + m)*(3 + m)*Sqrt[c^2*x^2]), -((b*e*x^(2 + m)*Sqrt[-1 + c^2*x^2])/(c*(6 + 5*m + m^2)*Sqrt[c^2*x^2])) + (d*x^(1 + m)*(a + b*ArcSec[c*x]))/(1 + m) + (e*x^(3 + m)*(a + b*ArcSec[c*x]))/(3 + m) - (b*(e*(1 + m)^2 + c^2*d*(2 + m)*(3 + m))*x^(2 + m)*Sqrt[1 - c^2*x^2]*Hypergeometric2F1[1/2, (1 + m)/2, (3 + m)/2, c^2*x^2])/(c*(1 + m)^2*(2 + m)*(3 + m)*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2])}

{x^3*(d + e*x^2)*(a + b*ArcSec[c*x]), x, 5, -((b*(3*c^2*d + 2*e)*x*Sqrt[-1 + c^2*x^2])/(12*c^5*Sqrt[c^2*x^2])) - (b*(3*c^2*d + 4*e)*x*(-1 + c^2*x^2)^(3/2))/(36*c^5*Sqrt[c^2*x^2]) - (b*e*x*(-1 + c^2*x^2)^(5/2))/(30*c^5*Sqrt[c^2*x^2]) + (1/4)*d*x^4*(a + b*ArcSec[c*x]) + (1/6)*e*x^6*(a + b*ArcSec[c*x])}
{x^2*(d + e*x^2)*(a + b*ArcSec[c*x]), x, 6, -((b*(20*c^2*d + 9*e)*x^2*Sqrt[-1 + c^2*x^2])/(120*c^3*Sqrt[c^2*x^2])) - (b*e*x^4*Sqrt[-1 + c^2*x^2])/(20*c*Sqrt[c^2*x^2]) + (1/3)*d*x^3*(a + b*ArcSec[c*x]) + (1/5)*e*x^5*(a + b*ArcSec[c*x]) - (b*(20*c^2*d + 9*e)*x*ArcTanh[(c*x)/Sqrt[-1 + c^2*x^2]])/(120*c^4*Sqrt[c^2*x^2])}
{x^1*(d + e*x^2)*(a + b*ArcSec[c*x]), x, 6, -((b*(2*c^2*d + e)*x*Sqrt[-1 + c^2*x^2])/(4*c^3*Sqrt[c^2*x^2])) - (b*e*x*(-1 + c^2*x^2)^(3/2))/(12*c^3*Sqrt[c^2*x^2]) + ((d + e*x^2)^2*(a + b*ArcSec[c*x]))/(4*e) - (b*c*d^2*x*ArcTan[Sqrt[-1 + c^2*x^2]])/(4*e*Sqrt[c^2*x^2])}
{x^0*(d + e*x^2)*(a + b*ArcSec[c*x]), x, 5, -((b*e*x^2*Sqrt[-1 + c^2*x^2])/(6*c*Sqrt[c^2*x^2])) + d*x*(a + b*ArcSec[c*x]) + (1/3)*e*x^3*(a + b*ArcSec[c*x]) - (b*(6*c^2*d + e)*x*ArcTanh[(c*x)/Sqrt[-1 + c^2*x^2]])/(6*c^2*Sqrt[c^2*x^2])}
{(d + e*x^2)*(a + b*ArcSec[c*x])/x^1, x, 12, -((b*e*Sqrt[1 - 1/(c^2*x^2)]*x)/(2*c)) - (1/2)*I*b*d*ArcCsc[c*x]^2 + (1/2)*e*x^2*(a + b*ArcSec[c*x]) + b*d*ArcCsc[c*x]*Log[1 - E^(2*I*ArcCsc[c*x])] - b*d*ArcCsc[c*x]*Log[1/x] - d*(a + b*ArcSec[c*x])*Log[1/x] - (1/2)*I*b*d*PolyLog[2, E^(2*I*ArcCsc[c*x])]}
{(d + e*x^2)*(a + b*ArcSec[c*x])/x^2, x, 4, (b*c*d*Sqrt[-1 + c^2*x^2])/Sqrt[c^2*x^2] - (d*(a + b*ArcSec[c*x]))/x + e*x*(a + b*ArcSec[c*x]) - (b*e*x*ArcTanh[(c*x)/Sqrt[-1 + c^2*x^2]])/Sqrt[c^2*x^2]}


{x^m*(d + e*x^2)^2*(a + b*ArcSec[c*x]), x, 5, If[$VersionNumber>=8, -((b*e*(e*(3 + m)^2 + 2*c^2*d*(20 + 9*m + m^2))*x^(2 + m)*Sqrt[-1 + c^2*x^2])/(c^3*(2 + m)*(3 + m)*(4 + m)*(5 + m)*Sqrt[c^2*x^2])) - (b*e^2*x^(4 + m)*Sqrt[-1 + c^2*x^2])/(c*(4 + m)*(5 + m)*Sqrt[c^2*x^2]) + (d^2*x^(1 + m)*(a + b*ArcSec[c*x]))/(1 + m) + (2*d*e*x^(3 + m)*(a + b*ArcSec[c*x]))/(3 + m) + (e^2*x^(5 + m)*(a + b*ArcSec[c*x]))/(5 + m) - (b*(e^2*(3 + 4*m + m^2)^2 + 2*c^2*d*e*(1 + m)^2*(20 + 9*m + m^2) + c^4*d^2*(120 + 154*m + 71*m^2 + 14*m^3 + m^4))*x^(2 + m)*Sqrt[1 - c^2*x^2]*Hypergeometric2F1[1/2, (1 + m)/2, (3 + m)/2, c^2*x^2])/(c^3*(1 + m)^2*(2 + m)*(3 + m)*(4 + m)*(5 + m)*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]), -((b*e*(e*(3 + m)^2 + 2*c^2*d*(20 + 9*m + m^2))*x^(2 + m)*Sqrt[-1 + c^2*x^2])/(c^3*(4 + m)*(5 + m)*(6 + 5*m + m^2)*Sqrt[c^2*x^2])) - (b*e^2*x^(4 + m)*Sqrt[-1 + c^2*x^2])/(c*(4 + m)*(5 + m)*Sqrt[c^2*x^2]) + (d^2*x^(1 + m)*(a + b*ArcSec[c*x]))/(1 + m) + (2*d*e*x^(3 + m)*(a + b*ArcSec[c*x]))/(3 + m) + (e^2*x^(5 + m)*(a + b*ArcSec[c*x]))/(5 + m) - (b*(e^2*(3 + 4*m + m^2)^2 + 2*c^2*d*e*(1 + m)^2*(20 + 9*m + m^2) + c^4*d^2*(120 + 154*m + 71*m^2 + 14*m^3 + m^4))*x^(2 + m)*Sqrt[1 - c^2*x^2]*Hypergeometric2F1[1/2, (1 + m)/2, (3 + m)/2, c^2*x^2])/(c^3*(1 + m)^2*(2 + m)*(3 + m)*(4 + m)*(5 + m)*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2])]}

{x^3*(d + e*x^2)^2*(a + b*ArcSec[c*x]), x, 5, -((b*(6*c^4*d^2 + 8*c^2*d*e + 3*e^2)*x*Sqrt[-1 + c^2*x^2])/(24*c^7*Sqrt[c^2*x^2])) - (b*(6*c^4*d^2 + 16*c^2*d*e + 9*e^2)*x*(-1 + c^2*x^2)^(3/2))/(72*c^7*Sqrt[c^2*x^2]) - (b*e*(8*c^2*d + 9*e)*x*(-1 + c^2*x^2)^(5/2))/(120*c^7*Sqrt[c^2*x^2]) - (b*e^2*x*(-1 + c^2*x^2)^(7/2))/(56*c^7*Sqrt[c^2*x^2]) + (1/4)*d^2*x^4*(a + b*ArcSec[c*x]) + (1/3)*d*e*x^6*(a + b*ArcSec[c*x]) + (1/8)*e^2*x^8*(a + b*ArcSec[c*x])}
{x^2*(d + e*x^2)^2*(a + b*ArcSec[c*x]), x, 7, -((b*(280*c^4*d^2 + 252*c^2*d*e + 75*e^2)*x^2*Sqrt[-1 + c^2*x^2])/(1680*c^5*Sqrt[c^2*x^2])) - (b*e*(84*c^2*d + 25*e)*x^4*Sqrt[-1 + c^2*x^2])/(840*c^3*Sqrt[c^2*x^2]) - (b*e^2*x^6*Sqrt[-1 + c^2*x^2])/(42*c*Sqrt[c^2*x^2]) + (1/3)*d^2*x^3*(a + b*ArcSec[c*x]) + (2/5)*d*e*x^5*(a + b*ArcSec[c*x]) + (1/7)*e^2*x^7*(a + b*ArcSec[c*x]) - (b*(280*c^4*d^2 + 252*c^2*d*e + 75*e^2)*x*ArcTanh[(c*x)/Sqrt[-1 + c^2*x^2]])/(1680*c^6*Sqrt[c^2*x^2])}
{x^1*(d + e*x^2)^2*(a + b*ArcSec[c*x]), x, 6, -((b*(3*c^4*d^2 + 3*c^2*d*e + e^2)*x*Sqrt[-1 + c^2*x^2])/(6*c^5*Sqrt[c^2*x^2])) - (b*e*(3*c^2*d + 2*e)*x*(-1 + c^2*x^2)^(3/2))/(18*c^5*Sqrt[c^2*x^2]) - (b*e^2*x*(-1 + c^2*x^2)^(5/2))/(30*c^5*Sqrt[c^2*x^2]) + ((d + e*x^2)^3*(a + b*ArcSec[c*x]))/(6*e) - (b*c*d^3*x*ArcTan[Sqrt[-1 + c^2*x^2]])/(6*e*Sqrt[c^2*x^2])}
{x^0*(d + e*x^2)^2*(a + b*ArcSec[c*x]), x, 6, -((b*e*(40*c^2*d + 9*e)*x^2*Sqrt[-1 + c^2*x^2])/(120*c^3*Sqrt[c^2*x^2])) - (b*e^2*x^4*Sqrt[-1 + c^2*x^2])/(20*c*Sqrt[c^2*x^2]) + d^2*x*(a + b*ArcSec[c*x]) + (2/3)*d*e*x^3*(a + b*ArcSec[c*x]) + (1/5)*e^2*x^5*(a + b*ArcSec[c*x]) - (b*(120*c^4*d^2 + 40*c^2*d*e + 9*e^2)*x*ArcTanh[(c*x)/Sqrt[-1 + c^2*x^2]])/(120*c^4*Sqrt[c^2*x^2])}
{(d + e*x^2)^2*(a + b*ArcSec[c*x])/x^1, x, 13, -((b*e*(6*c^2*d + e)*Sqrt[1 - 1/(c^2*x^2)]*x)/(6*c^3)) - (b*e^2*Sqrt[1 - 1/(c^2*x^2)]*x^3)/(12*c) - (1/2)*I*b*d^2*ArcCsc[c*x]^2 + d*e*x^2*(a + b*ArcSec[c*x]) + (1/4)*e^2*x^4*(a + b*ArcSec[c*x]) + b*d^2*ArcCsc[c*x]*Log[1 - E^(2*I*ArcCsc[c*x])] - b*d^2*ArcCsc[c*x]*Log[1/x] - d^2*(a + b*ArcSec[c*x])*Log[1/x] - (1/2)*I*b*d^2*PolyLog[2, E^(2*I*ArcCsc[c*x])]}
{(d + e*x^2)^2*(a + b*ArcSec[c*x])/x^2, x, 6, (b*c*d^2*Sqrt[-1 + c^2*x^2])/Sqrt[c^2*x^2] - (b*e^2*x^2*Sqrt[-1 + c^2*x^2])/(6*c*Sqrt[c^2*x^2]) - (d^2*(a + b*ArcSec[c*x]))/x + 2*d*e*x*(a + b*ArcSec[c*x]) + (1/3)*e^2*x^3*(a + b*ArcSec[c*x]) - (b*e*(12*c^2*d + e)*x*ArcTanh[(c*x)/Sqrt[-1 + c^2*x^2]])/(6*c^2*Sqrt[c^2*x^2])}


(* ::Subsubsection::Closed:: *)
(*p<0*)


{x^m*(a + b*ArcSec[c*x])/(d + e*x^2), x, 0, Defer[Int][(x^m*(a + b*ArcSec[c*x]))/(d + e*x^2), x]}

(* {x^3*(a + b*ArcSec[c*x])/(d + e*x^2), x, 47, -((b*Sqrt[1 - 1/(c^2*x^2)]*x)/(2*c*e)) + (I*b*d*ArcSec[c*x]^2)/(2*e^2) + (x^2*(a + b*ArcSec[c*x]))/(2*e) - (I*d*(a + b*ArcSec[c*x])^2)/(2*b*e^2) - (b*d*ArcSec[c*x]*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^2) - (b*d*ArcSec[c*x]*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^2) - (b*d*ArcSec[c*x]*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^2) - (b*d*ArcSec[c*x]*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^2) + (d*(a + b*ArcSec[c*x])*Log[1 + E^(2*I*ArcSec[c*x])])/e^2 - (a*d*Log[Sqrt[e] - Sqrt[-d]/x])/(2*e^2) - (a*d*Log[Sqrt[e] + Sqrt[-d]/x])/(2*e^2) + (I*b*d*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*e^2) + (I*b*d*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^2) + (I*b*d*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*e^2) + (I*b*d*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^2) - (I*b*d*PolyLog[2, -E^(2*I*ArcSec[c*x])])/(2*e^2)} *)
{x^2*(a + b*ArcSec[c*x])/(d + e*x^2), x, 25, (x*(a + b*ArcSec[c*x]))/e - (b*ArcTanh[Sqrt[1 - 1/(c^2*x^2)]])/(c*e) + (Sqrt[-d]*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^(3/2)) - (Sqrt[-d]*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^(3/2)) + (Sqrt[-d]*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^(3/2)) - (Sqrt[-d]*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^(3/2)) + (I*b*Sqrt[-d]*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*e^(3/2)) - (I*b*Sqrt[-d]*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^(3/2)) + (I*b*Sqrt[-d]*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*e^(3/2)) - (I*b*Sqrt[-d]*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^(3/2))}
{x^1*(a + b*ArcSec[c*x])/(d + e*x^2), x, 26, ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e) + ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e) + ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e) + ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e) - ((a + b*ArcSec[c*x])*Log[1 + E^(2*I*ArcSec[c*x])])/e - (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*e) - (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e) - (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*e) - (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e) + (I*b*PolyLog[2, -E^(2*I*ArcSec[c*x])])/(2*e)}
{x^0*(a + b*ArcSec[c*x])/(d + e*x^2), x, 19, ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) - ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) + ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) - ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) + (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*Sqrt[-d]*Sqrt[e]) - (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e]) + (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*Sqrt[-d]*Sqrt[e]) - (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*Sqrt[-d]*Sqrt[e])}
{(a + b*ArcSec[c*x])/(x^1*(d + e*x^2)), x, 19, (I*(a + b*ArcSec[c*x])^2)/(2*b*d) - ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d) - ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d) - ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d) - ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d) + (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*d) + (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d) + (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*d) + (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d)}
{(a + b*ArcSec[c*x])/(x^2*(d + e*x^2)), x, 24, (b*c*Sqrt[1 - 1/(c^2*x^2)])/d - a/(d*x) - (b*ArcSec[c*x])/(d*x) + (Sqrt[e]*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*(-d)^(3/2)) - (Sqrt[e]*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*(-d)^(3/2)) + (Sqrt[e]*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*(-d)^(3/2)) - (Sqrt[e]*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*(-d)^(3/2)) + (I*b*Sqrt[e]*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*(-d)^(3/2)) - (I*b*Sqrt[e]*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*(-d)^(3/2)) + (I*b*Sqrt[e]*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*(-d)^(3/2)) - (I*b*Sqrt[e]*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*(-d)^(3/2))}


{x^m*(a + b*ArcSec[c*x])/(d + e*x^2)^2, x, 0, Defer[Int][(x^m*(a + b*ArcSec[c*x]))/(d + e*x^2)^2, x]}

{x^5*(a + b*ArcSec[c*x])/(d + e*x^2)^2, x, 31, -((b*Sqrt[1 - 1/(c^2*x^2)]*x)/(2*c*e^2)) + (d*(a + b*ArcSec[c*x]))/(2*e^2*(e + d/x^2)) + (x^2*(a + b*ArcSec[c*x]))/(2*e^2) + (b*d*ArcTan[Sqrt[c^2*d + e]/(c*Sqrt[e]*Sqrt[1 - 1/(c^2*x^2)]*x)])/(2*e^(5/2)*Sqrt[c^2*d + e]) - (d*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/e^3 - (d*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/e^3 - (d*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/e^3 - (d*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/e^3 + (2*d*(a + b*ArcSec[c*x])*Log[1 + E^(2*I*ArcSec[c*x])])/e^3 + (I*b*d*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/e^3 + (I*b*d*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/e^3 + (I*b*d*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/e^3 + (I*b*d*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/e^3 - (I*b*d*PolyLog[2, -E^(2*I*ArcSec[c*x])])/e^3}
{x^4*(a + b*ArcSec[c*x])/(d + e*x^2)^2, x, 51, -((d*(a + b*ArcSec[c*x]))/(4*e^2*(Sqrt[-d]*Sqrt[e] - d/x))) + (d*(a + b*ArcSec[c*x]))/(4*e^2*(Sqrt[-d]*Sqrt[e] + d/x)) + (x*(a + b*ArcSec[c*x]))/e^2 - (b*ArcTanh[Sqrt[1 - 1/(c^2*x^2)]])/(c*e^2) - (b*Sqrt[d]*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(4*e^2*Sqrt[c^2*d + e]) - (b*Sqrt[d]*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(4*e^2*Sqrt[c^2*d + e]) + (3*Sqrt[-d]*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*e^(5/2)) - (3*Sqrt[-d]*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*e^(5/2)) + (3*Sqrt[-d]*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*e^(5/2)) - (3*Sqrt[-d]*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*e^(5/2)) + (3*I*b*Sqrt[-d]*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(4*e^(5/2)) - (3*I*b*Sqrt[-d]*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*e^(5/2)) + (3*I*b*Sqrt[-d]*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(4*e^(5/2)) - (3*I*b*Sqrt[-d]*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*e^(5/2))}
{x^3*(a + b*ArcSec[c*x])/(d + e*x^2)^2, x, 29, -((a + b*ArcSec[c*x])/(2*e*(e + d/x^2))) - (b*ArcTan[Sqrt[c^2*d + e]/(c*Sqrt[e]*Sqrt[1 - 1/(c^2*x^2)]*x)])/(2*e^(3/2)*Sqrt[c^2*d + e]) + ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^2) + ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^2) + ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^2) + ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^2) - ((a + b*ArcSec[c*x])*Log[1 + E^(2*I*ArcSec[c*x])])/e^2 - (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*e^2) - (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^2) - (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*e^2) - (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^2) + (I*b*PolyLog[2, -E^(2*I*ArcSec[c*x])])/(2*e^2)}
{x^2*(a + b*ArcSec[c*x])/(d + e*x^2)^2, x, 27, (a + b*ArcSec[c*x])/(4*e*(Sqrt[-d]*Sqrt[e] - d/x)) - (a + b*ArcSec[c*x])/(4*e*(Sqrt[-d]*Sqrt[e] + d/x)) + (b*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(4*Sqrt[d]*e*Sqrt[c^2*d + e]) + (b*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(4*Sqrt[d]*e*Sqrt[c^2*d + e]) + ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2)) - ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2)) + ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2)) - ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2)) + (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(4*Sqrt[-d]*e^(3/2)) - (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2)) + (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(4*Sqrt[-d]*e^(3/2)) - (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*Sqrt[-d]*e^(3/2))}
{x^1*(a + b*ArcSec[c*x])/(d + e*x^2)^2, x, 7, -((a + b*ArcSec[c*x])/(2*e*(d + e*x^2))) + (b*c*x*ArcTan[Sqrt[-1 + c^2*x^2]])/(2*d*e*Sqrt[c^2*x^2]) - (b*c*x*ArcTan[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/Sqrt[c^2*d + e]])/(2*d*Sqrt[e]*Sqrt[c^2*d + e]*Sqrt[c^2*x^2])}
{x^0*(a + b*ArcSec[c*x])/(d + e*x^2)^2, x, 47, -((a + b*ArcSec[c*x])/(4*d*(Sqrt[-d]*Sqrt[e] - d/x))) + (a + b*ArcSec[c*x])/(4*d*(Sqrt[-d]*Sqrt[e] + d/x)) - (b*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(4*d^(3/2)*Sqrt[c^2*d + e]) - (b*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(4*d^(3/2)*Sqrt[c^2*d + e]) - ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e]) + ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e]) - ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e]) + ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e]) - (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(4*(-d)^(3/2)*Sqrt[e]) + (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e]) - (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(4*(-d)^(3/2)*Sqrt[e]) + (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*(-d)^(3/2)*Sqrt[e])}
{(a + b*ArcSec[c*x])/(x^1*(d + e*x^2)^2), x, 24, -((e*(a + b*ArcSec[c*x]))/(2*d^2*(e + d/x^2))) + (I*(a + b*ArcSec[c*x])^2)/(2*b*d^2) - (b*Sqrt[e]*ArcTan[Sqrt[c^2*d + e]/(c*Sqrt[e]*Sqrt[1 - 1/(c^2*x^2)]*x)])/(2*d^2*Sqrt[c^2*d + e]) - ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d^2) - ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d^2) - ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d^2) - ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d^2) + (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*d^2) + (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d^2) + (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*d^2) + (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d^2)}
{(a + b*ArcSec[c*x])/(x^2*(d + e*x^2)^2), x, 50, (b*c*Sqrt[1 - 1/(c^2*x^2)])/d^2 - a/(d^2*x) - (b*ArcSec[c*x])/(d^2*x) + (e*(a + b*ArcSec[c*x]))/(4*d^2*(Sqrt[-d]*Sqrt[e] - d/x)) - (e*(a + b*ArcSec[c*x]))/(4*d^2*(Sqrt[-d]*Sqrt[e] + d/x)) + (b*e*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(4*d^(5/2)*Sqrt[c^2*d + e]) + (b*e*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(4*d^(5/2)*Sqrt[c^2*d + e]) - (3*Sqrt[e]*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*(-d)^(5/2)) + (3*Sqrt[e]*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*(-d)^(5/2)) - (3*Sqrt[e]*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*(-d)^(5/2)) + (3*Sqrt[e]*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*(-d)^(5/2)) - (3*I*b*Sqrt[e]*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(4*(-d)^(5/2)) + (3*I*b*Sqrt[e]*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(4*(-d)^(5/2)) - (3*I*b*Sqrt[e]*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(4*(-d)^(5/2)) + (3*I*b*Sqrt[e]*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(4*(-d)^(5/2))}


{x^m*(a + b*ArcSec[c*x])/(d + e*x^2)^3, x, 0, Defer[Int][(x^m*(a + b*ArcSec[c*x]))/(d + e*x^2)^3, x]}

{x^5*(a + b*ArcSec[c*x])/(d + e*x^2)^3, x, 33, -((b*c*d*Sqrt[1 - 1/(c^2*x^2)])/(8*e^2*(c^2*d + e)*(e + d/x^2)*x)) - (a + b*ArcSec[c*x])/(4*e*(e + d/x^2)^2) - (a + b*ArcSec[c*x])/(2*e^2*(e + d/x^2)) - (b*ArcTan[Sqrt[c^2*d + e]/(c*Sqrt[e]*Sqrt[1 - 1/(c^2*x^2)]*x)])/(2*e^(5/2)*Sqrt[c^2*d + e]) - (b*(c^2*d + 2*e)*ArcTan[Sqrt[c^2*d + e]/(c*Sqrt[e]*Sqrt[1 - 1/(c^2*x^2)]*x)])/(8*e^(5/2)*(c^2*d + e)^(3/2)) + ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^3) + ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^3) + ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^3) + ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^3) - ((a + b*ArcSec[c*x])*Log[1 + E^(2*I*ArcSec[c*x])])/e^3 - (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*e^3) - (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*e^3) - (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*e^3) - (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*e^3) + (I*b*PolyLog[2, -E^(2*I*ArcSec[c*x])])/(2*e^3)}
{x^4*(a + b*ArcSec[c*x])/(d + e*x^2)^3, x, 35, (b*c*Sqrt[-d]*Sqrt[1 - 1/(c^2*x^2)])/(16*e^(3/2)*(c^2*d + e)*(Sqrt[-d]*Sqrt[e] - d/x)) + (b*c*Sqrt[-d]*Sqrt[1 - 1/(c^2*x^2)])/(16*e^(3/2)*(c^2*d + e)*(Sqrt[-d]*Sqrt[e] + d/x)) + (Sqrt[-d]*(a + b*ArcSec[c*x]))/(16*e^(3/2)*(Sqrt[-d]*Sqrt[e] - d/x)^2) + (3*(a + b*ArcSec[c*x]))/(16*e^2*(Sqrt[-d]*Sqrt[e] - d/x)) - (Sqrt[-d]*(a + b*ArcSec[c*x]))/(16*e^(3/2)*(Sqrt[-d]*Sqrt[e] + d/x)^2) - (3*(a + b*ArcSec[c*x]))/(16*e^2*(Sqrt[-d]*Sqrt[e] + d/x)) + (b*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*Sqrt[d]*e*(c^2*d + e)^(3/2)) + (3*b*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*Sqrt[d]*e^2*Sqrt[c^2*d + e]) + (b*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*Sqrt[d]*e*(c^2*d + e)^(3/2)) + (3*b*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*Sqrt[d]*e^2*Sqrt[c^2*d + e]) + (3*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2)) - (3*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2)) + (3*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2)) - (3*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2)) + (3*I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(16*Sqrt[-d]*e^(5/2)) - (3*I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2)) + (3*I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(16*Sqrt[-d]*e^(5/2)) - (3*I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*Sqrt[-d]*e^(5/2))}
{x^3*(a + b*ArcSec[c*x])/(d + e*x^2)^3, x, 6, (b*c*x*Sqrt[-1 + c^2*x^2])/(8*e*(c^2*d + e)*Sqrt[c^2*x^2]*(d + e*x^2)) + (x^4*(a + b*ArcSec[c*x]))/(4*d*(d + e*x^2)^2) - (b*c*(c^2*d + 2*e)*x*ArcTan[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/Sqrt[c^2*d + e]])/(8*d*e^(3/2)*(c^2*d + e)^(3/2)*Sqrt[c^2*x^2])}
{x^2*(a + b*ArcSec[c*x])/(d + e*x^2)^3, x, 63, (b*c*Sqrt[1 - 1/(c^2*x^2)])/(16*Sqrt[-d]*Sqrt[e]*(c^2*d + e)*(Sqrt[-d]*Sqrt[e] - d/x)) + (b*c*Sqrt[1 - 1/(c^2*x^2)])/(16*Sqrt[-d]*Sqrt[e]*(c^2*d + e)*(Sqrt[-d]*Sqrt[e] + d/x)) + (a + b*ArcSec[c*x])/(16*Sqrt[-d]*Sqrt[e]*(Sqrt[-d]*Sqrt[e] - d/x)^2) + (a + b*ArcSec[c*x])/(16*d*e*(Sqrt[-d]*Sqrt[e] - d/x)) - (a + b*ArcSec[c*x])/(16*Sqrt[-d]*Sqrt[e]*(Sqrt[-d]*Sqrt[e] + d/x)^2) - (a + b*ArcSec[c*x])/(16*d*e*(Sqrt[-d]*Sqrt[e] + d/x)) - (b*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(3/2)*(c^2*d + e)^(3/2)) + (b*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(3/2)*e*Sqrt[c^2*d + e]) - (b*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(3/2)*(c^2*d + e)^(3/2)) + (b*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(3/2)*e*Sqrt[c^2*d + e]) - ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2)) + ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2)) - ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2)) + ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2)) - (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(16*(-d)^(3/2)*e^(3/2)) + (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2)) - (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(16*(-d)^(3/2)*e^(3/2)) + (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*(-d)^(3/2)*e^(3/2))}
{x^1*(a + b*ArcSec[c*x])/(d + e*x^2)^3, x, 8, -((b*c*x*Sqrt[-1 + c^2*x^2])/(8*d*(c^2*d + e)*Sqrt[c^2*x^2]*(d + e*x^2))) - (a + b*ArcSec[c*x])/(4*e*(d + e*x^2)^2) + (b*c*x*ArcTan[Sqrt[-1 + c^2*x^2]])/(4*d^2*e*Sqrt[c^2*x^2]) - (b*c*(3*c^2*d + 2*e)*x*ArcTan[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/Sqrt[c^2*d + e]])/(8*d^2*Sqrt[e]*(c^2*d + e)^(3/2)*Sqrt[c^2*x^2])}
{x^0*(a + b*ArcSec[c*x])/(d + e*x^2)^3, x, 81, (b*c*Sqrt[e]*Sqrt[1 - 1/(c^2*x^2)])/(16*(-d)^(3/2)*(c^2*d + e)*(Sqrt[-d]*Sqrt[e] - d/x)) + (b*c*Sqrt[e]*Sqrt[1 - 1/(c^2*x^2)])/(16*(-d)^(3/2)*(c^2*d + e)*(Sqrt[-d]*Sqrt[e] + d/x)) + (Sqrt[e]*(a + b*ArcSec[c*x]))/(16*(-d)^(3/2)*(Sqrt[-d]*Sqrt[e] - d/x)^2) - (5*(a + b*ArcSec[c*x]))/(16*d^2*(Sqrt[-d]*Sqrt[e] - d/x)) - (Sqrt[e]*(a + b*ArcSec[c*x]))/(16*(-d)^(3/2)*(Sqrt[-d]*Sqrt[e] + d/x)^2) + (5*(a + b*ArcSec[c*x]))/(16*d^2*(Sqrt[-d]*Sqrt[e] + d/x)) + (b*e*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(5/2)*(c^2*d + e)^(3/2)) - (5*b*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(5/2)*Sqrt[c^2*d + e]) + (b*e*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(5/2)*(c^2*d + e)^(3/2)) - (5*b*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(5/2)*Sqrt[c^2*d + e]) + (3*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e]) - (3*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e]) + (3*(a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e]) - (3*(a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e]) + (3*I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(16*(-d)^(5/2)*Sqrt[e]) - (3*I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e]) + (3*I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(16*(-d)^(5/2)*Sqrt[e]) - (3*I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(16*(-d)^(5/2)*Sqrt[e])}
{(a + b*ArcSec[c*x])/(x^1*(d + e*x^2)^3), x, 28, (b*c*e*Sqrt[1 - 1/(c^2*x^2)])/(8*d^2*(c^2*d + e)*(e + d/x^2)*x) + (e^2*(a + b*ArcSec[c*x]))/(4*d^3*(e + d/x^2)^2) - (e*(a + b*ArcSec[c*x]))/(d^3*(e + d/x^2)) + (I*(a + b*ArcSec[c*x])^2)/(2*b*d^3) - (b*Sqrt[e]*ArcTan[Sqrt[c^2*d + e]/(c*Sqrt[e]*Sqrt[1 - 1/(c^2*x^2)]*x)])/(d^3*Sqrt[c^2*d + e]) + (b*Sqrt[e]*(c^2*d + 2*e)*ArcTan[Sqrt[c^2*d + e]/(c*Sqrt[e]*Sqrt[1 - 1/(c^2*x^2)]*x)])/(8*d^3*(c^2*d + e)^(3/2)) - ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d^3) - ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d^3) - ((a + b*ArcSec[c*x])*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d^3) - ((a + b*ArcSec[c*x])*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d^3) + (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e]))])/(2*d^3) + (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - Sqrt[c^2*d + e])])/(2*d^3) + (I*b*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e]))])/(2*d^3) + (I*b*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + Sqrt[c^2*d + e])])/(2*d^3)}
(* {(a + b*ArcSec[c*x])/(x^2*(d + e*x^2)^3), x, 96, (b*c*Sqrt[1 - 1/(c^2*x^2)])/d^3 + (b*c*e^(3/2)*Sqrt[1 - 1/(c^2*x^2)])/(16*(-d)^(5/2)*(c^2*d + e)*(Sqrt[-d]*Sqrt[e] - d/x)) + (b*c*e^(3/2)*Sqrt[1 - 1/(c^2*x^2)])/(16*(-d)^(5/2)*(c^2*d + e)*(Sqrt[-d]*Sqrt[e] + d/x)) - a/(d^3*x) + (a*e^2)/(4*d^3*(e + d/x^2)^2*x) - (9*a*e)/(8*d^3*(e + d/x^2)*x) + (15*a*Sqrt[e]*ArcCot[(Sqrt[e]*x)/Sqrt[d]])/(8*d^(7/2)) + (b*e^(3/2)*ArcSec[c*x])/(16*(-d)^(5/2)*(Sqrt[-d]*Sqrt[e] - d/x)^2) + (9*b*e*ArcSec[c*x])/(16*d^3*(Sqrt[-d]*Sqrt[e] - d/x)) - (b*e^(3/2)*ArcSec[c*x])/(16*(-d)^(5/2)*(Sqrt[-d]*Sqrt[e] + d/x)^2) - (9*b*e*ArcSec[c*x])/(16*d^3*(Sqrt[-d]*Sqrt[e] + d/x)) - (b*ArcSec[c*x])/(d^3*x) - (b*e^2*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(7/2)*(c^2*d + e)^(3/2)) + (9*b*e*ArcTanh[(c^2*d - (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(7/2)*Sqrt[c^2*d + e]) - (b*e^2*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(7/2)*(c^2*d + e)^(3/2)) + (9*b*e*ArcTanh[(c^2*d + (Sqrt[-d]*Sqrt[e])/x)/(c*Sqrt[d]*Sqrt[c^2*d + e]*Sqrt[1 - 1/(c^2*x^2)])])/(16*d^(7/2)*Sqrt[c^2*d + e]) + (15*b*Sqrt[e]*ArcSec[c*x]*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - c*Sqrt[d + e/c^2])])/(16*(-d)^(7/2)) - (15*b*Sqrt[e]*ArcSec[c*x]*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - c*Sqrt[d + e/c^2])])/(16*(-d)^(7/2)) + (15*b*Sqrt[e]*ArcSec[c*x]*Log[1 - (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + c*Sqrt[d + e/c^2])])/(16*(-d)^(7/2)) - (15*b*Sqrt[e]*ArcSec[c*x]*Log[1 + (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + c*Sqrt[d + e/c^2])])/(16*(-d)^(7/2)) + (15*I*b*Sqrt[e]*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - c*Sqrt[d + e/c^2]))])/(16*(-d)^(7/2)) - (15*I*b*Sqrt[e]*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] - c*Sqrt[d + e/c^2])])/(16*(-d)^(7/2)) + (15*I*b*Sqrt[e]*PolyLog[2, -((c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + c*Sqrt[d + e/c^2]))])/(16*(-d)^(7/2)) - (15*I*b*Sqrt[e]*PolyLog[2, (c*Sqrt[-d]*E^(I*ArcSec[c*x]))/(Sqrt[e] + c*Sqrt[d + e/c^2])])/(16*(-d)^(7/2))} *)


(* ::Subsection::Closed:: *)
(*Integrands of the form x^m (d+e x^2)^(p/2) (a+b ArcSec[c x])*)


(* ::Subsubsection::Closed:: *)
(*p>0*)


{x^m*(d + e*x^2)^(1/2)*(a + b*ArcSec[c*x]), x, 0, Defer[Int][x^m*Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]), x]}

{x^3*(d + e*x^2)^(1/2)*(a + b*ArcSec[c*x]), x, If[$VersionNumber>=8, 10, 17], If[$VersionNumber>=8, -((b*(c^2*d + 9*e)*x*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(120*c^3*e*Sqrt[c^2*x^2])) - (b*x*Sqrt[-1 + c^2*x^2]*(d + e*x^2)^(3/2))/(20*c*e*Sqrt[c^2*x^2]) - (d*(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/(3*e^2) + ((d + e*x^2)^(5/2)*(a + b*ArcSec[c*x]))/(5*e^2) + (2*b*c*d^(5/2)*x*ArcTan[(Sqrt[d]*Sqrt[-1 + c^2*x^2])/Sqrt[d + e*x^2]])/(15*e^2*Sqrt[c^2*x^2]) + (b*(15*c^4*d^2 - 10*c^2*d*e - 9*e^2)*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(120*c^4*e^(3/2)*Sqrt[c^2*x^2]), (b*d*x*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(15*c*e*Sqrt[c^2*x^2]) - (3*b*(c^2*d + e)*x*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(40*c^3*e*Sqrt[c^2*x^2]) - (b*x*Sqrt[-1 + c^2*x^2]*(d + e*x^2)^(3/2))/(20*c*e*Sqrt[c^2*x^2]) - (d*(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/(3*e^2) + ((d + e*x^2)^(5/2)*(a + b*ArcSec[c*x]))/(5*e^2) + (2*b*c*d^(5/2)*x*ArcTan[(Sqrt[d]*Sqrt[-1 + c^2*x^2])/Sqrt[d + e*x^2]])/(15*e^2*Sqrt[c^2*x^2]) + (2*b*d^2*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(15*e^(3/2)*Sqrt[c^2*x^2]) + (b*d*(c^2*d + e)*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(15*c^2*e^(3/2)*Sqrt[c^2*x^2]) - (3*b*(c^2*d + e)^2*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(40*c^4*e^(3/2)*Sqrt[c^2*x^2])]}
{x^2*(d + e*x^2)^(1/2)*(a + b*ArcSec[c*x]), x, 0, Defer[Int][x^2*Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]), x]}
{x^1*(d + e*x^2)^(1/2)*(a + b*ArcSec[c*x]), x, 8, -((b*x*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(6*c*Sqrt[c^2*x^2])) + ((d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/(3*e) - (b*c*d^(3/2)*x*ArcTan[(Sqrt[d]*Sqrt[-1 + c^2*x^2])/Sqrt[d + e*x^2]])/(3*e*Sqrt[c^2*x^2]) - (b*(3*c^2*d + e)*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(6*c^2*Sqrt[e]*Sqrt[c^2*x^2])}
{x^0*(d + e*x^2)^(1/2)*(a + b*ArcSec[c*x]), x, 0, Defer[Int][Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]), x]}
{(d + e*x^2)^(1/2)*(a + b*ArcSec[c*x])/x^1, x, 0, Defer[Int][(Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/x, x]}
{(d + e*x^2)^(1/2)*(a + b*ArcSec[c*x])/x^2, x, 0, Defer[Int][(Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/x^2, x]}


{x^m*(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]), x, 0, Defer[Int][x^m*(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]), x]}

{x^3*(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]), x, 11, (b*(3*c^4*d^2 - 38*c^2*d*e - 25*e^2)*x*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(560*c^5*e*Sqrt[c^2*x^2]) - (b*(13*c^2*d + 25*e)*x*Sqrt[-1 + c^2*x^2]*(d + e*x^2)^(3/2))/(840*c^3*e*Sqrt[c^2*x^2]) - (b*x*Sqrt[-1 + c^2*x^2]*(d + e*x^2)^(5/2))/(42*c*e*Sqrt[c^2*x^2]) - (d*(d + e*x^2)^(5/2)*(a + b*ArcSec[c*x]))/(5*e^2) + ((d + e*x^2)^(7/2)*(a + b*ArcSec[c*x]))/(7*e^2) + (2*b*c*d^(7/2)*x*ArcTan[(Sqrt[d]*Sqrt[-1 + c^2*x^2])/Sqrt[d + e*x^2]])/(35*e^2*Sqrt[c^2*x^2]) + (b*(35*c^6*d^3 - 35*c^4*d^2*e - 63*c^2*d*e^2 - 25*e^3)*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(560*c^6*e^(3/2)*Sqrt[c^2*x^2])}
{x^2*(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]), x, 0, Defer[Int][x^2*(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]), x]}
{x^1*(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]), x, 9, -((b*(7*c^2*d + 3*e)*x*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(40*c^3*Sqrt[c^2*x^2])) - (b*x*Sqrt[-1 + c^2*x^2]*(d + e*x^2)^(3/2))/(20*c*Sqrt[c^2*x^2]) + ((d + e*x^2)^(5/2)*(a + b*ArcSec[c*x]))/(5*e) - (b*c*d^(5/2)*x*ArcTan[(Sqrt[d]*Sqrt[-1 + c^2*x^2])/Sqrt[d + e*x^2]])/(5*e*Sqrt[c^2*x^2]) - (b*(15*c^4*d^2 + 10*c^2*d*e + 3*e^2)*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(40*c^4*Sqrt[e]*Sqrt[c^2*x^2])}
{x^0*(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]), x, 0, Defer[Int][(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]), x]}
{(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x])/x^1, x, 0, Defer[Int][((d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/x, x]}
{(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x])/x^2, x, 0, Defer[Int][((d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/x^2, x]}


(* ::Subsubsection::Closed:: *)
(*p<0*)


{x^m*(a + b*ArcSec[c*x])/(d + e*x^2)^(1/2), x, 0, Defer[Int][(x^m*(a + b*ArcSec[c*x]))/Sqrt[d + e*x^2], x]}

{x^5*(a + b*ArcSec[c*x])/(d + e*x^2)^(1/2), x, 17, (7*b*d*x*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(30*c*e^2*Sqrt[c^2*x^2]) - (3*b*(c^2*d + e)*x*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(40*c^3*e^2*Sqrt[c^2*x^2]) - (b*x*Sqrt[-1 + c^2*x^2]*(d + e*x^2)^(3/2))/(20*c*e^2*Sqrt[c^2*x^2]) + (d^2*Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/e^3 - (2*d*(d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/(3*e^3) + ((d + e*x^2)^(5/2)*(a + b*ArcSec[c*x]))/(5*e^3) - (8*b*c*d^(5/2)*x*ArcTan[(Sqrt[d]*Sqrt[-1 + c^2*x^2])/Sqrt[d + e*x^2]])/(15*e^3*Sqrt[c^2*x^2]) - (8*b*d^2*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(15*e^(5/2)*Sqrt[c^2*x^2]) + (7*b*d*(c^2*d + e)*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(30*c^2*e^(5/2)*Sqrt[c^2*x^2]) - (3*b*(c^2*d + e)^2*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(40*c^4*e^(5/2)*Sqrt[c^2*x^2])}
{x^4*(a + b*ArcSec[c*x])/(d + e*x^2)^(1/2), x, 0, Defer[Int][(x^4*(a + b*ArcSec[c*x]))/Sqrt[d + e*x^2], x]}
{x^3*(a + b*ArcSec[c*x])/(d + e*x^2)^(1/2), x, 9, -((b*x*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(6*c*e*Sqrt[c^2*x^2])) - (d*Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/e^2 + ((d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/(3*e^2) + (2*b*c*d^(3/2)*x*ArcTan[(Sqrt[d]*Sqrt[-1 + c^2*x^2])/Sqrt[d + e*x^2]])/(3*e^2*Sqrt[c^2*x^2]) + (b*(3*c^2*d - e)*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(6*c^2*e^(3/2)*Sqrt[c^2*x^2])}
{x^2*(a + b*ArcSec[c*x])/(d + e*x^2)^(1/2), x, 0, Defer[Int][(x^2*(a + b*ArcSec[c*x]))/Sqrt[d + e*x^2], x]}
{x^1*(a + b*ArcSec[c*x])/(d + e*x^2)^(1/2), x, 7, (Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/e - (b*c*Sqrt[d]*x*ArcTan[(Sqrt[d]*Sqrt[-1 + c^2*x^2])/Sqrt[d + e*x^2]])/(e*Sqrt[c^2*x^2]) - (b*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(Sqrt[e]*Sqrt[c^2*x^2])}
{x^0*(a + b*ArcSec[c*x])/(d + e*x^2)^(1/2), x, 0, Defer[Int][(a + b*ArcSec[c*x])/Sqrt[d + e*x^2], x]}
{(a + b*ArcSec[c*x])/(x^1*(d + e*x^2)^(1/2)), x, 0, Defer[Int][(a + b*ArcSec[c*x])/(x*Sqrt[d + e*x^2]), x]}
{(a + b*ArcSec[c*x])/(x^2*(d + e*x^2)^(1/2)), x, 11, (b*c*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(d*Sqrt[c^2*x^2]) - (Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/(d*x) - (b*c^2*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(d*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) + (b*(c^2*d + e)*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(d*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])}
{(a + b*ArcSec[c*x])/(x^3*(d + e*x^2)^(1/2)), x, 0, Defer[Int][(a + b*ArcSec[c*x])/(x^3*Sqrt[d + e*x^2]), x]}


{x^m*(a + b*ArcSec[c*x])/(d + e*x^2)^(3/2), x, 0, Defer[Int][(x^m*(a + b*ArcSec[c*x]))/(d + e*x^2)^(3/2), x]}

{x^5*(a + b*ArcSec[c*x])/(d + e*x^2)^(3/2), x, 12, -((b*x*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(6*c*e^2*Sqrt[c^2*x^2])) - (d^2*(a + b*ArcSec[c*x]))/(e^3*Sqrt[d + e*x^2]) - (2*d*Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/e^3 + ((d + e*x^2)^(3/2)*(a + b*ArcSec[c*x]))/(3*e^3) + (8*b*c*d^(3/2)*x*ArcTan[(Sqrt[d]*Sqrt[-1 + c^2*x^2])/Sqrt[d + e*x^2]])/(3*e^3*Sqrt[c^2*x^2]) + (5*b*d*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(3*e^(5/2)*Sqrt[c^2*x^2]) - (b*(c^2*d + e)*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(6*c^2*e^(5/2)*Sqrt[c^2*x^2])}
{x^4*(a + b*ArcSec[c*x])/(d + e*x^2)^(3/2), x, 0, Defer[Int][(x^4*(a + b*ArcSec[c*x]))/(d + e*x^2)^(3/2), x]}
{x^3*(a + b*ArcSec[c*x])/(d + e*x^2)^(3/2), x, 8, (d*(a + b*ArcSec[c*x]))/(e^2*Sqrt[d + e*x^2]) + (Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/e^2 - (2*b*c*Sqrt[d]*x*ArcTan[(Sqrt[d]*Sqrt[-1 + c^2*x^2])/Sqrt[d + e*x^2]])/(e^2*Sqrt[c^2*x^2]) - (b*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(e^(3/2)*Sqrt[c^2*x^2])}
{x^2*(a + b*ArcSec[c*x])/(d + e*x^2)^(3/2), x, 0, Defer[Int][(x^2*(a + b*ArcSec[c*x]))/(d + e*x^2)^(3/2), x]}
{x^1*(a + b*ArcSec[c*x])/(d + e*x^2)^(3/2), x, 4, -((a + b*ArcSec[c*x])/(e*Sqrt[d + e*x^2])) + (b*c*x*ArcTan[(Sqrt[d]*Sqrt[-1 + c^2*x^2])/Sqrt[d + e*x^2]])/(Sqrt[d]*e*Sqrt[c^2*x^2])}
{x^0*(a + b*ArcSec[c*x])/(d + e*x^2)^(3/2), x, 5, (x*(a + b*ArcSec[c*x]))/(d*Sqrt[d + e*x^2]) - (b*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(d*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])}
{(a + b*ArcSec[c*x])/(x^1*(d + e*x^2)^(3/2)), x, 0, Defer[Int][(a + b*ArcSec[c*x])/(x*(d + e*x^2)^(3/2)), x]}
{(a + b*ArcSec[c*x])/(x^2*(d + e*x^2)^(3/2)), x, 10, (b*c*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(d^2*Sqrt[c^2*x^2]) - (a + b*ArcSec[c*x])/(d*x*Sqrt[d + e*x^2]) - (2*e*x*(a + b*ArcSec[c*x]))/(d^2*Sqrt[d + e*x^2]) - (b*c^2*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(d^2*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) + (b*(c^2*d + 2*e)*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(d^2*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])}
{(a + b*ArcSec[c*x])/(x^3*(d + e*x^2)^(3/2)), x, 0, Defer[Int][(a + b*ArcSec[c*x])/(x^3*(d + e*x^2)^(3/2)), x]}


{x^m*(a + b*ArcSec[c*x])/(d + e*x^2)^(5/2), x, 0, Defer[Int][(x^m*(a + b*ArcSec[c*x]))/(d + e*x^2)^(5/2), x]}

{x^5*(a + b*ArcSec[c*x])/(d + e*x^2)^(5/2), x, 11, -((b*c*d*x*Sqrt[-1 + c^2*x^2])/(3*e^2*(c^2*d + e)*Sqrt[c^2*x^2]*Sqrt[d + e*x^2])) - (d^2*(a + b*ArcSec[c*x]))/(3*e^3*(d + e*x^2)^(3/2)) + (2*d*(a + b*ArcSec[c*x]))/(e^3*Sqrt[d + e*x^2]) + (Sqrt[d + e*x^2]*(a + b*ArcSec[c*x]))/e^3 - (8*b*c*Sqrt[d]*x*ArcTan[(Sqrt[d]*Sqrt[-1 + c^2*x^2])/Sqrt[d + e*x^2]])/(3*e^3*Sqrt[c^2*x^2]) - (b*x*ArcTanh[(Sqrt[e]*Sqrt[-1 + c^2*x^2])/(c*Sqrt[d + e*x^2])])/(e^(5/2)*Sqrt[c^2*x^2])}
{x^4*(a + b*ArcSec[c*x])/(d + e*x^2)^(5/2), x, 0, Defer[Int][(x^4*(a + b*ArcSec[c*x]))/(d + e*x^2)^(5/2), x]}
{x^3*(a + b*ArcSec[c*x])/(d + e*x^2)^(5/2), x, 7, (b*c*x*Sqrt[-1 + c^2*x^2])/(3*e*(c^2*d + e)*Sqrt[c^2*x^2]*Sqrt[d + e*x^2]) + (d*(a + b*ArcSec[c*x]))/(3*e^2*(d + e*x^2)^(3/2)) - (a + b*ArcSec[c*x])/(e^2*Sqrt[d + e*x^2]) + (2*b*c*x*ArcTan[(Sqrt[d]*Sqrt[-1 + c^2*x^2])/Sqrt[d + e*x^2]])/(3*Sqrt[d]*e^2*Sqrt[c^2*x^2])}
{x^2*(a + b*ArcSec[c*x])/(d + e*x^2)^(5/2), x, 10, -((b*c*x^2*Sqrt[-1 + c^2*x^2])/(3*d*(c^2*d + e)*Sqrt[c^2*x^2]*Sqrt[d + e*x^2])) + (x^3*(a + b*ArcSec[c*x]))/(3*d*(d + e*x^2)^(3/2)) + (b*c^2*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(3*d*e*(c^2*d + e)*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) - (b*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(3*d*e*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])}
{x^1*(a + b*ArcSec[c*x])/(d + e*x^2)^(5/2), x, 5, -((b*c*x*Sqrt[-1 + c^2*x^2])/(3*d*(c^2*d + e)*Sqrt[c^2*x^2]*Sqrt[d + e*x^2])) - (a + b*ArcSec[c*x])/(3*e*(d + e*x^2)^(3/2)) + (b*c*x*ArcTan[(Sqrt[d]*Sqrt[-1 + c^2*x^2])/Sqrt[d + e*x^2]])/(3*d^(3/2)*e*Sqrt[c^2*x^2])}
{x^0*(a + b*ArcSec[c*x])/(d + e*x^2)^(5/2), x, 10, (b*c*e*x^2*Sqrt[-1 + c^2*x^2])/(3*d^2*(c^2*d + e)*Sqrt[c^2*x^2]*Sqrt[d + e*x^2]) + (x*(a + b*ArcSec[c*x]))/(3*d*(d + e*x^2)^(3/2)) + (2*x*(a + b*ArcSec[c*x]))/(3*d^2*Sqrt[d + e*x^2]) - (b*c^2*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(3*d^2*(c^2*d + e)*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) - (2*b*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(3*d^2*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])}
{(a + b*ArcSec[c*x])/(x^1*(d + e*x^2)^(5/2)), x, 0, Defer[Int][(a + b*ArcSec[c*x])/(x*(d + e*x^2)^(5/2)), x]}
{(a + b*ArcSec[c*x])/(x^2*(d + e*x^2)^(5/2)), x, 26, -((b*c*e*Sqrt[-1 + c^2*x^2])/(d^2*(c^2*d + e)*Sqrt[c^2*x^2]*Sqrt[d + e*x^2])) - (4*b*c*e^2*x^2*Sqrt[-1 + c^2*x^2])/(3*d^3*(c^2*d + e)*Sqrt[c^2*x^2]*Sqrt[d + e*x^2]) + (b*c*(c^2*d + 2*e)*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])/(d^3*(c^2*d + e)*Sqrt[c^2*x^2]) - (a + b*ArcSec[c*x])/(d*x*(d + e*x^2)^(3/2)) - (4*e*x*(a + b*ArcSec[c*x]))/(3*d^2*(d + e*x^2)^(3/2)) - (8*e*x*(a + b*ArcSec[c*x]))/(3*d^3*Sqrt[d + e*x^2]) + (4*b*c^2*e*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(3*d^3*(c^2*d + e)*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) - (b*c^2*(c^2*d + 2*e)*x*Sqrt[1 - c^2*x^2]*Sqrt[d + e*x^2]*EllipticE[ArcSin[c*x], -(e/(c^2*d))])/(d^3*(c^2*d + e)*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[1 + (e*x^2)/d]) + (b*c^2*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(d^2*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2]) + (8*b*e*x*Sqrt[1 - c^2*x^2]*Sqrt[1 + (e*x^2)/d]*EllipticF[ArcSin[c*x], -(e/(c^2*d))])/(3*d^3*Sqrt[c^2*x^2]*Sqrt[-1 + c^2*x^2]*Sqrt[d + e*x^2])}
{(a + b*ArcSec[c*x])/(x^3*(d + e*x^2)^(5/2)), x, 0, Defer[Int][(a + b*ArcSec[c*x])/(x^3*(d + e*x^2)^(5/2)), x]}


(* ::Section::Closed:: *)
(*Integrands of the form x^m ArcSec[a x^n]*)


(* ::Subsection::Closed:: *)
(*Integrands of the form x^m ArcSec[a x^n]*)


(* ::Subsubsection::Closed:: *)
(*n>0*)


{ArcSec[a*x^5]/x, x, 7, (1/10)*I*ArcSec[a*x^5]^2 - (1/5)*ArcSec[a*x^5]*Log[1 + E^(2*I*ArcSec[a*x^5])] + (1/10)*I*PolyLog[2, -E^(2*I*ArcSec[a*x^5])]}


{x^3*ArcSec[Sqrt[x]], x, 4, (-(1/4))*Sqrt[-1 + x] - (1/4)*(-1 + x)^(3/2) - (3/20)*(-1 + x)^(5/2) - (1/28)*(-1 + x)^(7/2) + (1/4)*x^4*ArcSec[Sqrt[x]]}
{x^2*ArcSec[Sqrt[x]], x, 4, (-(1/3))*Sqrt[-1 + x] - (2/9)*(-1 + x)^(3/2) - (1/15)*(-1 + x)^(5/2) + (1/3)*x^3*ArcSec[Sqrt[x]]}
{x^1*ArcSec[Sqrt[x]], x, 4, (-(1/2))*Sqrt[-1 + x] - (1/6)*(-1 + x)^(3/2) + (1/2)*x^2*ArcSec[Sqrt[x]]}
{x^0*ArcSec[Sqrt[x]], x, 3, -Sqrt[-1 + x] + x*ArcSec[Sqrt[x]]}
{ArcSec[Sqrt[x]]/x^1, x, 7, I*ArcSec[Sqrt[x]]^2 - 2*ArcSec[Sqrt[x]]*Log[1 + E^(2*I*ArcSec[Sqrt[x]])] + I*PolyLog[2, -E^(2*I*ArcSec[Sqrt[x]])]}
{ArcSec[Sqrt[x]]/x^2, x, 5, Sqrt[-1 + x]/(2*x) - ArcSec[Sqrt[x]]/x + (1/2)*ArcTan[Sqrt[-1 + x]]}
{ArcSec[Sqrt[x]]/x^3, x, 6, Sqrt[-1 + x]/(8*x^2) + (3*Sqrt[-1 + x])/(16*x) - ArcSec[Sqrt[x]]/(2*x^2) + (3/16)*ArcTan[Sqrt[-1 + x]]}
{ArcSec[Sqrt[x]]/x^4, x, 7, Sqrt[-1 + x]/(18*x^3) + (5*Sqrt[-1 + x])/(72*x^2) + (5*Sqrt[-1 + x])/(48*x) - ArcSec[Sqrt[x]]/(3*x^3) + (5/48)*ArcTan[Sqrt[-1 + x]]}


(* ::Subsubsection::Closed:: *)
(*n<0*)


{x^2*ArcSec[a/x], x, 5, (-(1/3))*a^3*Sqrt[1 - x^2/a^2] + (1/9)*a^3*(1 - x^2/a^2)^(3/2) + (1/3)*x^3*ArcCos[x/a]}
{x^1*ArcSec[a/x], x, 4, (-(1/4))*a*x*Sqrt[1 - x^2/a^2] + (1/2)*x^2*ArcCos[x/a] + (1/4)*a^2*ArcSin[x/a]}
{x^0*ArcSec[a/x], x, 3, (-a)*Sqrt[1 - x^2/a^2] + x*ArcCos[x/a]}
{ArcSec[a/x]/x^1, x, 6, (-(1/2))*I*ArcCos[x/a]^2 + ArcCos[x/a]*Log[1 + E^(2*I*ArcCos[x/a])] - (1/2)*I*PolyLog[2, -E^(2*I*ArcCos[x/a])]}
{ArcSec[a/x]/x^2, x, 5, -(ArcCos[x/a]/x) + ArcTanh[Sqrt[1 - x^2/a^2]]/a}
{ArcSec[a/x]/x^3, x, 3, Sqrt[1 - x^2/a^2]/(2*a*x) - ArcCos[x/a]/(2*x^2)}
{ArcSec[a/x]/x^4, x, 6, Sqrt[1 - x^2/a^2]/(6*a*x^2) - ArcCos[x/a]/(3*x^3) + ArcTanh[Sqrt[1 - x^2/a^2]]/(6*a^3)}


(* ::Subsubsection::Closed:: *)
(*n symbolic*)


{ArcSec[a*x^n]/x, x, 7, (I*ArcSec[a*x^n]^2)/(2*n) - (ArcSec[a*x^n]*Log[1 + E^(2*I*ArcSec[a*x^n])])/n + (I*PolyLog[2, -E^(2*I*ArcSec[a*x^n])])/(2*n)}


(* ::Section::Closed:: *)
(*Integrands of the form x^m ArcSec[a+b x]^n*)


{x^4*ArcSec[a + b*x], x, 8, (2*a*(1 + 3*a^2)*(a + b*x)*Sqrt[1 - 1/(a + b*x)^2])/(3*b^5) - ((3 + 40*a^2)*(a + b*x)^2*Sqrt[1 - 1/(a + b*x)^2])/(40*b^5) + (a*(a + b*x)^3*Sqrt[1 - 1/(a + b*x)^2])/(3*b^5) - ((a + b*x)^4*Sqrt[1 - 1/(a + b*x)^2])/(20*b^5) + ((a^5 + b^5*x^5)*ArcSec[a + b*x])/(5*b^5) - ((3 + 40*a^2 + 40*a^4)*ArcTanh[Sqrt[1 - 1/(a + b*x)^2]])/(40*b^5)}
{x^3*ArcSec[a + b*x], x, 7, -(((1 + 9*a^2)*(a + b*x)*Sqrt[1 - 1/(a + b*x)^2])/(6*b^4)) + (a*(a + b*x)^2*Sqrt[1 - 1/(a + b*x)^2])/(2*b^4) - ((a + b*x)^3*Sqrt[1 - 1/(a + b*x)^2])/(12*b^4) - ((a^4 - b^4*x^4)*ArcSec[a + b*x])/(4*b^4) + (a*(1 + 2*a^2)*ArcTanh[Sqrt[1 - 1/(a + b*x)^2]])/(2*b^4)}
{x^2*ArcSec[a + b*x], x, 7, (a*(a + b*x)*Sqrt[1 - 1/(a + b*x)^2])/b^3 - ((a + b*x)^2*Sqrt[1 - 1/(a + b*x)^2])/(6*b^3) + ((a^3 + b^3*x^3)*ArcSec[a + b*x])/(3*b^3) - ((1 + 6*a^2)*ArcTanh[Sqrt[1 - 1/(a + b*x)^2]])/(6*b^3)}
{x^1*ArcSec[a + b*x], x, 6, -(((a + b*x)*Sqrt[1 - 1/(a + b*x)^2])/(2*b^2)) - ((a^2 - b^2*x^2)*ArcSec[a + b*x])/(2*b^2) + (a*ArcTanh[Sqrt[1 - 1/(a + b*x)^2]])/b^2}
{x^0*ArcSec[a + b*x], x, 5, ((a + b*x)*ArcSec[a + b*x])/b - ArcTanh[Sqrt[1 - 1/(a + b*x)^2]]/b}
{ArcSec[a + b*x]/x^1, x, 1, ArcSec[a + b*x]*Log[1 - ((1 - Sqrt[1 - a^2])*E^(I*ArcSec[a + b*x]))/a] + ArcSec[a + b*x]*Log[1 - ((1 + Sqrt[1 - a^2])*E^(I*ArcSec[a + b*x]))/a] - ArcSec[a + b*x]*Log[1 + E^(2*I*ArcSec[a + b*x])] - I*PolyLog[2, ((1 - Sqrt[1 - a^2])*E^(I*ArcSec[a + b*x]))/a] - I*PolyLog[2, ((1 + Sqrt[1 - a^2])*E^(I*ArcSec[a + b*x]))/a] + (1/2)*I*PolyLog[2, -E^(2*I*ArcSec[a + b*x])]}
{ArcSec[a + b*x]/x^2, x, 5, -(((b + a/x)*ArcSec[a + b*x])/a) + (b*ArcTan[(a - 1/(a + b*x))/(Sqrt[1 - a^2]*Sqrt[1 - 1/(a + b*x)^2])])/(a*Sqrt[1 - a^2])}
{ArcSec[a + b*x]/x^3, x, 6, (b^2*Sqrt[1 - 1/(a + b*x)^2])/(2*a*(1 - a^2)*(1 - a/(a + b*x))) + ((b^2 - a^2/x^2)*ArcSec[a + b*x])/(2*a^2) - ((1 - 2*a^2)*b^2*ArcTan[(a - 1/(a + b*x))/(Sqrt[1 - a^2]*Sqrt[1 - 1/(a + b*x)^2])])/(2*a^2*(1 - a^2)^(3/2))}
{ArcSec[a + b*x]/x^4, x, 7, (b^3*Sqrt[1 - 1/(a + b*x)^2])/(6*a^2*(1 - a^2)*(1 - a/(a + b*x))^2) - ((1 - 2*a^2)*b^3*Sqrt[1 - 1/(a + b*x)^2])/(2*a^2*(1 - a^2)^2*(1 - a/(a + b*x))) - ((b^3 + a^3/x^3)*ArcSec[a + b*x])/(3*a^3) + ((2 - 5*a^2 + 6*a^4)*b^3*ArcTan[(a - 1/(a + b*x))/(Sqrt[1 - a^2]*Sqrt[1 - 1/(a + b*x)^2])])/(6*a^3*(1 - a^2)^(5/2))}


{x^3*ArcSec[a + b*x]^2, x, 20, -((a*x)/b^3) + (a + b*x)^2/(12*b^4) - ((a + b*x)*Sqrt[1 - 1/(a + b*x)^2]*ArcSec[a + b*x])/(3*b^4) - (3*a^2*(a + b*x)*Sqrt[1 - 1/(a + b*x)^2]*ArcSec[a + b*x])/b^4 + (a*(a + b*x)^2*Sqrt[1 - 1/(a + b*x)^2]*ArcSec[a + b*x])/b^4 - ((a + b*x)^3*Sqrt[1 - 1/(a + b*x)^2]*ArcSec[a + b*x])/(6*b^4) - (a^4*ArcSec[a + b*x]^2)/(4*b^4) + (1/4)*x^4*ArcSec[a + b*x]^2 - (2*I*a*ArcSec[a + b*x]*ArcTan[E^(I*ArcSec[a + b*x])])/b^4 - (4*I*a^3*ArcSec[a + b*x]*ArcTan[E^(I*ArcSec[a + b*x])])/b^4 + Log[a + b*x]/(3*b^4) + (3*a^2*Log[a + b*x])/b^4 + (I*a*PolyLog[2, (-I)*E^(I*ArcSec[a + b*x])])/b^4 + (2*I*a^3*PolyLog[2, (-I)*E^(I*ArcSec[a + b*x])])/b^4 - (I*a*PolyLog[2, I*E^(I*ArcSec[a + b*x])])/b^4 - (2*I*a^3*PolyLog[2, I*E^(I*ArcSec[a + b*x])])/b^4}
{x^2*ArcSec[a + b*x]^2, x, 17, x/(3*b^2) + (2*a*(a + b*x)*Sqrt[1 - 1/(a + b*x)^2]*ArcSec[a + b*x])/b^3 - ((a + b*x)^2*Sqrt[1 - 1/(a + b*x)^2]*ArcSec[a + b*x])/(3*b^3) + (a^3*ArcSec[a + b*x]^2)/(3*b^3) + (1/3)*x^3*ArcSec[a + b*x]^2 + (2*I*ArcSec[a + b*x]*ArcTan[E^(I*ArcSec[a + b*x])])/(3*b^3) + (4*I*a^2*ArcSec[a + b*x]*ArcTan[E^(I*ArcSec[a + b*x])])/b^3 - (2*a*Log[a + b*x])/b^3 - (I*PolyLog[2, (-I)*E^(I*ArcSec[a + b*x])])/(3*b^3) - (2*I*a^2*PolyLog[2, (-I)*E^(I*ArcSec[a + b*x])])/b^3 + (I*PolyLog[2, I*E^(I*ArcSec[a + b*x])])/(3*b^3) + (2*I*a^2*PolyLog[2, I*E^(I*ArcSec[a + b*x])])/b^3}
{x^1*ArcSec[a + b*x]^2, x, 11, -(((a + b*x)*Sqrt[1 - 1/(a + b*x)^2]*ArcSec[a + b*x])/b^2) - (a^2*ArcSec[a + b*x]^2)/(2*b^2) + (1/2)*x^2*ArcSec[a + b*x]^2 - (4*I*a*ArcSec[a + b*x]*ArcTan[E^(I*ArcSec[a + b*x])])/b^2 + Log[a + b*x]/b^2 + (2*I*a*PolyLog[2, (-I)*E^(I*ArcSec[a + b*x])])/b^2 - (2*I*a*PolyLog[2, I*E^(I*ArcSec[a + b*x])])/b^2}
{x^0*ArcSec[a + b*x]^2, x, 7, ((a + b*x)*ArcSec[a + b*x]^2)/b + (4*I*ArcSec[a + b*x]*ArcTan[E^(I*ArcSec[a + b*x])])/b - (2*I*PolyLog[2, (-I)*E^(I*ArcSec[a + b*x])])/b + (2*I*PolyLog[2, I*E^(I*ArcSec[a + b*x])])/b}
{ArcSec[a + b*x]^2/x^1, x, 0, (-ArcSec[a + b*x]^2)*Log[1 + E^(2*I*ArcSec[a + b*x])] + ArcSec[a + b*x]^2*Log[1 + (a*(1/(a + b*x) + I*Sqrt[1 - 1/(a + b*x)^2]))/(-1 + Sqrt[1 - a^2])] + ArcSec[a + b*x]^2*Log[1 - (a*(1/(a + b*x) + I*Sqrt[1 - 1/(a + b*x)^2]))/(1 + Sqrt[1 - a^2])] + I*ArcSec[a + b*x]*PolyLog[2, -E^(2*I*ArcSec[a + b*x])] - 2*I*ArcSec[a + b*x]*PolyLog[2, -((a*(1/(a + b*x) + I*Sqrt[1 - 1/(a + b*x)^2]))/(-1 + Sqrt[1 - a^2]))] - 2*I*ArcSec[a + b*x]*PolyLog[2, (a*(1/(a + b*x) + I*Sqrt[1 - 1/(a + b*x)^2]))/(1 + Sqrt[1 - a^2])] - (1/2)*PolyLog[3, -E^(2*I*ArcSec[a + b*x])] + 2*PolyLog[3, -((a*(1/(a + b*x) + I*Sqrt[1 - 1/(a + b*x)^2]))/(-1 + Sqrt[1 - a^2]))] + 2*PolyLog[3, (a*(1/(a + b*x) + I*Sqrt[1 - 1/(a + b*x)^2]))/(1 + Sqrt[1 - a^2])], Int[ArcSec[a + b*x]^2/x, x]}
{ArcSec[a + b*x]^2/x^2, x, 0, (1/a)*(b*(-(((a + b*x)*ArcSec[a + b*x]^2)/(b*x)) - (1/Sqrt[-1 + a^2])*(2*(2*ArcSec[a + b*x]*ArcTanh[((-1 + a)*Cot[(1/2)*ArcSec[a + b*x]])/Sqrt[-1 + a^2]] - 2*ArcCos[1/a]*ArcTanh[((1 + a)*Tan[(1/2)*ArcSec[a + b*x]])/Sqrt[-1 + a^2]] + (ArcCos[1/a] - 2*I*ArcTanh[((-1 + a)*Cot[(1/2)*ArcSec[a + b*x]])/Sqrt[-1 + a^2]] + 2*I*ArcTanh[((1 + a)*Tan[(1/2)*ArcSec[a + b*x]])/Sqrt[-1 + a^2]])*Log[Sqrt[-1 + a^2]/(E^((1/2)*I*ArcSec[a + b*x])*(Sqrt[2]*Sqrt[a]*Sqrt[-((b*x)/(a + b*x))]))] + (ArcCos[1/a] + 2*I*(ArcTanh[((-1 + a)*Cot[(1/2)*ArcSec[a + b*x]])/Sqrt[-1 + a^2]] - ArcTanh[((1 + a)*Tan[(1/2)*ArcSec[a + b*x]])/Sqrt[-1 + a^2]]))*Log[(Sqrt[-1 + a^2]*E^((1/2)*I*ArcSec[a + b*x]))/(Sqrt[2]*Sqrt[a]*Sqrt[-((b*x)/(a + b*x))])] - (ArcCos[1/a] + 2*I*ArcTanh[((1 + a)*Tan[(1/2)*ArcSec[a + b*x]])/Sqrt[-1 + a^2]])*Log[((-1 + a)*(1 + a + I*Sqrt[-1 + a^2])*(1 - I*Tan[(1/2)*ArcSec[a + b*x]]))/(a*(-1 + a + Sqrt[-1 + a^2]*Tan[(1/2)*ArcSec[a + b*x]]))] - (ArcCos[1/a] - 2*I*ArcTanh[((1 + a)*Tan[(1/2)*ArcSec[a + b*x]])/Sqrt[-1 + a^2]])*Log[((-1 + a)*(1 + a - I*Sqrt[-1 + a^2])*(1 + I*Tan[(1/2)*ArcSec[a + b*x]]))/(a*(-1 + a + Sqrt[-1 + a^2]*Tan[(1/2)*ArcSec[a + b*x]]))] + I*(-PolyLog[2, ((1 - I*Sqrt[-1 + a^2])*(1 - a + Sqrt[-1 + a^2]*Tan[(1/2)*ArcSec[a + b*x]]))/(a*(-1 + a + Sqrt[-1 + a^2]*Tan[(1/2)*ArcSec[a + b*x]]))] + PolyLog[2, ((1 + I*Sqrt[-1 + a^2])*(1 - a + Sqrt[-1 + a^2]*Tan[(1/2)*ArcSec[a + b*x]]))/(a*(-1 + a + Sqrt[-1 + a^2]*Tan[(1/2)*ArcSec[a + b*x]]))]))))), Int[ArcSec[a + b*x]^2/x^2, x]}


{x^2*ArcSec[a + b*x]^3, x, 25, ((a + b*x)*ArcSec[a + b*x])/b^3 - (3*I*a*ArcSec[a + b*x]^2)/b^3 + (3*a*(a + b*x)*Sqrt[1 - 1/(a + b*x)^2]*ArcSec[a + b*x]^2)/b^3 - ((a + b*x)^2*Sqrt[1 - 1/(a + b*x)^2]*ArcSec[a + b*x]^2)/(2*b^3) + (a^3*ArcSec[a + b*x]^3)/(3*b^3) + (1/3)*x^3*ArcSec[a + b*x]^3 + (I*ArcSec[a + b*x]^2*ArcTan[E^(I*ArcSec[a + b*x])])/b^3 + (6*I*a^2*ArcSec[a + b*x]^2*ArcTan[E^(I*ArcSec[a + b*x])])/b^3 - ArcTanh[Sqrt[1 - 1/(a + b*x)^2]]/b^3 + (6*a*ArcSec[a + b*x]*Log[1 + E^(2*I*ArcSec[a + b*x])])/b^3 - (I*ArcSec[a + b*x]*PolyLog[2, (-I)*E^(I*ArcSec[a + b*x])])/b^3 - (6*I*a^2*ArcSec[a + b*x]*PolyLog[2, (-I)*E^(I*ArcSec[a + b*x])])/b^3 + (I*ArcSec[a + b*x]*PolyLog[2, I*E^(I*ArcSec[a + b*x])])/b^3 + (6*I*a^2*ArcSec[a + b*x]*PolyLog[2, I*E^(I*ArcSec[a + b*x])])/b^3 - (3*I*a*PolyLog[2, -E^(2*I*ArcSec[a + b*x])])/b^3 + PolyLog[3, (-I)*E^(I*ArcSec[a + b*x])]/b^3 + (6*a^2*PolyLog[3, (-I)*E^(I*ArcSec[a + b*x])])/b^3 - PolyLog[3, I*E^(I*ArcSec[a + b*x])]/b^3 - (6*a^2*PolyLog[3, I*E^(I*ArcSec[a + b*x])])/b^3}
{x^1*ArcSec[a + b*x]^3, x, 16, (3*I*ArcSec[a + b*x]^2)/(2*b^2) - (3*(a + b*x)*Sqrt[1 - 1/(a + b*x)^2]*ArcSec[a + b*x]^2)/(2*b^2) - (a^2*ArcSec[a + b*x]^3)/(2*b^2) + (1/2)*x^2*ArcSec[a + b*x]^3 - (6*I*a*ArcSec[a + b*x]^2*ArcTan[E^(I*ArcSec[a + b*x])])/b^2 - (3*ArcSec[a + b*x]*Log[1 + E^(2*I*ArcSec[a + b*x])])/b^2 + (6*I*a*ArcSec[a + b*x]*PolyLog[2, (-I)*E^(I*ArcSec[a + b*x])])/b^2 - (6*I*a*ArcSec[a + b*x]*PolyLog[2, I*E^(I*ArcSec[a + b*x])])/b^2 + (3*I*PolyLog[2, -E^(2*I*ArcSec[a + b*x])])/(2*b^2) - (6*a*PolyLog[3, (-I)*E^(I*ArcSec[a + b*x])])/b^2 + (6*a*PolyLog[3, I*E^(I*ArcSec[a + b*x])])/b^2}
{x^0*ArcSec[a + b*x]^3, x, 9, ((a + b*x)*ArcSec[a + b*x]^3)/b + (6*I*ArcSec[a + b*x]^2*ArcTan[E^(I*ArcSec[a + b*x])])/b - (6*I*ArcSec[a + b*x]*PolyLog[2, (-I)*E^(I*ArcSec[a + b*x])])/b + (6*I*ArcSec[a + b*x]*PolyLog[2, I*E^(I*ArcSec[a + b*x])])/b + (6*PolyLog[3, (-I)*E^(I*ArcSec[a + b*x])])/b - (6*PolyLog[3, I*E^(I*ArcSec[a + b*x])])/b}
{ArcSec[a + b*x]^3/x^1, x, 0, Int[ArcSec[a + b*x]^3/x, x]}
{ArcSec[a + b*x]^3/x^2, x, 0, Int[ArcSec[a + b*x]^3/x^2, x]}


(* ::Section::Closed:: *)
(*Integrands of the form x^m (a+b ArcSec[c+d x^n])*)


{x^1*(a + b*ArcSec[c + d*x^2]), x, 7, (a*x^2)/2 + (b*(c + d*x^2)*ArcSec[c + d*x^2])/(2*d) - (b*ArcTanh[Sqrt[1 - 1/(c + d*x^2)^2]])/(2*d)}


{x^2*(a + b*ArcSec[c + d*x^3]), x, 7, (a*x^3)/3 + (b*(c + d*x^3)*ArcSec[c + d*x^3])/(3*d) - (b*ArcTanh[Sqrt[1 - 1/(c + d*x^3)^2]])/(3*d)}


{x^3*(a + b*ArcSec[c + d*x^4]), x, 7, (a*x^4)/4 + (b*(c + d*x^4)*ArcSec[c + d*x^4])/(4*d) - (b*ArcTanh[Sqrt[1 - 1/(c + d*x^4)^2]])/(4*d)}


{x^(n-1)*ArcSec[a + b*x^n], x, 6, ((a + b*x^n)*ArcSec[a + b*x^n])/(b*n) - ArcTanh[Sqrt[1 - 1/(a + b*x^n)^2]]/(b*n)}


(* ::Section::Closed:: *)
(*Integrands involving inverse secant functions of exponentials*)


{ArcSec[c*E^(a + b*x)], x, 7, (I*ArcSec[c*E^(a + b*x)]^2)/(2*b) - (ArcSec[c*E^(a + b*x)]*Log[1 + E^(2*I*ArcSec[c*E^(a + b*x)])])/b + (I*PolyLog[2, -E^(2*I*ArcSec[c*E^(a + b*x)])])/(2*b)}


(* ::Section::Closed:: *)
(*Integrands involving exponentials of inverse secant functions*)


{E^ArcSec[a*x]*x^2, x, 6, -(((12/5 + (4*I)/5)*E^((1 + 3*I)*ArcSec[a*x])*Hypergeometric2F1[3/2 - I/2, 3, 5/2 - I/2, -E^(2*I*ArcSec[a*x])])/a^3) + ((24/5 + (8*I)/5)*E^((1 + 3*I)*ArcSec[a*x])*Hypergeometric2F1[3/2 - I/2, 4, 5/2 - I/2, -E^(2*I*ArcSec[a*x])])/a^3}
{E^ArcSec[a*x]*x^1, x, 6, -(((8/5 + (4*I)/5)*E^((1 + 2*I)*ArcSec[a*x])*Hypergeometric2F1[1 - I/2, 2, 2 - I/2, -E^(2*I*ArcSec[a*x])])/a^2) + ((16/5 + (8*I)/5)*E^((1 + 2*I)*ArcSec[a*x])*Hypergeometric2F1[1 - I/2, 3, 2 - I/2, -E^(2*I*ArcSec[a*x])])/a^2}
{E^ArcSec[a*x]*x^0, x, 5, -(((1 + I)*E^((1 + I)*ArcSec[a*x])*Hypergeometric2F1[1/2 - I/2, 1, 3/2 - I/2, -E^(2*I*ArcSec[a*x])])/a) + ((2 + 2*I)*E^((1 + I)*ArcSec[a*x])*Hypergeometric2F1[1/2 - I/2, 2, 3/2 - I/2, -E^(2*I*ArcSec[a*x])])/a}
{E^ArcSec[a*x]/x^1, x, 6, (-I)*E^ArcSec[a*x] + 2*I*E^ArcSec[a*x]*Hypergeometric2F1[-(I/2), 1, 1 - I/2, -E^(2*I*ArcSec[a*x])]}
{E^ArcSec[a*x]/x^2, x, 3, (1/2)*a*E^ArcSec[a*x]*Sqrt[1 - 1/(a^2*x^2)] - E^ArcSec[a*x]/(2*x)}
{E^ArcSec[a*x]/x^3, x, 5, (-(1/5))*a^2*E^ArcSec[a*x]*Cos[2*ArcSec[a*x]] + (1/10)*a^2*E^ArcSec[a*x]*Sin[2*ArcSec[a*x]]}
{E^ArcSec[a*x]/x^4, x, 6, (1/8)*a^3*E^ArcSec[a*x]*Sqrt[1 - 1/(a^2*x^2)] - (a^2*E^ArcSec[a*x])/(8*x) - (3/40)*a^3*E^ArcSec[a*x]*Cos[3*ArcSec[a*x]] + (1/40)*a^3*E^ArcSec[a*x]*Sin[3*ArcSec[a*x]]}


(* ::Section::Closed:: *)
(*Miscellaneous integrands involving inverse secants*)


{ArcSec[a + b*x]/((a*d)/b + d*x), x, 8, (I*ArcSec[b*(a/b + x)]^2)/(2*d) - (ArcSec[b*(a/b + x)]*Log[1 + E^(2*I*ArcSec[b*(a/b + x)])])/d + (I*PolyLog[2, -E^(2*I*ArcSec[b*(a/b + x)])])/(2*d)}
