(* ::Package:: *)

(* ::Title:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p (a+b ArcTan[c x])^n*)


(* ::Section::Closed:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p (a+b ArcTan[c x])^1*)


(* ::Subsection::Closed:: *)
(*Integrands of the form x^m (d+e x^2)^p (a+b ArcTan[c x])*)


(* ::Subsubsection::Closed:: *)
(*p>0*)


{x^3*(a + b*ArcTan[c*x])*(d + e*x^2), x, 5, (b*(3*c^2*d - 2*e)*x)/(12*c^5) - (b*(3*c^2*d - 2*e)*x^3)/(36*c^3) - (b*e*x^5)/(30*c) - (b*(3*c^2*d - 2*e)*ArcTan[c*x])/(12*c^6) + (1/4)*d*x^4*(a + b*ArcTan[c*x]) + (1/6)*e*x^6*(a + b*ArcTan[c*x])}
{x^2*(a + b*ArcTan[c*x])*(d + e*x^2), x, 4, -((b*(5*c^2*d - 3*e)*x^2)/(30*c^3)) - (b*e*x^4)/(20*c) + (1/3)*d*x^3*(a + b*ArcTan[c*x]) + (1/5)*e*x^5*(a + b*ArcTan[c*x]) + (b*(5*c^2*d - 3*e)*Log[1 + c^2*x^2])/(30*c^5)}
{x^1*(a + b*ArcTan[c*x])*(d + e*x^2), x, 4, -((b*(2*c^2*d - e)*x)/(4*c^3)) - (b*e*x^3)/(12*c) - (b*(c^2*d - e)^2*ArcTan[c*x])/(4*c^4*e) + ((d + e*x^2)^2*(a + b*ArcTan[c*x]))/(4*e)}
{x^0*(a + b*ArcTan[c*x])*(d + e*x^2), x, 3, -((b*e*x^2)/(6*c)) + d*x*(a + b*ArcTan[c*x]) + (1/3)*e*x^3*(a + b*ArcTan[c*x]) - (b*(3*c^2*d - e)*Log[1 + c^2*x^2])/(6*c^3)}
{(a + b*ArcTan[c*x])*(d + e*x^2)/x^1, x, 9, -((b*e*x)/(2*c)) + (b*e*ArcTan[c*x])/(2*c^2) + (1/2)*e*x^2*(a + b*ArcTan[c*x]) + a*d*Log[x] + (1/2)*I*b*d*PolyLog[2, (-I)*c*x] - (1/2)*I*b*d*PolyLog[2, I*c*x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)/x^2, x, 4, -((d*(a + b*ArcTan[c*x]))/x) + e*x*(a + b*ArcTan[c*x]) + b*c*d*Log[x] - (b*(c^2*d + e)*Log[1 + c^2*x^2])/(2*c)}
{(a + b*ArcTan[c*x])*(d + e*x^2)/x^3, x, 9, -((b*c*d)/(2*x)) - (1/2)*b*c^2*d*ArcTan[c*x] - (d*(a + b*ArcTan[c*x]))/(2*x^2) + a*e*Log[x] + (1/2)*I*b*e*PolyLog[2, (-I)*c*x] - (1/2)*I*b*e*PolyLog[2, I*c*x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)/x^4, x, 5, -((b*c*d)/(6*x^2)) - (d*(a + b*ArcTan[c*x]))/(3*x^3) - (e*(a + b*ArcTan[c*x]))/x - (1/3)*b*c*(c^2*d - 3*e)*Log[x] + (1/6)*b*c*(c^2*d - 3*e)*Log[1 + c^2*x^2]}
{(a + b*ArcTan[c*x])*(d + e*x^2)/x^5, x, 5, -((b*c*d)/(12*x^3)) + (b*c*(c^2*d - 2*e))/(4*x) + (1/4)*b*c^2*(c^2*d - 2*e)*ArcTan[c*x] - (d*(a + b*ArcTan[c*x]))/(4*x^4) - (e*(a + b*ArcTan[c*x]))/(2*x^2)}
{(a + b*ArcTan[c*x])*(d + e*x^2)/x^6, x, 5, -((b*c*d)/(20*x^4)) + (b*c*(3*c^2*d - 5*e))/(30*x^2) - (d*(a + b*ArcTan[c*x]))/(5*x^5) - (e*(a + b*ArcTan[c*x]))/(3*x^3) + (1/15)*b*c^3*(3*c^2*d - 5*e)*Log[x] - (1/30)*b*c^3*(3*c^2*d - 5*e)*Log[1 + c^2*x^2]}
{(a + b*ArcTan[c*x])*(d + e*x^2)/x^7, x, 6, -((b*c*d)/(30*x^5)) + (b*c*(2*c^2*d - 3*e))/(36*x^3) - (b*c^3*(2*c^2*d - 3*e))/(12*x) - (1/12)*b*c^4*(2*c^2*d - 3*e)*ArcTan[c*x] - (d*(a + b*ArcTan[c*x]))/(6*x^6) - (e*(a + b*ArcTan[c*x]))/(4*x^4)}


{x^3*(a + b*ArcTan[c*x])*(d + e*x^2)^2, x, 4, (b*(6*c^4*d^2 - 8*c^2*d*e + 3*e^2)*x)/(24*c^7) - (b*(6*c^4*d^2 - 8*c^2*d*e + 3*e^2)*x^3)/(72*c^5) - (b*(8*c^2*d - 3*e)*e*x^5)/(120*c^3) - (b*e^2*x^7)/(56*c) - (b*(6*c^4*d^2 - 8*c^2*d*e + 3*e^2)*ArcTan[c*x])/(24*c^8) + (1/4)*d^2*x^4*(a + b*ArcTan[c*x]) + (1/3)*d*e*x^6*(a + b*ArcTan[c*x]) + (1/8)*e^2*x^8*(a + b*ArcTan[c*x])}
{x^2*(a + b*ArcTan[c*x])*(d + e*x^2)^2, x, 5, -((b*(35*c^4*d^2 - 42*c^2*d*e + 15*e^2)*x^2)/(210*c^5)) - (b*(14*c^2*d - 5*e)*e*x^4)/(140*c^3) - (b*e^2*x^6)/(42*c) + (1/3)*d^2*x^3*(a + b*ArcTan[c*x]) + (2/5)*d*e*x^5*(a + b*ArcTan[c*x]) + (1/7)*e^2*x^7*(a + b*ArcTan[c*x]) + (b*(35*c^4*d^2 - 42*c^2*d*e + 15*e^2)*Log[1 + c^2*x^2])/(210*c^7)}
{x^1*(a + b*ArcTan[c*x])*(d + e*x^2)^2, x, 4, -((b*(3*c^4*d^2 - 3*c^2*d*e + e^2)*x)/(6*c^5)) - (b*(3*c^2*d - e)*e*x^3)/(18*c^3) - (b*e^2*x^5)/(30*c) - (b*(c^2*d - e)^3*ArcTan[c*x])/(6*c^6*e) + ((d + e*x^2)^3*(a + b*ArcTan[c*x]))/(6*e)}
{x^0*(a + b*ArcTan[c*x])*(d + e*x^2)^2, x, 3, -((b*(10*c^2*d - 3*e)*e*x^2)/(30*c^3)) - (b*e^2*x^4)/(20*c) + d^2*x*(a + b*ArcTan[c*x]) + (2/3)*d*e*x^3*(a + b*ArcTan[c*x]) + (1/5)*e^2*x^5*(a + b*ArcTan[c*x]) - (b*(15*c^4*d^2 - 10*c^2*d*e + 3*e^2)*Log[1 + c^2*x^2])/(30*c^5)}
{(a + b*ArcTan[c*x])*(d + e*x^2)^2/x^1, x, 13, -((b*d*e*x)/c) + (b*e^2*x)/(4*c^3) - (b*e^2*x^3)/(12*c) + (b*d*e*ArcTan[c*x])/c^2 - (b*e^2*ArcTan[c*x])/(4*c^4) + d*e*x^2*(a + b*ArcTan[c*x]) + (1/4)*e^2*x^4*(a + b*ArcTan[c*x]) + a*d^2*Log[x] + (1/2)*I*b*d^2*PolyLog[2, (-I)*c*x] - (1/2)*I*b*d^2*PolyLog[2, I*c*x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^2/x^2, x, 4, -((b*e^2*x^2)/(6*c)) - (d^2*(a + b*ArcTan[c*x]))/x + 2*d*e*x*(a + b*ArcTan[c*x]) + (1/3)*e^2*x^3*(a + b*ArcTan[c*x]) + b*c*d^2*Log[x] - (b*(3*c^4*d^2 + 6*c^2*d*e - e^2)*Log[1 + c^2*x^2])/(6*c^3)}
{(a + b*ArcTan[c*x])*(d + e*x^2)^2/x^3, x, 12, -((b*c*d^2)/(2*x)) - (b*e^2*x)/(2*c) - (1/2)*b*c^2*d^2*ArcTan[c*x] + (b*e^2*ArcTan[c*x])/(2*c^2) - (d^2*(a + b*ArcTan[c*x]))/(2*x^2) + (1/2)*e^2*x^2*(a + b*ArcTan[c*x]) + 2*a*d*e*Log[x] + I*b*d*e*PolyLog[2, (-I)*c*x] - I*b*d*e*PolyLog[2, I*c*x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^2/x^4, x, 5, -((b*c*d^2)/(6*x^2)) - (d^2*(a + b*ArcTan[c*x]))/(3*x^3) - (2*d*e*(a + b*ArcTan[c*x]))/x + e^2*x*(a + b*ArcTan[c*x]) - (1/3)*b*c*d*(c^2*d - 6*e)*Log[x] + (b*(c^4*d^2 - 6*c^2*d*e - 3*e^2)*Log[1 + c^2*x^2])/(6*c)}
{(a + b*ArcTan[c*x])*(d + e*x^2)^2/x^5, x, 13, -((b*c*d^2)/(12*x^3)) + (b*c^3*d^2)/(4*x) - (b*c*d*e)/x + (1/4)*b*c^4*d^2*ArcTan[c*x] - b*c^2*d*e*ArcTan[c*x] - (d^2*(a + b*ArcTan[c*x]))/(4*x^4) - (d*e*(a + b*ArcTan[c*x]))/x^2 + a*e^2*Log[x] + (1/2)*I*b*e^2*PolyLog[2, (-I)*c*x] - (1/2)*I*b*e^2*PolyLog[2, I*c*x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^2/x^6, x, 5, -((b*c*d^2)/(20*x^4)) + (b*c*d*(3*c^2*d - 10*e))/(30*x^2) - (d^2*(a + b*ArcTan[c*x]))/(5*x^5) - (2*d*e*(a + b*ArcTan[c*x]))/(3*x^3) - (e^2*(a + b*ArcTan[c*x]))/x + (1/15)*b*c*(3*c^4*d^2 - 10*c^2*d*e + 15*e^2)*Log[x] - (1/30)*b*c*(3*c^4*d^2 - 10*c^2*d*e + 15*e^2)*Log[1 + c^2*x^2]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^2/x^7, x, 5, -((b*c*d^2)/(30*x^5)) + (b*c*d*(c^2*d - 3*e))/(18*x^3) - (b*c*(c^4*d^2 - 3*c^2*d*e + 3*e^2))/(6*x) - (b*(c^2*d - e)^3*ArcTan[c*x])/(6*d) - ((d + e*x^2)^3*(a + b*ArcTan[c*x]))/(6*d*x^6)}
{(a + b*ArcTan[c*x])*(d + e*x^2)^2/x^8, x, 5, -((b*c*d^2)/(42*x^6)) + (b*c*d*(5*c^2*d - 14*e))/(140*x^4) - (b*c*(15*c^4*d^2 - 42*c^2*d*e + 35*e^2))/(210*x^2) - (d^2*(a + b*ArcTan[c*x]))/(7*x^7) - (2*d*e*(a + b*ArcTan[c*x]))/(5*x^5) - (e^2*(a + b*ArcTan[c*x]))/(3*x^3) - (1/105)*b*c^3*(15*c^4*d^2 - 42*c^2*d*e + 35*e^2)*Log[x] + (1/210)*b*c^3*(15*c^4*d^2 - 42*c^2*d*e + 35*e^2)*Log[1 + c^2*x^2]}


{x^3*(a + b*ArcTan[c*x])*(d + e*x^2)^3, x, -8, (b*(10*c^6*d^3 - 20*c^4*d^2*e + 15*c^2*d*e^2 - 4*e^3)*x)/(40*c^9) - (b*(10*c^6*d^3 - 20*c^4*d^2*e + 15*c^2*d*e^2 - 4*e^3)*x^3)/(120*c^7) - (b*e*(20*c^4*d^2 - 15*c^2*d*e + 4*e^2)*x^5)/(200*c^5) - (b*(15*c^2*d - 4*e)*e^2*x^7)/(280*c^3) - (b*e^3*x^9)/(90*c) + (b*(c^2*d - e)^4*(c^2*d + 4*e)*ArcTan[c*x])/(40*c^10*e^2) - (d*(d + e*x^2)^4*(a + b*ArcTan[c*x]))/(8*e^2) + ((d + e*x^2)^5*(a + b*ArcTan[c*x]))/(10*e^2)}
{x^2*(a + b*ArcTan[c*x])*(d + e*x^2)^3, x, 5, -((b*(105*c^6*d^3 - 189*c^4*d^2*e + 135*c^2*d*e^2 - 35*e^3)*x^2)/(630*c^7)) - (b*e*(189*c^4*d^2 - 135*c^2*d*e + 35*e^2)*x^4)/(1260*c^5) - (b*(27*c^2*d - 7*e)*e^2*x^6)/(378*c^3) - (b*e^3*x^8)/(72*c) + (1/3)*d^3*x^3*(a + b*ArcTan[c*x]) + (3/5)*d^2*e*x^5*(a + b*ArcTan[c*x]) + (3/7)*d*e^2*x^7*(a + b*ArcTan[c*x]) + (1/9)*e^3*x^9*(a + b*ArcTan[c*x]) + (b*(105*c^6*d^3 - 189*c^4*d^2*e + 135*c^2*d*e^2 - 35*e^3)*Log[1 + c^2*x^2])/(630*c^9)}
{x^1*(a + b*ArcTan[c*x])*(d + e*x^2)^3, x, 4, -((b*(2*c^2*d - e)*(2*c^4*d^2 - 2*c^2*d*e + e^2)*x)/(8*c^7)) - (b*e*(6*c^4*d^2 - 4*c^2*d*e + e^2)*x^3)/(24*c^5) - (b*(4*c^2*d - e)*e^2*x^5)/(40*c^3) - (b*e^3*x^7)/(56*c) - (b*(c^2*d - e)^4*ArcTan[c*x])/(8*c^8*e) + ((d + e*x^2)^4*(a + b*ArcTan[c*x]))/(8*e)}
{x^0*(a + b*ArcTan[c*x])*(d + e*x^2)^3, x, 3, -((b*e*(35*c^4*d^2 - 21*c^2*d*e + 5*e^2)*x^2)/(70*c^5)) - (b*(21*c^2*d - 5*e)*e^2*x^4)/(140*c^3) - (b*e^3*x^6)/(42*c) + d^3*x*(a + b*ArcTan[c*x]) + d^2*e*x^3*(a + b*ArcTan[c*x]) + (3/5)*d*e^2*x^5*(a + b*ArcTan[c*x]) + (1/7)*e^3*x^7*(a + b*ArcTan[c*x]) - (b*(35*c^6*d^3 - 35*c^4*d^2*e + 21*c^2*d*e^2 - 5*e^3)*Log[1 + c^2*x^2])/(70*c^7)}
{(a + b*ArcTan[c*x])*(d + e*x^2)^3/x^1, x, 17, -((3*b*d^2*e*x)/(2*c)) + (3*b*d*e^2*x)/(4*c^3) - (b*e^3*x)/(6*c^5) - (b*d*e^2*x^3)/(4*c) + (b*e^3*x^3)/(18*c^3) - (b*e^3*x^5)/(30*c) + (3*b*d^2*e*ArcTan[c*x])/(2*c^2) - (3*b*d*e^2*ArcTan[c*x])/(4*c^4) + (b*e^3*ArcTan[c*x])/(6*c^6) + (3/2)*d^2*e*x^2*(a + b*ArcTan[c*x]) + (3/4)*d*e^2*x^4*(a + b*ArcTan[c*x]) + (1/6)*e^3*x^6*(a + b*ArcTan[c*x]) + a*d^3*Log[x] + (1/2)*I*b*d^3*PolyLog[2, (-I)*c*x] - (1/2)*I*b*d^3*PolyLog[2, I*c*x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^3/x^2, x, 4, -((b*(5*c^2*d - e)*e^2*x^2)/(10*c^3)) - (b*e^3*x^4)/(20*c) - (d^3*(a + b*ArcTan[c*x]))/x + 3*d^2*e*x*(a + b*ArcTan[c*x]) + d*e^2*x^3*(a + b*ArcTan[c*x]) + (1/5)*e^3*x^5*(a + b*ArcTan[c*x]) + b*c*d^3*Log[x] - (b*(5*c^6*d^3 + 15*c^4*d^2*e - 5*c^2*d*e^2 + e^3)*Log[1 + c^2*x^2])/(10*c^5)}
{(a + b*ArcTan[c*x])*(d + e*x^2)^3/x^3, x, 16, -((b*c*d^3)/(2*x)) - (3*b*d*e^2*x)/(2*c) + (b*e^3*x)/(4*c^3) - (b*e^3*x^3)/(12*c) - (1/2)*b*c^2*d^3*ArcTan[c*x] + (3*b*d*e^2*ArcTan[c*x])/(2*c^2) - (b*e^3*ArcTan[c*x])/(4*c^4) - (d^3*(a + b*ArcTan[c*x]))/(2*x^2) + (3/2)*d*e^2*x^2*(a + b*ArcTan[c*x]) + (1/4)*e^3*x^4*(a + b*ArcTan[c*x]) + 3*a*d^2*e*Log[x] + (3/2)*I*b*d^2*e*PolyLog[2, (-I)*c*x] - (3/2)*I*b*d^2*e*PolyLog[2, I*c*x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^3/x^4, x, 5, -((b*c*d^3)/(6*x^2)) - (b*e^3*x^2)/(6*c) - (d^3*(a + b*ArcTan[c*x]))/(3*x^3) - (3*d^2*e*(a + b*ArcTan[c*x]))/x + 3*d*e^2*x*(a + b*ArcTan[c*x]) + (1/3)*e^3*x^3*(a + b*ArcTan[c*x]) - (1/3)*b*c*d^2*(c^2*d - 9*e)*Log[x] + (b*(c^2*d + e)*(c^4*d^2 - 10*c^2*d*e + e^2)*Log[1 + c^2*x^2])/(6*c^3)}
{(a + b*ArcTan[c*x])*(d + e*x^2)^3/x^5, x, 16, -((b*c*d^3)/(12*x^3)) + (b*c^3*d^3)/(4*x) - (3*b*c*d^2*e)/(2*x) - (b*e^3*x)/(2*c) + (1/4)*b*c^4*d^3*ArcTan[c*x] - (3/2)*b*c^2*d^2*e*ArcTan[c*x] + (b*e^3*ArcTan[c*x])/(2*c^2) - (d^3*(a + b*ArcTan[c*x]))/(4*x^4) - (3*d^2*e*(a + b*ArcTan[c*x]))/(2*x^2) + (1/2)*e^3*x^2*(a + b*ArcTan[c*x]) + 3*a*d*e^2*Log[x] + (3/2)*I*b*d*e^2*PolyLog[2, (-I)*c*x] - (3/2)*I*b*d*e^2*PolyLog[2, I*c*x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^3/x^6, x, 5, -((b*c*d^3)/(20*x^4)) + (b*c*d^2*(c^2*d - 5*e))/(10*x^2) - (d^3*(a + b*ArcTan[c*x]))/(5*x^5) - (d^2*e*(a + b*ArcTan[c*x]))/x^3 - (3*d*e^2*(a + b*ArcTan[c*x]))/x + e^3*x*(a + b*ArcTan[c*x]) + (1/5)*b*c*d*(c^4*d^2 - 5*c^2*d*e + 15*e^2)*Log[x] - (b*(c^6*d^3 - 5*c^4*d^2*e + 15*c^2*d*e^2 + 5*e^3)*Log[1 + c^2*x^2])/(10*c)}
{(a + b*ArcTan[c*x])*(d + e*x^2)^3/x^7, x, 18, -((b*c*d^3)/(30*x^5)) + (b*c^3*d^3)/(18*x^3) - (b*c*d^2*e)/(4*x^3) - (b*c^5*d^3)/(6*x) + (3*b*c^3*d^2*e)/(4*x) - (3*b*c*d*e^2)/(2*x) - (1/6)*b*c^6*d^3*ArcTan[c*x] + (3/4)*b*c^4*d^2*e*ArcTan[c*x] - (3/2)*b*c^2*d*e^2*ArcTan[c*x] - (d^3*(a + b*ArcTan[c*x]))/(6*x^6) - (3*d^2*e*(a + b*ArcTan[c*x]))/(4*x^4) - (3*d*e^2*(a + b*ArcTan[c*x]))/(2*x^2) + a*e^3*Log[x] + (1/2)*I*b*e^3*PolyLog[2, (-I)*c*x] - (1/2)*I*b*e^3*PolyLog[2, I*c*x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^3/x^8, x, 5, -((b*c*d^3)/(42*x^6)) + (b*c*d^2*(5*c^2*d - 21*e))/(140*x^4) - (b*c*d*(5*c^4*d^2 - 21*c^2*d*e + 35*e^2))/(70*x^2) - (d^3*(a + b*ArcTan[c*x]))/(7*x^7) - (3*d^2*e*(a + b*ArcTan[c*x]))/(5*x^5) - (d*e^2*(a + b*ArcTan[c*x]))/x^3 - (e^3*(a + b*ArcTan[c*x]))/x - (1/35)*b*c*(5*c^6*d^3 - 21*c^4*d^2*e + 35*c^2*d*e^2 - 35*e^3)*Log[x] + (1/70)*b*c*(5*c^6*d^3 - 21*c^4*d^2*e + 35*c^2*d*e^2 - 35*e^3)*Log[1 + c^2*x^2]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^3/x^9, x, 5, -((b*c*d^3)/(56*x^7)) + (b*c*d^2*(c^2*d - 4*e))/(40*x^5) - (b*c*d*(c^4*d^2 - 4*c^2*d*e + 6*e^2))/(24*x^3) + (b*c*(c^2*d - 2*e)*(c^4*d^2 - 2*c^2*d*e + 2*e^2))/(8*x) + (b*(c^2*d - e)^4*ArcTan[c*x])/(8*d) - ((d + e*x^2)^4*(a + b*ArcTan[c*x]))/(8*d*x^8)}


{ArcTan[a*x]*(c + d*x^2)^4, x, 3, -((d*(420*a^6*c^3 - 378*a^4*c^2*d + 180*a^2*c*d^2 - 35*d^3)*x^2)/(630*a^7)) - (d^2*(378*a^4*c^2 - 180*a^2*c*d + 35*d^2)*x^4)/(1260*a^5) - ((36*a^2*c - 7*d)*d^3*x^6)/(378*a^3) - (d^4*x^8)/(72*a) + c^4*x*ArcTan[a*x] + (4/3)*c^3*d*x^3*ArcTan[a*x] + (6/5)*c^2*d^2*x^5*ArcTan[a*x] + (4/7)*c*d^3*x^7*ArcTan[a*x] + (1/9)*d^4*x^9*ArcTan[a*x] - ((315*a^8*c^4 - 420*a^6*c^3*d + 378*a^4*c^2*d^2 - 180*a^2*c*d^3 + 35*d^4)*Log[1 + a^2*x^2])/(630*a^9)}


(* ::Subsubsection::Closed:: *)
(*p<0*)


{x^3*(a + b*ArcTan[c*x])/(d + e*x^2), x, 18, -((b*x)/(2*c*e)) + (b*ArcTan[c*x])/(2*c^2*e) + (x^2*(a + b*ArcTan[c*x]))/(2*e) + (I*b*d*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*e^2) - (I*b*d*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*e^2) - (I*b*d*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*e^2) + (I*b*d*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*e^2) - (a*d*Log[d + e*x^2])/(2*e^2) - (I*b*d*PolyLog[2, -((Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*e^2) - (I*b*d*PolyLog[2, (Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*e^2) + (I*b*d*PolyLog[2, -((Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*e^2) + (I*b*d*PolyLog[2, (Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*e^2)}
{x^2*(a + b*ArcTan[c*x])/(d + e*x^2), x, 19, (a*x)/e + (b*x*ArcTan[c*x])/e - (a*Sqrt[d]*ArcTan[(Sqrt[e]*x)/Sqrt[d]])/e^(3/2) - (I*b*Sqrt[-d]*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*e^(3/2)) + (I*b*Sqrt[-d]*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*e^(3/2)) - (I*b*Sqrt[-d]*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*e^(3/2)) + (I*b*Sqrt[-d]*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*e^(3/2)) - (b*Log[1 + c^2*x^2])/(2*c*e) + (I*b*Sqrt[-d]*PolyLog[2, -((Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*e^(3/2)) - (I*b*Sqrt[-d]*PolyLog[2, (Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*e^(3/2)) + (I*b*Sqrt[-d]*PolyLog[2, -((Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*e^(3/2)) - (I*b*Sqrt[-d]*PolyLog[2, (Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*e^(3/2))}
{x^1*(a + b*ArcTan[c*x])/(d + e*x^2), x, 14, -((I*b*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*e)) + (I*b*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*e) + (I*b*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*e) - (I*b*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*e) + (a*Log[d + e*x^2])/(2*e) + (I*b*PolyLog[2, -((Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*e) + (I*b*PolyLog[2, (Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*e) - (I*b*PolyLog[2, -((Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*e) - (I*b*PolyLog[2, (Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*e)}
{x^0*(a + b*ArcTan[c*x])/(d + e*x^2), x, 15, (a*ArcTan[(Sqrt[e]*x)/Sqrt[d]])/(Sqrt[d]*Sqrt[e]) - (I*b*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*Sqrt[-d]*Sqrt[e]) + (I*b*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*Sqrt[-d]*Sqrt[e]) - (I*b*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*Sqrt[-d]*Sqrt[e]) + (I*b*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*Sqrt[-d]*Sqrt[e]) + (I*b*PolyLog[2, -((Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*Sqrt[-d]*Sqrt[e]) - (I*b*PolyLog[2, (Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*Sqrt[-d]*Sqrt[e]) + (I*b*PolyLog[2, -((Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*Sqrt[-d]*Sqrt[e]) - (I*b*PolyLog[2, (Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*Sqrt[-d]*Sqrt[e])}
{(a + b*ArcTan[c*x])/(x^1*(d + e*x^2)), x, 20, (a*Log[x])/d + (I*b*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*d) - (I*b*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*d) - (I*b*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*d) + (I*b*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*d) - (a*Log[d + e*x^2])/(2*d) + (I*b*PolyLog[2, (-I)*c*x])/(2*d) - (I*b*PolyLog[2, I*c*x])/(2*d) - (I*b*PolyLog[2, -((Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*d) - (I*b*PolyLog[2, (Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*d) + (I*b*PolyLog[2, -((Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*d) + (I*b*PolyLog[2, (Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*d)}
{(a + b*ArcTan[c*x])/(x^2*(d + e*x^2)), x, 21, -((a + b*ArcTan[c*x])/(d*x)) - (a*Sqrt[e]*ArcTan[(Sqrt[e]*x)/Sqrt[d]])/d^(3/2) + (b*c*Log[x])/d - (I*b*Sqrt[e]*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*(-d)^(3/2)) + (I*b*Sqrt[e]*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*(-d)^(3/2)) - (I*b*Sqrt[e]*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*(-d)^(3/2)) + (I*b*Sqrt[e]*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*(-d)^(3/2)) - (b*c*Log[1 + c^2*x^2])/(2*d) + (I*b*Sqrt[e]*PolyLog[2, -((Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*(-d)^(3/2)) - (I*b*Sqrt[e]*PolyLog[2, (Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*(-d)^(3/2)) + (I*b*Sqrt[e]*PolyLog[2, -((Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*(-d)^(3/2)) - (I*b*Sqrt[e]*PolyLog[2, (Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*(-d)^(3/2))}
{(a + b*ArcTan[c*x])/(x^3*(d + e*x^2)), x, 24, -((b*c)/(2*d*x)) - (b*c^2*ArcTan[c*x])/(2*d) - (a + b*ArcTan[c*x])/(2*d*x^2) - (a*e*Log[x])/d^2 - (I*b*e*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*d^2) + (I*b*e*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*d^2) + (I*b*e*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*d^2) - (I*b*e*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*d^2) + (a*e*Log[d + e*x^2])/(2*d^2) - (I*b*e*PolyLog[2, (-I)*c*x])/(2*d^2) + (I*b*e*PolyLog[2, I*c*x])/(2*d^2) + (I*b*e*PolyLog[2, -((Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*d^2) + (I*b*e*PolyLog[2, (Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*d^2) - (I*b*e*PolyLog[2, -((Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*d^2) - (I*b*e*PolyLog[2, (Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*d^2)}


{x^3*(a + b*ArcTan[c*x])/(d + e*x^2)^2, x, 20, -((b*c^2*d*ArcTan[c*x])/(2*(c^2*d - e)*e^2)) + (d*(a + b*ArcTan[c*x]))/(2*e^2*(d + e*x^2)) + (b*c*Sqrt[d]*ArcTan[(Sqrt[e]*x)/Sqrt[d]])/(2*(c^2*d - e)*e^(3/2)) - (I*b*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*e^2) + (I*b*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*e^2) + (I*b*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*e^2) - (I*b*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*e^2) + (a*Log[d + e*x^2])/(2*e^2) + (I*b*PolyLog[2, -((Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*e^2) + (I*b*PolyLog[2, (Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*e^2) - (I*b*PolyLog[2, -((Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*e^2) - (I*b*PolyLog[2, (Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*e^2)}
{x^2*(a + b*ArcTan[c*x])/(d + e*x^2)^2, x, 36, -((x*(a + b*ArcTan[c*x]))/(2*e*(d + e*x^2))) + (a*ArcTan[(Sqrt[e]*x)/Sqrt[d]])/(Sqrt[d]*e^(3/2)) - ((a + b*ArcTan[c*x])*ArcTan[(Sqrt[e]*x)/Sqrt[d]])/(2*Sqrt[d]*e^(3/2)) - (I*b*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*Sqrt[-d]*e^(3/2)) + (I*b*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*Sqrt[-d]*e^(3/2)) - (I*b*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*Sqrt[-d]*e^(3/2)) + (I*b*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*Sqrt[-d]*e^(3/2)) - (I*b*c*Log[(Sqrt[e]*(1 - Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] + Sqrt[e])]*Log[1 - (I*Sqrt[e]*x)/Sqrt[d]])/(8*Sqrt[-c^2]*Sqrt[d]*e^(3/2)) + (I*b*c*Log[-((Sqrt[e]*(1 + Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] - Sqrt[e]))]*Log[1 - (I*Sqrt[e]*x)/Sqrt[d]])/(8*Sqrt[-c^2]*Sqrt[d]*e^(3/2)) + (I*b*c*Log[-((Sqrt[e]*(1 - Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] - Sqrt[e]))]*Log[1 + (I*Sqrt[e]*x)/Sqrt[d]])/(8*Sqrt[-c^2]*Sqrt[d]*e^(3/2)) - (I*b*c*Log[(Sqrt[e]*(1 + Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] + Sqrt[e])]*Log[1 + (I*Sqrt[e]*x)/Sqrt[d]])/(8*Sqrt[-c^2]*Sqrt[d]*e^(3/2)) + (b*c*Log[1 + c^2*x^2])/(4*(c^2*d - e)*e) - (b*c*Log[d + e*x^2])/(4*(c^2*d - e)*e) + (I*b*PolyLog[2, -((Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*Sqrt[-d]*e^(3/2)) - (I*b*PolyLog[2, (Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*Sqrt[-d]*e^(3/2)) + (I*b*PolyLog[2, -((Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*Sqrt[-d]*e^(3/2)) - (I*b*PolyLog[2, (Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*Sqrt[-d]*e^(3/2)) - (I*b*c*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] - I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] - I*Sqrt[e])])/(8*Sqrt[-c^2]*Sqrt[d]*e^(3/2)) + (I*b*c*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] - I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] + I*Sqrt[e])])/(8*Sqrt[-c^2]*Sqrt[d]*e^(3/2)) - (I*b*c*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] + I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] - I*Sqrt[e])])/(8*Sqrt[-c^2]*Sqrt[d]*e^(3/2)) + (I*b*c*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] + I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] + I*Sqrt[e])])/(8*Sqrt[-c^2]*Sqrt[d]*e^(3/2))}
{x^1*(a + b*ArcTan[c*x])/(d + e*x^2)^2, x, 4, (b*c^2*ArcTan[c*x])/(2*(c^2*d - e)*e) - (a + b*ArcTan[c*x])/(2*e*(d + e*x^2)) - (b*c*ArcTan[(Sqrt[e]*x)/Sqrt[d]])/(2*Sqrt[d]*(c^2*d - e)*Sqrt[e])}
{x^0*(a + b*ArcTan[c*x])/(d + e*x^2)^2, x, 19, (x*(a + b*ArcTan[c*x]))/(2*d*(d + e*x^2)) + ((a + b*ArcTan[c*x])*ArcTan[(Sqrt[e]*x)/Sqrt[d]])/(2*d^(3/2)*Sqrt[e]) + (I*b*c*Log[(Sqrt[e]*(1 - Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] + Sqrt[e])]*Log[1 - (I*Sqrt[e]*x)/Sqrt[d]])/(8*Sqrt[-c^2]*d^(3/2)*Sqrt[e]) - (I*b*c*Log[-((Sqrt[e]*(1 + Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] - Sqrt[e]))]*Log[1 - (I*Sqrt[e]*x)/Sqrt[d]])/(8*Sqrt[-c^2]*d^(3/2)*Sqrt[e]) - (I*b*c*Log[-((Sqrt[e]*(1 - Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] - Sqrt[e]))]*Log[1 + (I*Sqrt[e]*x)/Sqrt[d]])/(8*Sqrt[-c^2]*d^(3/2)*Sqrt[e]) + (I*b*c*Log[(Sqrt[e]*(1 + Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] + Sqrt[e])]*Log[1 + (I*Sqrt[e]*x)/Sqrt[d]])/(8*Sqrt[-c^2]*d^(3/2)*Sqrt[e]) - (b*c*Log[1 + c^2*x^2])/(4*d*(c^2*d - e)) + (b*c*Log[d + e*x^2])/(4*d*(c^2*d - e)) + (I*b*c*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] - I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] - I*Sqrt[e])])/(8*Sqrt[-c^2]*d^(3/2)*Sqrt[e]) - (I*b*c*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] - I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] + I*Sqrt[e])])/(8*Sqrt[-c^2]*d^(3/2)*Sqrt[e]) + (I*b*c*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] + I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] - I*Sqrt[e])])/(8*Sqrt[-c^2]*d^(3/2)*Sqrt[e]) - (I*b*c*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] + I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] + I*Sqrt[e])])/(8*Sqrt[-c^2]*d^(3/2)*Sqrt[e])}
{(a + b*ArcTan[c*x])/(x^1*(d + e*x^2)^2), x, 24, -((b*c^2*ArcTan[c*x])/(2*d*(c^2*d - e))) + (a + b*ArcTan[c*x])/(2*d*(d + e*x^2)) + (b*c*Sqrt[e]*ArcTan[(Sqrt[e]*x)/Sqrt[d]])/(2*d^(3/2)*(c^2*d - e)) + (a*Log[x])/d^2 + (I*b*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*d^2) - (I*b*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*d^2) - (I*b*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*d^2) + (I*b*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*d^2) - (a*Log[d + e*x^2])/(2*d^2) + (I*b*PolyLog[2, (-I)*c*x])/(2*d^2) - (I*b*PolyLog[2, I*c*x])/(2*d^2) - (I*b*PolyLog[2, -((Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*d^2) - (I*b*PolyLog[2, (Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*d^2) + (I*b*PolyLog[2, -((Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*d^2) + (I*b*PolyLog[2, (Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*d^2)}
{(a + b*ArcTan[c*x])/(x^2*(d + e*x^2)^2), x, 41, -((a + b*ArcTan[c*x])/(d^2*x)) - (e*x*(a + b*ArcTan[c*x]))/(2*d^2*(d + e*x^2)) - (a*Sqrt[e]*ArcTan[(Sqrt[e]*x)/Sqrt[d]])/d^(5/2) - (Sqrt[e]*(a + b*ArcTan[c*x])*ArcTan[(Sqrt[e]*x)/Sqrt[d]])/(2*d^(5/2)) + (b*c*Log[x])/d^2 + (I*b*Sqrt[e]*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*(-d)^(5/2)) - (I*b*Sqrt[e]*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*(-d)^(5/2)) + (I*b*Sqrt[e]*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*(-d)^(5/2)) - (I*b*Sqrt[e]*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*(-d)^(5/2)) - (I*b*c*Sqrt[e]*Log[(Sqrt[e]*(1 - Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] + Sqrt[e])]*Log[1 - (I*Sqrt[e]*x)/Sqrt[d]])/(8*Sqrt[-c^2]*d^(5/2)) + (I*b*c*Sqrt[e]*Log[-((Sqrt[e]*(1 + Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] - Sqrt[e]))]*Log[1 - (I*Sqrt[e]*x)/Sqrt[d]])/(8*Sqrt[-c^2]*d^(5/2)) + (I*b*c*Sqrt[e]*Log[-((Sqrt[e]*(1 - Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] - Sqrt[e]))]*Log[1 + (I*Sqrt[e]*x)/Sqrt[d]])/(8*Sqrt[-c^2]*d^(5/2)) - (I*b*c*Sqrt[e]*Log[(Sqrt[e]*(1 + Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] + Sqrt[e])]*Log[1 + (I*Sqrt[e]*x)/Sqrt[d]])/(8*Sqrt[-c^2]*d^(5/2)) - (b*c*Log[1 + c^2*x^2])/(2*d^2) + (b*c*e*Log[1 + c^2*x^2])/(4*d^2*(c^2*d - e)) - (b*c*e*Log[d + e*x^2])/(4*d^2*(c^2*d - e)) - (I*b*Sqrt[e]*PolyLog[2, -((Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*(-d)^(5/2)) + (I*b*Sqrt[e]*PolyLog[2, (Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*(-d)^(5/2)) - (I*b*Sqrt[e]*PolyLog[2, -((Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*(-d)^(5/2)) + (I*b*Sqrt[e]*PolyLog[2, (Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*(-d)^(5/2)) - (I*b*c*Sqrt[e]*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] - I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] - I*Sqrt[e])])/(8*Sqrt[-c^2]*d^(5/2)) + (I*b*c*Sqrt[e]*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] - I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] + I*Sqrt[e])])/(8*Sqrt[-c^2]*d^(5/2)) - (I*b*c*Sqrt[e]*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] + I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] - I*Sqrt[e])])/(8*Sqrt[-c^2]*d^(5/2)) + (I*b*c*Sqrt[e]*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] + I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] + I*Sqrt[e])])/(8*Sqrt[-c^2]*d^(5/2))}
{(a + b*ArcTan[c*x])/(x^3*(d + e*x^2)^2), x, 27, -((b*c)/(2*d^2*x)) - (b*c^2*ArcTan[c*x])/(2*d^2) + (b*c^2*e*ArcTan[c*x])/(2*d^2*(c^2*d - e)) - (a + b*ArcTan[c*x])/(2*d^2*x^2) - (e*(a + b*ArcTan[c*x]))/(2*d^2*(d + e*x^2)) - (b*c*e^(3/2)*ArcTan[(Sqrt[e]*x)/Sqrt[d]])/(2*d^(5/2)*(c^2*d - e)) - (2*a*e*Log[x])/d^3 - (I*b*e*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(2*d^3) + (I*b*e*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(2*d^3) + (I*b*e*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(2*d^3) - (I*b*e*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(2*d^3) + (a*e*Log[d + e*x^2])/d^3 - (I*b*e*PolyLog[2, (-I)*c*x])/d^3 + (I*b*e*PolyLog[2, I*c*x])/d^3 + (I*b*e*PolyLog[2, -((Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(2*d^3) + (I*b*e*PolyLog[2, (Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(2*d^3) - (I*b*e*PolyLog[2, -((Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(2*d^3) - (I*b*e*PolyLog[2, (Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(2*d^3)}


{x^3*(a + b*ArcTan[c*x])/(d + e*x^2)^3, x, 6, (b*c*x)/(8*(c^2*d - e)*e*(d + e*x^2)) - (b*ArcTan[c*x])/(4*d*(c^2*d - e)^2) + (x^4*(a + b*ArcTan[c*x]))/(4*d*(d + e*x^2)^2) - (b*c*(c^2*d - 3*e)*ArcTan[(Sqrt[e]*x)/Sqrt[d]])/(8*Sqrt[d]*(c^2*d - e)^2*e^(3/2))}
{x^2*(a + b*ArcTan[c*x])/(d + e*x^2)^3, x, 39, (b*c)/(8*(c^2*d - e)*e*(d + e*x^2)) - (x*(a + b*ArcTan[c*x]))/(4*e*(d + e*x^2)^2) + (x*(a + b*ArcTan[c*x]))/(8*d*e*(d + e*x^2)) + ((a + b*ArcTan[c*x])*ArcTan[(Sqrt[e]*x)/Sqrt[d]])/(8*d^(3/2)*e^(3/2)) + (I*b*c*Log[(Sqrt[e]*(1 - Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] + Sqrt[e])]*Log[1 - (I*Sqrt[e]*x)/Sqrt[d]])/(32*Sqrt[-c^2]*d^(3/2)*e^(3/2)) - (I*b*c*Log[-((Sqrt[e]*(1 + Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] - Sqrt[e]))]*Log[1 - (I*Sqrt[e]*x)/Sqrt[d]])/(32*Sqrt[-c^2]*d^(3/2)*e^(3/2)) - (I*b*c*Log[-((Sqrt[e]*(1 - Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] - Sqrt[e]))]*Log[1 + (I*Sqrt[e]*x)/Sqrt[d]])/(32*Sqrt[-c^2]*d^(3/2)*e^(3/2)) + (I*b*c*Log[(Sqrt[e]*(1 + Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] + Sqrt[e])]*Log[1 + (I*Sqrt[e]*x)/Sqrt[d]])/(32*Sqrt[-c^2]*d^(3/2)*e^(3/2)) + (b*c*(5*c^2*d - 3*e)*Log[1 + c^2*x^2])/(16*d*(c^2*d - e)^2*e) - (b*c*Log[1 + c^2*x^2])/(4*d*(c^2*d - e)*e) - (b*c*(5*c^2*d - 3*e)*Log[d + e*x^2])/(16*d*(c^2*d - e)^2*e) + (b*c*Log[d + e*x^2])/(4*d*(c^2*d - e)*e) + (I*b*c*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] - I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] - I*Sqrt[e])])/(32*Sqrt[-c^2]*d^(3/2)*e^(3/2)) - (I*b*c*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] - I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] + I*Sqrt[e])])/(32*Sqrt[-c^2]*d^(3/2)*e^(3/2)) + (I*b*c*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] + I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] - I*Sqrt[e])])/(32*Sqrt[-c^2]*d^(3/2)*e^(3/2)) - (I*b*c*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] + I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] + I*Sqrt[e])])/(32*Sqrt[-c^2]*d^(3/2)*e^(3/2))}
{x^1*(a + b*ArcTan[c*x])/(d + e*x^2)^3, x, 5, -((b*c*x)/(8*d*(c^2*d - e)*(d + e*x^2))) + (b*c^4*ArcTan[c*x])/(4*(c^2*d - e)^2*e) - (a + b*ArcTan[c*x])/(4*e*(d + e*x^2)^2) - (b*c*(3*c^2*d - e)*ArcTan[(Sqrt[e]*x)/Sqrt[d]])/(8*d^(3/2)*(c^2*d - e)^2*Sqrt[e])}
{x^0*(a + b*ArcTan[c*x])/(d + e*x^2)^3, x, 18, -((b*c)/(8*d*(c^2*d - e)*(d + e*x^2))) + (x*(a + b*ArcTan[c*x]))/(4*d*(d + e*x^2)^2) + (3*x*(a + b*ArcTan[c*x]))/(8*d^2*(d + e*x^2)) + (3*(a + b*ArcTan[c*x])*ArcTan[(Sqrt[e]*x)/Sqrt[d]])/(8*d^(5/2)*Sqrt[e]) + (3*I*b*c*Log[(Sqrt[e]*(1 - Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] + Sqrt[e])]*Log[1 - (I*Sqrt[e]*x)/Sqrt[d]])/(32*Sqrt[-c^2]*d^(5/2)*Sqrt[e]) - (3*I*b*c*Log[-((Sqrt[e]*(1 + Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] - Sqrt[e]))]*Log[1 - (I*Sqrt[e]*x)/Sqrt[d]])/(32*Sqrt[-c^2]*d^(5/2)*Sqrt[e]) - (3*I*b*c*Log[-((Sqrt[e]*(1 - Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] - Sqrt[e]))]*Log[1 + (I*Sqrt[e]*x)/Sqrt[d]])/(32*Sqrt[-c^2]*d^(5/2)*Sqrt[e]) + (3*I*b*c*Log[(Sqrt[e]*(1 + Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] + Sqrt[e])]*Log[1 + (I*Sqrt[e]*x)/Sqrt[d]])/(32*Sqrt[-c^2]*d^(5/2)*Sqrt[e]) - (b*c*(5*c^2*d - 3*e)*Log[1 + c^2*x^2])/(16*d^2*(c^2*d - e)^2) + (b*c*(5*c^2*d - 3*e)*Log[d + e*x^2])/(16*d^2*(c^2*d - e)^2) + (3*I*b*c*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] - I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] - I*Sqrt[e])])/(32*Sqrt[-c^2]*d^(5/2)*Sqrt[e]) - (3*I*b*c*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] - I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] + I*Sqrt[e])])/(32*Sqrt[-c^2]*d^(5/2)*Sqrt[e]) + (3*I*b*c*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] + I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] - I*Sqrt[e])])/(32*Sqrt[-c^2]*d^(5/2)*Sqrt[e]) - (3*I*b*c*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] + I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] + I*Sqrt[e])])/(32*Sqrt[-c^2]*d^(5/2)*Sqrt[e])}
{(a + b*ArcTan[c*x])/(x^1*(d + e*x^2)^3), x, 29, (b*c*e*x)/(8*d^2*(c^2*d - e)*(d + e*x^2)) - (b*c^4*ArcTan[c*x])/(4*d*(c^2*d - e)^2) - (b*c^2*ArcTan[c*x])/(2*d^2*(c^2*d - e)) + (a + b*ArcTan[c*x])/(4*d*(d + e*x^2)^2) + (a + b*ArcTan[c*x])/(2*d^2*(d + e*x^2)) + (b*c*Sqrt[e]*ArcTan[(Sqrt[e]*x)/Sqrt[d]])/(2*d^(5/2)*(c^2*d - e)) + (b*c*(3*c^2*d - e)*Sqrt[e]*ArcTan[(Sqrt[e]*x)/Sqrt[d]])/(8*d^(5/2)*(c^2*d - e)^2) + (a*Log[x])/d^3 + (I*b*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*d^3) - (I*b*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*d^3) - (I*b*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*d^3) + (I*b*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*d^3) - (a*Log[d + e*x^2])/(2*d^3) + (I*b*PolyLog[2, (-I)*c*x])/(2*d^3) - (I*b*PolyLog[2, I*c*x])/(2*d^3) - (I*b*PolyLog[2, -((Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*d^3) - (I*b*PolyLog[2, (Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*d^3) + (I*b*PolyLog[2, -((Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*d^3) + (I*b*PolyLog[2, (Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*d^3)}
{(a + b*ArcTan[c*x])/(x^2*(d + e*x^2)^3), x, 59, (b*c*e)/(8*d^2*(c^2*d - e)*(d + e*x^2)) - (a + b*ArcTan[c*x])/(d^3*x) - (e*x*(a + b*ArcTan[c*x]))/(4*d^2*(d + e*x^2)^2) - (7*e*x*(a + b*ArcTan[c*x]))/(8*d^3*(d + e*x^2)) - (a*Sqrt[e]*ArcTan[(Sqrt[e]*x)/Sqrt[d]])/d^(7/2) - (7*Sqrt[e]*(a + b*ArcTan[c*x])*ArcTan[(Sqrt[e]*x)/Sqrt[d]])/(8*d^(7/2)) + (b*c*Log[x])/d^3 - (I*b*Sqrt[e]*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*(-d)^(7/2)) + (I*b*Sqrt[e]*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*(-d)^(7/2)) - (I*b*Sqrt[e]*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*(-d)^(7/2)) + (I*b*Sqrt[e]*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*(-d)^(7/2)) - (7*I*b*c*Sqrt[e]*Log[(Sqrt[e]*(1 - Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] + Sqrt[e])]*Log[1 - (I*Sqrt[e]*x)/Sqrt[d]])/(32*Sqrt[-c^2]*d^(7/2)) + (7*I*b*c*Sqrt[e]*Log[-((Sqrt[e]*(1 + Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] - Sqrt[e]))]*Log[1 - (I*Sqrt[e]*x)/Sqrt[d]])/(32*Sqrt[-c^2]*d^(7/2)) + (7*I*b*c*Sqrt[e]*Log[-((Sqrt[e]*(1 - Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] - Sqrt[e]))]*Log[1 + (I*Sqrt[e]*x)/Sqrt[d]])/(32*Sqrt[-c^2]*d^(7/2)) - (7*I*b*c*Sqrt[e]*Log[(Sqrt[e]*(1 + Sqrt[-c^2]*x))/(I*Sqrt[-c^2]*Sqrt[d] + Sqrt[e])]*Log[1 + (I*Sqrt[e]*x)/Sqrt[d]])/(32*Sqrt[-c^2]*d^(7/2)) - (b*c*Log[1 + c^2*x^2])/(2*d^3) + (b*c*(5*c^2*d - 3*e)*e*Log[1 + c^2*x^2])/(16*d^3*(c^2*d - e)^2) + (b*c*e*Log[1 + c^2*x^2])/(4*d^3*(c^2*d - e)) - (b*c*(5*c^2*d - 3*e)*e*Log[d + e*x^2])/(16*d^3*(c^2*d - e)^2) - (b*c*e*Log[d + e*x^2])/(4*d^3*(c^2*d - e)) + (I*b*Sqrt[e]*PolyLog[2, -((Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*(-d)^(7/2)) - (I*b*Sqrt[e]*PolyLog[2, (Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*(-d)^(7/2)) + (I*b*Sqrt[e]*PolyLog[2, -((Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*(-d)^(7/2)) - (I*b*Sqrt[e]*PolyLog[2, (Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*(-d)^(7/2)) - (7*I*b*c*Sqrt[e]*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] - I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] - I*Sqrt[e])])/(32*Sqrt[-c^2]*d^(7/2)) + (7*I*b*c*Sqrt[e]*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] - I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] + I*Sqrt[e])])/(32*Sqrt[-c^2]*d^(7/2)) - (7*I*b*c*Sqrt[e]*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] + I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] - I*Sqrt[e])])/(32*Sqrt[-c^2]*d^(7/2)) + (7*I*b*c*Sqrt[e]*PolyLog[2, (Sqrt[-c^2]*(Sqrt[d] + I*Sqrt[e]*x))/(Sqrt[-c^2]*Sqrt[d] + I*Sqrt[e])])/(32*Sqrt[-c^2]*d^(7/2))}
{(a + b*ArcTan[c*x])/(x^3*(d + e*x^2)^3), x, 32, -((b*c)/(2*d^3*x)) - (b*c*e^2*x)/(8*d^3*(c^2*d - e)*(d + e*x^2)) - (b*c^2*ArcTan[c*x])/(2*d^3) + (b*c^4*e*ArcTan[c*x])/(4*d^2*(c^2*d - e)^2) + (b*c^2*e*ArcTan[c*x])/(d^3*(c^2*d - e)) - (a + b*ArcTan[c*x])/(2*d^3*x^2) - (e*(a + b*ArcTan[c*x]))/(4*d^2*(d + e*x^2)^2) - (e*(a + b*ArcTan[c*x]))/(d^3*(d + e*x^2)) - (b*c*e^(3/2)*ArcTan[(Sqrt[e]*x)/Sqrt[d]])/(d^(7/2)*(c^2*d - e)) - (b*c*(3*c^2*d - e)*e^(3/2)*ArcTan[(Sqrt[e]*x)/Sqrt[d]])/(8*d^(7/2)*(c^2*d - e)^2) - (3*a*e*Log[x])/d^4 - (3*I*b*e*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*d^4) + (3*I*b*e*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] - Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*d^4) + (3*I*b*e*Log[1 - I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] - I*Sqrt[e])])/(4*d^4) - (3*I*b*e*Log[1 + I*c*x]*Log[(c*(Sqrt[-d] + Sqrt[e]*x))/(c*Sqrt[-d] + I*Sqrt[e])])/(4*d^4) + (3*a*e*Log[d + e*x^2])/(2*d^4) - (3*I*b*e*PolyLog[2, (-I)*c*x])/(2*d^4) + (3*I*b*e*PolyLog[2, I*c*x])/(2*d^4) + (3*I*b*e*PolyLog[2, -((Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*d^4) + (3*I*b*e*PolyLog[2, (Sqrt[e]*(1 - I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*d^4) - (3*I*b*e*PolyLog[2, -((Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] - Sqrt[e]))])/(4*d^4) - (3*I*b*e*PolyLog[2, (Sqrt[e]*(1 + I*c*x))/(I*c*Sqrt[-d] + Sqrt[e])])/(4*d^4)}


(* ::Subsection::Closed:: *)
(*Integrands of the form x^m (d+e x^2)^(p/2) (a+b ArcTan[c x])*)


(* ::Subsubsection::Closed:: *)
(*p>0*)


{x^3*(a + b*ArcTan[c*x])*(d + e*x^2)^(1/2), x, If[$VersionNumber>=8, 9, 10], If[$VersionNumber>=8, -((b*(c^2*d - 12*e)*x*Sqrt[d + e*x^2])/(120*c^3*e)) - (b*x*(d + e*x^2)^(3/2))/(20*c*e) - (d*(d + e*x^2)^(3/2)*(a + b*ArcTan[c*x]))/(3*e^2) + ((d + e*x^2)^(5/2)*(a + b*ArcTan[c*x]))/(5*e^2) + (b*(c^2*d - e)^(3/2)*(2*c^2*d + 3*e)*ArcTan[(Sqrt[c^2*d - e]*x)/Sqrt[d + e*x^2]])/(15*c^5*e^2) + (b*(15*c^4*d^2 + 20*c^2*d*e - 24*e^2)*ArcTanh[(Sqrt[e]*x)/Sqrt[d + e*x^2]])/(120*c^5*e^(3/2)), -((b*(c^2*d - 12*e)*x*Sqrt[d + e*x^2])/(120*c^3*e)) - (b*x*(d + e*x^2)^(3/2))/(20*c*e) - (d*(d + e*x^2)^(3/2)*(a + b*ArcTan[c*x]))/(3*e^2) + ((d + e*x^2)^(5/2)*(a + b*ArcTan[c*x]))/(5*e^2) + (b*(c^2*d - e)^(3/2)*(2*c^2*d + 3*e)*ArcTan[(Sqrt[c^2*d - e]*x)/Sqrt[d + e*x^2]])/(15*c^5*e^2) + (b*(15*c^4*d^2 + 20*c^2*d*e - 24*e^2)*ArcTanh[(Sqrt[e]*x)/Sqrt[d + e*x^2]])/(120*c^5*e^(3/2))]}
{x^2*(a + b*ArcTan[c*x])*(d + e*x^2)^(1/2), x, 5, (a*d*x*Sqrt[d + e*x^2])/(8*e) + (1/4)*a*x^3*Sqrt[d + e*x^2] - (a*d^2*ArcTanh[(Sqrt[e]*x)/Sqrt[d + e*x^2]])/(8*e^(3/2)) + b*Defer[Int][x^2*Sqrt[d + e*x^2]*ArcTan[c*x], x]}
{x^1*(a + b*ArcTan[c*x])*(d + e*x^2)^(1/2), x, 7, -((b*x*Sqrt[d + e*x^2])/(6*c)) + ((d + e*x^2)^(3/2)*(a + b*ArcTan[c*x]))/(3*e) - (b*(c^2*d - e)^(3/2)*ArcTan[(Sqrt[c^2*d - e]*x)/Sqrt[d + e*x^2]])/(3*c^3*e) - (b*(3*c^2*d - 2*e)*ArcTanh[(Sqrt[e]*x)/Sqrt[d + e*x^2]])/(6*c^3*Sqrt[e])}
{x^0*(a + b*ArcTan[c*x])*(d + e*x^2)^(1/2), x, 0, Defer[Int][Sqrt[d + e*x^2]*(a + b*ArcTan[c*x]), x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^(1/2)/x^1, x, 5, a*Sqrt[d + e*x^2] - a*Sqrt[d]*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]] + b*Defer[Int][(Sqrt[d + e*x^2]*ArcTan[c*x])/x, x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^(1/2)/x^2, x, 4, -((a*Sqrt[d + e*x^2])/x) + a*Sqrt[e]*ArcTanh[(Sqrt[e]*x)/Sqrt[d + e*x^2]] + b*Defer[Int][(Sqrt[d + e*x^2]*ArcTan[c*x])/x^2, x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^(1/2)/x^3, x, 5, -((a*Sqrt[d + e*x^2])/(2*x^2)) - (a*e*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/(2*Sqrt[d]) + b*Defer[Int][(Sqrt[d + e*x^2]*ArcTan[c*x])/x^3, x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^(1/2)/x^4, x, 9, -((b*c*Sqrt[d + e*x^2])/(6*x^2)) - ((d + e*x^2)^(3/2)*(a + b*ArcTan[c*x]))/(3*d*x^3) + (b*c*(2*c^2*d - 3*e)*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/(6*Sqrt[d]) - (b*(c^2*d - e)^(3/2)*ArcTanh[(c*Sqrt[d + e*x^2])/Sqrt[c^2*d - e]])/(3*d)}
{(a + b*ArcTan[c*x])*(d + e*x^2)^(1/2)/x^5, x, 6, -((a*Sqrt[d + e*x^2])/(4*x^4)) - (a*e*Sqrt[d + e*x^2])/(8*d*x^2) + (a*e^2*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/(8*d^(3/2)) + b*Defer[Int][(Sqrt[d + e*x^2]*ArcTan[c*x])/x^5, x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^(1/2)/x^6, x, If[$VersionNumber>=8, 10, 21], If[$VersionNumber>=8, (b*c*(12*c^2*d - e)*Sqrt[d + e*x^2])/(120*d*x^2) - (b*c*(d + e*x^2)^(3/2))/(20*d*x^4) - ((d + e*x^2)^(3/2)*(a + b*ArcTan[c*x]))/(5*d*x^5) + (2*e*(d + e*x^2)^(3/2)*(a + b*ArcTan[c*x]))/(15*d^2*x^3) - (b*c*(24*c^4*d^2 - 20*c^2*d*e - 15*e^2)*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/(120*d^(3/2)) + (b*(c^2*d - e)^(3/2)*(3*c^2*d + 2*e)*ArcTanh[(c*Sqrt[d + e*x^2])/Sqrt[c^2*d - e]])/(15*d^2), -((b*c*Sqrt[d + e*x^2])/(20*x^4)) + (b*c*(3*c^2*d - e)*Sqrt[d + e*x^2])/(30*d*x^2) - (b*c*e*Sqrt[d + e*x^2])/(40*d*x^2) - ((d + e*x^2)^(3/2)*(a + b*ArcTan[c*x]))/(5*d*x^5) + (2*e*(d + e*x^2)^(3/2)*(a + b*ArcTan[c*x]))/(15*d^2*x^3) + (b*c*(3*c^2*d - e)*e*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/(30*d^(3/2)) + (b*c*e^2*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/(40*d^(3/2)) - (b*c*(c^2*d - e)*(3*c^2*d + 2*e)*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/(15*d^(3/2)) + (b*(c^2*d - e)^(3/2)*(3*c^2*d + 2*e)*ArcTanh[(c*Sqrt[d + e*x^2])/Sqrt[c^2*d - e]])/(15*d^2)]}


{x^3*(a + b*ArcTan[c*x])*(d + e*x^2)^(3/2), x, 10, (b*(3*c^4*d^2 + 54*c^2*d*e - 40*e^2)*x*Sqrt[d + e*x^2])/(560*c^5*e) - (b*(13*c^2*d - 30*e)*x*(d + e*x^2)^(3/2))/(840*c^3*e) - (b*x*(d + e*x^2)^(5/2))/(42*c*e) - (d*(d + e*x^2)^(5/2)*(a + b*ArcTan[c*x]))/(5*e^2) + ((d + e*x^2)^(7/2)*(a + b*ArcTan[c*x]))/(7*e^2) + (b*(c^2*d - e)^(5/2)*(2*c^2*d + 5*e)*ArcTan[(Sqrt[c^2*d - e]*x)/Sqrt[d + e*x^2]])/(35*c^7*e^2) + (b*(35*c^6*d^3 + 70*c^4*d^2*e - 168*c^2*d*e^2 + 80*e^3)*ArcTanh[(Sqrt[e]*x)/Sqrt[d + e*x^2]])/(560*c^7*e^(3/2))}
{x^2*(a + b*ArcTan[c*x])*(d + e*x^2)^(3/2), x, 6, (a*d^2*x*Sqrt[d + e*x^2])/(16*e) + (1/8)*a*d*x^3*Sqrt[d + e*x^2] + (1/6)*a*x^3*(d + e*x^2)^(3/2) - (a*d^3*ArcTanh[(Sqrt[e]*x)/Sqrt[d + e*x^2]])/(16*e^(3/2)) + b*Defer[Int][x^2*(d + e*x^2)^(3/2)*ArcTan[c*x], x]}
{x^1*(a + b*ArcTan[c*x])*(d + e*x^2)^(3/2), x, 8, -((b*(7*c^2*d - 4*e)*x*Sqrt[d + e*x^2])/(40*c^3)) - (b*x*(d + e*x^2)^(3/2))/(20*c) + ((d + e*x^2)^(5/2)*(a + b*ArcTan[c*x]))/(5*e) - (b*(c^2*d - e)^(5/2)*ArcTan[(Sqrt[c^2*d - e]*x)/Sqrt[d + e*x^2]])/(5*c^5*e) - (b*(15*c^4*d^2 - 20*c^2*d*e + 8*e^2)*ArcTanh[(Sqrt[e]*x)/Sqrt[d + e*x^2]])/(40*c^5*Sqrt[e])}
{x^0*(a + b*ArcTan[c*x])*(d + e*x^2)^(3/2), x, 0, Defer[Int][(d + e*x^2)^(3/2)*(a + b*ArcTan[c*x]), x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^(3/2)/x^1, x, 6, a*d*Sqrt[d + e*x^2] + (1/3)*a*(d + e*x^2)^(3/2) - a*d^(3/2)*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]] + b*Defer[Int][((d + e*x^2)^(3/2)*ArcTan[c*x])/x, x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^(3/2)/x^2, x, 5, (3/2)*a*e*x*Sqrt[d + e*x^2] - (a*(d + e*x^2)^(3/2))/x + (3/2)*a*d*Sqrt[e]*ArcTanh[(Sqrt[e]*x)/Sqrt[d + e*x^2]] + b*Defer[Int][((d + e*x^2)^(3/2)*ArcTan[c*x])/x^2, x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^(3/2)/x^3, x, 6, (3/2)*a*e*Sqrt[d + e*x^2] - (a*(d + e*x^2)^(3/2))/(2*x^2) - (3/2)*a*Sqrt[d]*e*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]] + b*Defer[Int][((d + e*x^2)^(3/2)*ArcTan[c*x])/x^3, x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^(3/2)/x^4, x, 5, -((a*e*Sqrt[d + e*x^2])/x) - (a*(d + e*x^2)^(3/2))/(3*x^3) + a*e^(3/2)*ArcTanh[(Sqrt[e]*x)/Sqrt[d + e*x^2]] + b*Defer[Int][((d + e*x^2)^(3/2)*ArcTan[c*x])/x^4, x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^(3/2)/x^5, x, 6, -((3*a*e*Sqrt[d + e*x^2])/(8*x^2)) - (a*(d + e*x^2)^(3/2))/(4*x^4) - (3*a*e^2*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/(8*Sqrt[d]) + b*Defer[Int][((d + e*x^2)^(3/2)*ArcTan[c*x])/x^5, x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^(3/2)/x^6, x, 10, (b*c*(4*c^2*d - 7*e)*Sqrt[d + e*x^2])/(40*x^2) - (b*c*(d + e*x^2)^(3/2))/(20*x^4) - ((d + e*x^2)^(5/2)*(a + b*ArcTan[c*x]))/(5*d*x^5) - (b*c*(8*c^4*d^2 - 20*c^2*d*e + 15*e^2)*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/(40*Sqrt[d]) + (b*(c^2*d - e)^(5/2)*ArcTanh[(c*Sqrt[d + e*x^2])/Sqrt[c^2*d - e]])/(5*d)}


{x^3*(a + b*ArcTan[c*x])*(d + e*x^2)^(5/2), x, 11, (b*(59*c^6*d^3 + 712*c^4*d^2*e - 1104*c^2*d*e^2 + 448*e^3)*x*Sqrt[d + e*x^2])/(8064*c^7*e) - (b*(69*c^4*d^2 - 520*c^2*d*e + 336*e^2)*x*(d + e*x^2)^(3/2))/(12096*c^5*e) - (b*(33*c^2*d - 56*e)*x*(d + e*x^2)^(5/2))/(3024*c^3*e) - (b*x*(d + e*x^2)^(7/2))/(72*c*e) - (d*(d + e*x^2)^(7/2)*(a + b*ArcTan[c*x]))/(7*e^2) + ((d + e*x^2)^(9/2)*(a + b*ArcTan[c*x]))/(9*e^2) + (b*(c^2*d - e)^(7/2)*(2*c^2*d + 7*e)*ArcTan[(Sqrt[c^2*d - e]*x)/Sqrt[d + e*x^2]])/(63*c^9*e^2) + (b*(315*c^8*d^4 + 840*c^6*d^3*e - 3024*c^4*d^2*e^2 + 2880*c^2*d*e^3 - 896*e^4)*ArcTanh[(Sqrt[e]*x)/Sqrt[d + e*x^2]])/(8064*c^9*e^(3/2))}
{x^2*(a + b*ArcTan[c*x])*(d + e*x^2)^(5/2), x, 7, (5*a*d^3*x*Sqrt[d + e*x^2])/(128*e) + (5/64)*a*d^2*x^3*Sqrt[d + e*x^2] + (5/48)*a*d*x^3*(d + e*x^2)^(3/2) + (1/8)*a*x^3*(d + e*x^2)^(5/2) - (5*a*d^4*ArcTanh[(Sqrt[e]*x)/Sqrt[d + e*x^2]])/(128*e^(3/2)) + b*Defer[Int][x^2*(d + e*x^2)^(5/2)*ArcTan[c*x], x]}
{x^1*(a + b*ArcTan[c*x])*(d + e*x^2)^(5/2), x, 9, -((b*(19*c^4*d^2 - 22*c^2*d*e + 8*e^2)*x*Sqrt[d + e*x^2])/(112*c^5)) - (b*(11*c^2*d - 6*e)*x*(d + e*x^2)^(3/2))/(168*c^3) - (b*x*(d + e*x^2)^(5/2))/(42*c) + ((d + e*x^2)^(7/2)*(a + b*ArcTan[c*x]))/(7*e) - (b*(c^2*d - e)^(7/2)*ArcTan[(Sqrt[c^2*d - e]*x)/Sqrt[d + e*x^2]])/(7*c^7*e) - (b*(35*c^6*d^3 - 70*c^4*d^2*e + 56*c^2*d*e^2 - 16*e^3)*ArcTanh[(Sqrt[e]*x)/Sqrt[d + e*x^2]])/(112*c^7*Sqrt[e])}
{x^0*(a + b*ArcTan[c*x])*(d + e*x^2)^(5/2), x, 0, Defer[Int][(d + e*x^2)^(5/2)*(a + b*ArcTan[c*x]), x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^(5/2)/x^1, x, 7, a*d^2*Sqrt[d + e*x^2] + (1/3)*a*d*(d + e*x^2)^(3/2) + (1/5)*a*(d + e*x^2)^(5/2) - a*d^(5/2)*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]] + b*Defer[Int][((d + e*x^2)^(5/2)*ArcTan[c*x])/x, x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^(5/2)/x^2, x, 6, (15/8)*a*d*e*x*Sqrt[d + e*x^2] + (5/4)*a*e*x*(d + e*x^2)^(3/2) - (a*(d + e*x^2)^(5/2))/x + (15/8)*a*d^2*Sqrt[e]*ArcTanh[(Sqrt[e]*x)/Sqrt[d + e*x^2]] + b*Defer[Int][((d + e*x^2)^(5/2)*ArcTan[c*x])/x^2, x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^(5/2)/x^3, x, 7, (5/2)*a*d*e*Sqrt[d + e*x^2] + (5/6)*a*e*(d + e*x^2)^(3/2) - (a*(d + e*x^2)^(5/2))/(2*x^2) - (5/2)*a*d^(3/2)*e*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]] + b*Defer[Int][((d + e*x^2)^(5/2)*ArcTan[c*x])/x^3, x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^(5/2)/x^4, x, 6, (5/2)*a*e^2*x*Sqrt[d + e*x^2] - (5*a*e*(d + e*x^2)^(3/2))/(3*x) - (a*(d + e*x^2)^(5/2))/(3*x^3) + (5/2)*a*d*e^(3/2)*ArcTanh[(Sqrt[e]*x)/Sqrt[d + e*x^2]] + b*Defer[Int][((d + e*x^2)^(5/2)*ArcTan[c*x])/x^4, x]}


(* ::Subsubsection::Closed:: *)
(*p<0*)


{x^3*(a + b*ArcTan[c*x])/(d + e*x^2)^(1/2), x, 8, -((b*x*Sqrt[d + e*x^2])/(6*c*e)) - (d*Sqrt[d + e*x^2]*(a + b*ArcTan[c*x]))/e^2 + ((d + e*x^2)^(3/2)*(a + b*ArcTan[c*x]))/(3*e^2) + (b*Sqrt[c^2*d - e]*(2*c^2*d + e)*ArcTan[(Sqrt[c^2*d - e]*x)/Sqrt[d + e*x^2]])/(3*c^3*e^2) + (b*(3*c^2*d + 2*e)*ArcTanh[(Sqrt[e]*x)/Sqrt[d + e*x^2]])/(6*c^3*e^(3/2))}
{x^2*(a + b*ArcTan[c*x])/(d + e*x^2)^(1/2), x, 4, (a*x*Sqrt[d + e*x^2])/(2*e) - (a*d*ArcTanh[(Sqrt[e]*x)/Sqrt[d + e*x^2]])/(2*e^(3/2)) + b*Defer[Int][(x^2*ArcTan[c*x])/Sqrt[d + e*x^2], x]}
{x^1*(a + b*ArcTan[c*x])/(d + e*x^2)^(1/2), x, 6, (Sqrt[d + e*x^2]*(a + b*ArcTan[c*x]))/e - (b*Sqrt[c^2*d - e]*ArcTan[(Sqrt[c^2*d - e]*x)/Sqrt[d + e*x^2]])/(c*e) - (b*ArcTanh[(Sqrt[e]*x)/Sqrt[d + e*x^2]])/(c*Sqrt[e])}
{x^0*(a + b*ArcTan[c*x])/(d + e*x^2)^(1/2), x, 0, Defer[Int][(a + b*ArcTan[c*x])/Sqrt[d + e*x^2], x]}
{(a + b*ArcTan[c*x])/(x^1*(d + e*x^2)^(1/2)), x, 4, -((a*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/Sqrt[d]) + b*Defer[Int][ArcTan[c*x]/(x*Sqrt[d + e*x^2]), x]}
{(a + b*ArcTan[c*x])/(x^2*(d + e*x^2)^(1/2)), x, 7, -((Sqrt[d + e*x^2]*(a + b*ArcTan[c*x]))/(d*x)) - (b*c*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/Sqrt[d] + (b*Sqrt[c^2*d - e]*ArcTanh[(c*Sqrt[d + e*x^2])/Sqrt[c^2*d - e]])/d}
{(a + b*ArcTan[c*x])/(x^3*(d + e*x^2)^(1/2)), x, 5, -((a*Sqrt[d + e*x^2])/(2*d*x^2)) + (a*e*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/(2*d^(3/2)) + b*Defer[Int][ArcTan[c*x]/(x^3*Sqrt[d + e*x^2]), x]}
{(a + b*ArcTan[c*x])/(x^4*(d + e*x^2)^(1/2)), x, 9, -((b*c*Sqrt[d + e*x^2])/(6*d*x^2)) - (Sqrt[d + e*x^2]*(a + b*ArcTan[c*x]))/(3*d*x^3) + (2*e*Sqrt[d + e*x^2]*(a + b*ArcTan[c*x]))/(3*d^2*x) + (b*c*(2*c^2*d + 3*e)*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/(6*d^(3/2)) - (b*Sqrt[c^2*d - e]*(c^2*d + 2*e)*ArcTanh[(c*Sqrt[d + e*x^2])/Sqrt[c^2*d - e]])/(3*d^2)}


{x^3*(a + b*ArcTan[c*x])/(d + e*x^2)^(3/2), x, 7, (d*(a + b*ArcTan[c*x]))/(e^2*Sqrt[d + e*x^2]) + (Sqrt[d + e*x^2]*(a + b*ArcTan[c*x]))/e^2 - (b*(2*c^2*d - e)*ArcTan[(Sqrt[c^2*d - e]*x)/Sqrt[d + e*x^2]])/(c*Sqrt[c^2*d - e]*e^2) - (b*ArcTanh[(Sqrt[e]*x)/Sqrt[d + e*x^2]])/(c*e^(3/2))}
{x^2*(a + b*ArcTan[c*x])/(d + e*x^2)^(3/2), x, 4, -((a*x)/(e*Sqrt[d + e*x^2])) + (a*ArcTanh[(Sqrt[e]*x)/Sqrt[d + e*x^2]])/e^(3/2) + b*Defer[Int][(x^2*ArcTan[c*x])/(d + e*x^2)^(3/2), x]}
{x^1*(a + b*ArcTan[c*x])/(d + e*x^2)^(3/2), x, 3, -((a + b*ArcTan[c*x])/(e*Sqrt[d + e*x^2])) + (b*c*ArcTan[(Sqrt[c^2*d - e]*x)/Sqrt[d + e*x^2]])/(Sqrt[c^2*d - e]*e)}
{x^0*(a + b*ArcTan[c*x])/(d + e*x^2)^(3/2), x, 5, (x*(a + b*ArcTan[c*x]))/(d*Sqrt[d + e*x^2]) + (b*ArcTanh[(c*Sqrt[d + e*x^2])/Sqrt[c^2*d - e]])/(d*Sqrt[c^2*d - e])}
{(a + b*ArcTan[c*x])/(x^1*(d + e*x^2)^(3/2)), x, 5, a/(d*Sqrt[d + e*x^2]) - (a*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/d^(3/2) + b*Defer[Int][ArcTan[c*x]/(x*(d + e*x^2)^(3/2)), x]}
{(a + b*ArcTan[c*x])/(x^2*(d + e*x^2)^(3/2)), x, 8, -((a + b*ArcTan[c*x])/(d*x*Sqrt[d + e*x^2])) - (2*e*x*(a + b*ArcTan[c*x]))/(d^2*Sqrt[d + e*x^2]) - (b*c*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/d^(3/2) + (b*(c^2*d - 2*e)*ArcTanh[(c*Sqrt[d + e*x^2])/Sqrt[c^2*d - e]])/(d^2*Sqrt[c^2*d - e])}
{(a + b*ArcTan[c*x])/(x^3*(d + e*x^2)^(3/2)), x, 6, a/(d*x^2*Sqrt[d + e*x^2]) - (3*a*Sqrt[d + e*x^2])/(2*d^2*x^2) + (3*a*e*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/(2*d^(5/2)) + b*Defer[Int][ArcTan[c*x]/(x^3*(d + e*x^2)^(3/2)), x]}
{(a + b*ArcTan[c*x])/(x^4*(d + e*x^2)^(3/2)), x, 14, -((b*c*Sqrt[d + e*x^2])/(6*d^2*x^2)) - (a + b*ArcTan[c*x])/(3*d*x^3*Sqrt[d + e*x^2]) + (4*e*(a + b*ArcTan[c*x]))/(3*d^2*x*Sqrt[d + e*x^2]) + (8*e^2*x*(a + b*ArcTan[c*x]))/(3*d^3*Sqrt[d + e*x^2]) + (b*c*e*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/(6*d^(5/2)) + (b*c*(c^2*d + 4*e)*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/(3*d^(5/2)) - (b*(c^4*d^2 + 4*c^2*d*e - 8*e^2)*ArcTanh[(c*Sqrt[d + e*x^2])/Sqrt[c^2*d - e]])/(3*d^3*Sqrt[c^2*d - e])}


{x^4*(a + b*ArcTan[c*x])/(d + e*x^2)^(5/2), x, 5, -((a*x^3)/(3*e*(d + e*x^2)^(3/2))) - (a*x)/(e^2*Sqrt[d + e*x^2]) + (a*ArcTanh[(Sqrt[e]*x)/Sqrt[d + e*x^2]])/e^(5/2) + b*Defer[Int][(x^4*ArcTan[c*x])/(d + e*x^2)^(5/2), x]}
{x^3*(a + b*ArcTan[c*x])/(d + e*x^2)^(5/2), x, 6, (b*c*x)/(3*(c^2*d - e)*e*Sqrt[d + e*x^2]) + (d*(a + b*ArcTan[c*x]))/(3*e^2*(d + e*x^2)^(3/2)) - (a + b*ArcTan[c*x])/(e^2*Sqrt[d + e*x^2]) + (b*c*(2*c^2*d - 3*e)*ArcTan[(Sqrt[c^2*d - e]*x)/Sqrt[d + e*x^2]])/(3*(c^2*d - e)^(3/2)*e^2)}
{x^2*(a + b*ArcTan[c*x])/(d + e*x^2)^(5/2), x, 5, (b*c)/(3*(c^2*d - e)*e*Sqrt[d + e*x^2]) + (x^3*(a + b*ArcTan[c*x]))/(3*d*(d + e*x^2)^(3/2)) - (b*ArcTanh[(c*Sqrt[d + e*x^2])/Sqrt[c^2*d - e]])/(3*d*(c^2*d - e)^(3/2))}
{x^1*(a + b*ArcTan[c*x])/(d + e*x^2)^(5/2), x, 4, -((b*c*x)/(3*d*(c^2*d - e)*Sqrt[d + e*x^2])) - (a + b*ArcTan[c*x])/(3*e*(d + e*x^2)^(3/2)) + (b*c^3*ArcTan[(Sqrt[c^2*d - e]*x)/Sqrt[d + e*x^2]])/(3*(c^2*d - e)^(3/2)*e)}
{x^0*(a + b*ArcTan[c*x])/(d + e*x^2)^(5/2), x, 9, -((b*c)/(3*d*(c^2*d - e)*Sqrt[d + e*x^2])) + (x*(a + b*ArcTan[c*x]))/(3*d*(d + e*x^2)^(3/2)) + (2*x*(a + b*ArcTan[c*x]))/(3*d^2*Sqrt[d + e*x^2]) + (b*c^2*ArcTanh[(c*Sqrt[d + e*x^2])/Sqrt[c^2*d - e]])/(3*d*(c^2*d - e)^(3/2)) + (2*b*ArcTanh[(c*Sqrt[d + e*x^2])/Sqrt[c^2*d - e]])/(3*d^2*Sqrt[c^2*d - e])}
{(a + b*ArcTan[c*x])/(x^1*(d + e*x^2)^(5/2)), x, 6, a/(3*d*(d + e*x^2)^(3/2)) + a/(d^2*Sqrt[d + e*x^2]) - (a*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/d^(5/2) + b*Defer[Int][ArcTan[c*x]/(x*(d + e*x^2)^(5/2)), x]}
{(a + b*ArcTan[c*x])/(x^2*(d + e*x^2)^(5/2)), x, 13, (b*c)/(d^2*Sqrt[d + e*x^2]) - (8*b*e)/(3*c*d^3*Sqrt[d + e*x^2]) - (b*(3*c^4*d^2 - 12*c^2*d*e + 8*e^2))/(3*c*d^3*(c^2*d - e)*Sqrt[d + e*x^2]) - (a + b*ArcTan[c*x])/(d*x*(d + e*x^2)^(3/2)) - (4*e*x*(a + b*ArcTan[c*x]))/(3*d^2*(d + e*x^2)^(3/2)) - (8*e*x*(a + b*ArcTan[c*x]))/(3*d^3*Sqrt[d + e*x^2]) - (b*c*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/d^(5/2) + (b*(3*c^4*d^2 - 12*c^2*d*e + 8*e^2)*ArcTanh[(c*Sqrt[d + e*x^2])/Sqrt[c^2*d - e]])/(3*d^3*(c^2*d - e)^(3/2))}
{(a + b*ArcTan[c*x])/(x^3*(d + e*x^2)^(5/2)), x, 7, a/(3*d*x^2*(d + e*x^2)^(3/2)) + (5*a)/(3*d^2*x^2*Sqrt[d + e*x^2]) - (5*a*Sqrt[d + e*x^2])/(2*d^3*x^2) + (5*a*e*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/(2*d^(7/2)) + b*Defer[Int][ArcTan[c*x]/(x^3*(d + e*x^2)^(5/2)), x]}
{(a + b*ArcTan[c*x])/(x^4*(d + e*x^2)^(5/2)), x, 18, (16*b*e^2)/(3*c*d^4*Sqrt[d + e*x^2]) - (b*c*(c^2*d + 6*e))/(3*d^3*Sqrt[d + e*x^2]) + (b*(c^2*d - 2*e)*(c^4*d^2 + 8*c^2*d*e - 8*e^2))/(3*c*d^4*(c^2*d - e)*Sqrt[d + e*x^2]) + (b*c)/(3*d^2*x^2*Sqrt[d + e*x^2]) - (b*c*Sqrt[d + e*x^2])/(2*d^3*x^2) - (a + b*ArcTan[c*x])/(3*d*x^3*(d + e*x^2)^(3/2)) + (2*e*(a + b*ArcTan[c*x]))/(d^2*x*(d + e*x^2)^(3/2)) + (8*e^2*x*(a + b*ArcTan[c*x]))/(3*d^3*(d + e*x^2)^(3/2)) + (16*e^2*x*(a + b*ArcTan[c*x]))/(3*d^4*Sqrt[d + e*x^2]) + (b*c*e*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/(2*d^(7/2)) + (b*c*(c^2*d + 6*e)*ArcTanh[Sqrt[d + e*x^2]/Sqrt[d]])/(3*d^(7/2)) - (b*(c^2*d - 2*e)*(c^4*d^2 + 8*c^2*d*e - 8*e^2)*ArcTanh[(c*Sqrt[d + e*x^2])/Sqrt[c^2*d - e]])/(3*d^4*(c^2*d - e)^(3/2))}


{ArcTan[a*x]/(c + d*x^2)^(7/2), x, 14, -(a/(15*c*(a^2*c - d)*(c + d*x^2)^(3/2))) - a^3/(5*c*(a^2*c - d)^2*Sqrt[c + d*x^2]) - (4*a)/(15*c^2*(a^2*c - d)*Sqrt[c + d*x^2]) + (x*ArcTan[a*x])/(5*c*(c + d*x^2)^(5/2)) + (4*x*ArcTan[a*x])/(15*c^2*(c + d*x^2)^(3/2)) + (8*x*ArcTan[a*x])/(15*c^3*Sqrt[c + d*x^2]) + (a^4*ArcTanh[(a*Sqrt[c + d*x^2])/Sqrt[a^2*c - d]])/(5*c*(a^2*c - d)^(5/2)) + (4*a^2*ArcTanh[(a*Sqrt[c + d*x^2])/Sqrt[a^2*c - d]])/(15*c^2*(a^2*c - d)^(3/2)) + (8*ArcTanh[(a*Sqrt[c + d*x^2])/Sqrt[a^2*c - d]])/(15*c^3*Sqrt[a^2*c - d])}


{ArcTan[a*x]/(c + d*x^2)^(9/2), x, 20, -(a/(35*c*(a^2*c - d)*(c + d*x^2)^(5/2))) - a^3/(21*c*(a^2*c - d)^2*(c + d*x^2)^(3/2)) - (2*a)/(35*c^2*(a^2*c - d)*(c + d*x^2)^(3/2)) - a^5/(7*c*(a^2*c - d)^3*Sqrt[c + d*x^2]) - (6*a^3)/(35*c^2*(a^2*c - d)^2*Sqrt[c + d*x^2]) - (8*a)/(35*c^3*(a^2*c - d)*Sqrt[c + d*x^2]) + (x*ArcTan[a*x])/(7*c*(c + d*x^2)^(7/2)) + (6*x*ArcTan[a*x])/(35*c^2*(c + d*x^2)^(5/2)) + (8*x*ArcTan[a*x])/(35*c^3*(c + d*x^2)^(3/2)) + (16*x*ArcTan[a*x])/(35*c^4*Sqrt[c + d*x^2]) + (a^6*ArcTanh[(a*Sqrt[c + d*x^2])/Sqrt[a^2*c - d]])/(7*c*(a^2*c - d)^(7/2)) + (6*a^4*ArcTanh[(a*Sqrt[c + d*x^2])/Sqrt[a^2*c - d]])/(35*c^2*(a^2*c - d)^(5/2)) + (8*a^2*ArcTanh[(a*Sqrt[c + d*x^2])/Sqrt[a^2*c - d]])/(35*c^3*(a^2*c - d)^(3/2)) + (16*ArcTanh[(a*Sqrt[c + d*x^2])/Sqrt[a^2*c - d]])/(35*c^4*Sqrt[a^2*c - d])}


(* ::Subsection::Closed:: *)
(*Integrands of the form x^m (d+e x^2)^p (a+b ArcTan[c x]) with m symbolic*)


{x^m*(a + b*ArcTan[c*x])*(d + e*x^2)^3, x, 4, If[$VersionNumber>=8, -((b*e*(e^2*(15 + 8*m + m^2) - 3*c^2*d*e*(21 + 10*m + m^2) + 3*c^4*d^2*(35 + 12*m + m^2))*x^(2 + m))/(c^5*(2 + m)*(3 + m)*(5 + m)*(7 + m))) + (b*e^2*(e*(5 + m) - 3*c^2*d*(7 + m))*x^(4 + m))/(c^3*(4 + m)*(5 + m)*(7 + m)) - (b*e^3*x^(6 + m))/(c*(6 + m)*(7 + m)) + (d^3*x^(1 + m)*(a + b*ArcTan[c*x]))/(1 + m) + (3*d^2*e*x^(3 + m)*(a + b*ArcTan[c*x]))/(3 + m) + (3*d*e^2*x^(5 + m)*(a + b*ArcTan[c*x]))/(5 + m) + (e^3*x^(7 + m)*(a + b*ArcTan[c*x]))/(7 + m) + (b*(e^3*(15 + 23*m + 9*m^2 + m^3) - 3*c^2*d*e^2*(21 + 31*m + 11*m^2 + m^3) + 3*c^4*d^2*e*(35 + 47*m + 13*m^2 + m^3) - c^6*d^3*(105 + 71*m + 15*m^2 + m^3))*x^(2 + m)*Hypergeometric2F1[1, (2 + m)/2, (4 + m)/2, (-c^2)*x^2])/(c^5*(1 + m)*(2 + m)*(3 + m)*(5 + m)*(7 + m)), -((b*e*(e^2*(15 + 8*m + m^2) - 3*c^2*d*e*(21 + 10*m + m^2) + 3*c^4*d^2*(35 + 12*m + m^2))*x^(2 + m))/(c^5*(2 + m)*(7 + m)*(15 + 8*m + m^2))) + (b*e^2*(e*(5 + m) - 3*c^2*d*(7 + m))*x^(4 + m))/(c^3*(4 + m)*(5 + m)*(7 + m)) - (b*e^3*x^(6 + m))/(c*(6 + m)*(7 + m)) + (d^3*x^(1 + m)*(a + b*ArcTan[c*x]))/(1 + m) + (3*d^2*e*x^(3 + m)*(a + b*ArcTan[c*x]))/(3 + m) + (3*d*e^2*x^(5 + m)*(a + b*ArcTan[c*x]))/(5 + m) + (e^3*x^(7 + m)*(a + b*ArcTan[c*x]))/(7 + m) + (b*(e^3*(15 + 23*m + 9*m^2 + m^3) - 3*c^2*d*e^2*(21 + 31*m + 11*m^2 + m^3) + 3*c^4*d^2*e*(35 + 47*m + 13*m^2 + m^3) - c^6*d^3*(105 + 71*m + 15*m^2 + m^3))*x^(2 + m)*Hypergeometric2F1[1, (2 + m)/2, (4 + m)/2, (-c^2)*x^2])/(c^5*(35 + 12*m + m^2)*(6 + 11*m + 6*m^2 + m^3))]}
{x^m*(a + b*ArcTan[c*x])*(d + e*x^2)^2, x, 4, If[$VersionNumber>=8, (b*e*(e*(3 + m) - 2*c^2*d*(5 + m))*x^(2 + m))/(c^3*(2 + m)*(3 + m)*(5 + m)) - (b*e^2*x^(4 + m))/(c*(4 + m)*(5 + m)) + (d^2*x^(1 + m)*(a + b*ArcTan[c*x]))/(1 + m) + (2*d*e*x^(3 + m)*(a + b*ArcTan[c*x]))/(3 + m) + (e^2*x^(5 + m)*(a + b*ArcTan[c*x]))/(5 + m) - (b*(e^2*(3 + 4*m + m^2) - 2*c^2*d*e*(5 + 6*m + m^2) + c^4*d^2*(15 + 8*m + m^2))*x^(2 + m)*Hypergeometric2F1[1, (2 + m)/2, (4 + m)/2, (-c^2)*x^2])/(c^3*(1 + m)*(2 + m)*(3 + m)*(5 + m)), (b*e*(e*(3 + m) - 2*c^2*d*(5 + m))*x^(2 + m))/(c^3*(5 + m)*(6 + 5*m + m^2)) - (b*e^2*x^(4 + m))/(c*(4 + m)*(5 + m)) + (d^2*x^(1 + m)*(a + b*ArcTan[c*x]))/(1 + m) + (2*d*e*x^(3 + m)*(a + b*ArcTan[c*x]))/(3 + m) + (e^2*x^(5 + m)*(a + b*ArcTan[c*x]))/(5 + m) - (b*(e^2*(3 + 4*m + m^2) - 2*c^2*d*e*(5 + 6*m + m^2) + c^4*d^2*(15 + 8*m + m^2))*x^(2 + m)*Hypergeometric2F1[1, (2 + m)/2, (4 + m)/2, (-c^2)*x^2])/(c^3*(2 + 3*m + m^2)*(15 + 8*m + m^2))]}
{x^m*(a + b*ArcTan[c*x])*(d + e*x^2)^1, x, 3, -((b*e*x^(2 + m))/(c*(6 + 5*m + m^2))) + (d*x^(1 + m)*(a + b*ArcTan[c*x]))/(1 + m) + (e*x^(3 + m)*(a + b*ArcTan[c*x]))/(3 + m) - (b*((c^2*d)/(1 + m) - e/(3 + m))*x^(2 + m)*Hypergeometric2F1[1, (2 + m)/2, (4 + m)/2, (-c^2)*x^2])/(c*(2 + m))}
{x^m*(a + b*ArcTan[c*x])/(d + e*x^2)^1, x, 2, (a*x^(1 + m)*Hypergeometric2F1[1, (1 + m)/2, (3 + m)/2, -((e*x^2)/d)])/(d*(1 + m)) + b*Defer[Int][(x^m*ArcTan[c*x])/(d + e*x^2), x]}
{x^m*(a + b*ArcTan[c*x])/(d + e*x^2)^2, x, 2, (a*x^(1 + m)*Hypergeometric2F1[2, (1 + m)/2, (3 + m)/2, -((e*x^2)/d)])/(d^2*(1 + m)) + b*Defer[Int][(x^m*ArcTan[c*x])/(d + e*x^2)^2, x]}


{x^m*(a + b*ArcTan[c*x])*(d + e*x^2)^(5/2), x, 3, (a*x^(1 + m)*(d + e*x^2)^(7/2)*Hypergeometric2F1[1, (8 + m)/2, (3 + m)/2, -((e*x^2)/d)])/(d*(1 + m)) + b*Defer[Int][x^m*(d + e*x^2)^(5/2)*ArcTan[c*x], x], (a*d^2*x^(1 + m)*Sqrt[d + e*x^2]*Hypergeometric2F1[-(5/2), (1 + m)/2, (3 + m)/2, -((e*x^2)/d)])/((1 + m)*Sqrt[1 + (e*x^2)/d]) + b*Defer[Int][x^m*(d + e*x^2)^(5/2)*ArcTan[c*x], x]}
{x^m*(a + b*ArcTan[c*x])*(d + e*x^2)^(3/2), x, 3, (a*x^(1 + m)*(d + e*x^2)^(5/2)*Hypergeometric2F1[1, (6 + m)/2, (3 + m)/2, -((e*x^2)/d)])/(d*(1 + m)) + b*Defer[Int][x^m*(d + e*x^2)^(3/2)*ArcTan[c*x], x], (a*d*x^(1 + m)*Sqrt[d + e*x^2]*Hypergeometric2F1[-(3/2), (1 + m)/2, (3 + m)/2, -((e*x^2)/d)])/((1 + m)*Sqrt[1 + (e*x^2)/d]) + b*Defer[Int][x^m*(d + e*x^2)^(3/2)*ArcTan[c*x], x]}
{x^m*(a + b*ArcTan[c*x])*(d + e*x^2)^(1/2), x, 3, (a*x^(1 + m)*(d + e*x^2)^(3/2)*Hypergeometric2F1[1, (4 + m)/2, (3 + m)/2, -((e*x^2)/d)])/(d*(1 + m)) + b*Defer[Int][x^m*Sqrt[d + e*x^2]*ArcTan[c*x], x], (a*x^(1 + m)*Sqrt[d + e*x^2]*Hypergeometric2F1[-(1/2), (1 + m)/2, (3 + m)/2, -((e*x^2)/d)])/((1 + m)*Sqrt[1 + (e*x^2)/d]) + b*Defer[Int][x^m*Sqrt[d + e*x^2]*ArcTan[c*x], x]}
{x^m*(a + b*ArcTan[c*x])/(d + e*x^2)^(1/2), x, 3, (a*x^(1 + m)*Sqrt[d + e*x^2]*Hypergeometric2F1[1, (2 + m)/2, (3 + m)/2, -((e*x^2)/d)])/(d*(1 + m)) + b*Defer[Int][(x^m*ArcTan[c*x])/Sqrt[d + e*x^2], x], (a*x^(1 + m)*Sqrt[1 + (e*x^2)/d]*Hypergeometric2F1[1/2, (1 + m)/2, (3 + m)/2, -((e*x^2)/d)])/((1 + m)*Sqrt[d + e*x^2]) + b*Defer[Int][(x^m*ArcTan[c*x])/Sqrt[d + e*x^2], x]}
{x^m*(a + b*ArcTan[c*x])/(d + e*x^2)^(3/2), x, 3, (a*x^(1 + m)*Hypergeometric2F1[1, m/2, (3 + m)/2, -((e*x^2)/d)])/(d*(1 + m)*Sqrt[d + e*x^2]) + b*Defer[Int][(x^m*ArcTan[c*x])/(d + e*x^2)^(3/2), x], (a*x^(1 + m)*Sqrt[1 + (e*x^2)/d]*Hypergeometric2F1[3/2, (1 + m)/2, (3 + m)/2, -((e*x^2)/d)])/(d*(1 + m)*Sqrt[d + e*x^2]) + b*Defer[Int][(x^m*ArcTan[c*x])/(d + e*x^2)^(3/2), x]}
{x^m*(a + b*ArcTan[c*x])/(d + e*x^2)^(5/2), x, 3, (a*x^(1 + m)*Hypergeometric2F1[1, (1/2)*(-2 + m), (3 + m)/2, -((e*x^2)/d)])/(d*(1 + m)*(d + e*x^2)^(3/2)) + b*Defer[Int][(x^m*ArcTan[c*x])/(d + e*x^2)^(5/2), x], (a*x^(1 + m)*Sqrt[1 + (e*x^2)/d]*Hypergeometric2F1[5/2, (1 + m)/2, (3 + m)/2, -((e*x^2)/d)])/(d^2*(1 + m)*Sqrt[d + e*x^2]) + b*Defer[Int][(x^m*ArcTan[c*x])/(d + e*x^2)^(5/2), x]}


(* ::Subsection::Closed:: *)
(*Integrands of the form x^m (d+e x^2)^p (a+b ArcTan[c x]) with p symbolic*)


{x^m*(a + b*ArcTan[c*x])*(d + e*x^2)^p, x, 3, (a*x^(1 + m)*(d + e*x^2)^(1 + p)*Hypergeometric2F1[1, (1/2)*(3 + m + 2*p), (3 + m)/2, -((e*x^2)/d)])/(d*(1 + m)) + b*Defer[Int][x^m*(d + e*x^2)^p*ArcTan[c*x], x], (a*x^(1 + m)*(d + e*x^2)^p*Hypergeometric2F1[(1 + m)/2, -p, (3 + m)/2, -((e*x^2)/d)])/((1 + (e*x^2)/d)^p*(1 + m)) + b*Defer[Int][x^m*(d + e*x^2)^p*ArcTan[c*x], x]}


{(a + b*ArcTan[c*x])*(d + e*x^2)^p/x^(2*p + 2), x, 3, -((a*x^(-1 - 2*p)*(d + e*x^2)^(1 + p)*Hypergeometric2F1[1/2, 1, (1/2)*(1 - 2*p), -((e*x^2)/d)])/(d*(1 + 2*p))) + b*Defer[Int][x^(-2 - 2*p)*(d + e*x^2)^p*ArcTan[c*x], x], -((a*x^(-1 - 2*p)*(d + e*x^2)^p*Hypergeometric2F1[(1/2)*(-1 - 2*p), -p, (1/2)*(1 - 2*p), -((e*x^2)/d)])/((1 + (e*x^2)/d)^p*(1 + 2*p))) + b*Defer[Int][x^(-2 - 2*p)*(d + e*x^2)^p*ArcTan[c*x], x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^p/x^(2*p + 3), x, 4, -((b*c*x^(-1 - 2*p)*(d + e*x^2)^p*AppellF1[(1/2)*(-1 - 2*p), 1, -1 - p, (1/2)*(1 - 2*p), (-c^2)*x^2, -((e*x^2)/d)])/((1 + (e*x^2)/d)^p*(2*(1 + 3*p + 2*p^2)))) - ((d + e*x^2)^(1 + p)*(a + b*ArcTan[c*x]))/(x^(2*(1 + p))*(2*d*(1 + p)))}
{(a + b*ArcTan[c*x])*(d + e*x^2)^p/x^(2*p + 4), x, 3, -((a*x^(-3 - 2*p)*(d + e*x^2)^(1 + p)*Hypergeometric2F1[-(1/2), 1, (1/2)*(-1 - 2*p), -((e*x^2)/d)])/(d*(3 + 2*p))) + b*Defer[Int][x^(-4 - 2*p)*(d + e*x^2)^p*ArcTan[c*x], x], -((a*x^(-3 - 2*p)*(d + e*x^2)^p*Hypergeometric2F1[(1/2)*(-3 - 2*p), -p, (1/2)*(-1 - 2*p), -((e*x^2)/d)])/((1 + (e*x^2)/d)^p*(3 + 2*p))) + b*Defer[Int][x^(-4 - 2*p)*(d + e*x^2)^p*ArcTan[c*x], x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^p/x^(2*p + 5), x, 8, If[$VersionNumber>=8, -((b*(e + c^2*d*(1 + p))*x^(-3 - 2*p)*(d + e*x^2)^p*AppellF1[(1/2)*(-3 - 2*p), 1, -1 - p, (1/2)*(-1 - 2*p), (-c^2)*x^2, -((e*x^2)/d)])/((1 + (e*x^2)/d)^p*(2*c*d*(1 + p)*(2 + p)*(3 + 2*p)))) + (e*(d + e*x^2)^(1 + p)*(a + b*ArcTan[c*x]))/(x^(2*(1 + p))*(2*d^2*(1 + p)*(2 + p))) - ((d + e*x^2)^(1 + p)*(a + b*ArcTan[c*x]))/(x^(2*(2 + p))*(2*d*(2 + p))) + (b*e*x^(-3 - 2*p)*(d + e*x^2)^p*Hypergeometric2F1[(1/2)*(-3 - 2*p), -1 - p, (1/2)*(-1 - 2*p), -((e*x^2)/d)])/((1 + (e*x^2)/d)^p*(2*c*d*(6 + 13*p + 9*p^2 + 2*p^3))), -((b*(e + c^2*d*(1 + p))*x^(-3 - 2*p)*(d + e*x^2)^p*AppellF1[(1/2)*(-3 - 2*p), 1, -1 - p, (1/2)*(-1 - 2*p), (-c^2)*x^2, -((e*x^2)/d)])/((1 + (e*x^2)/d)^p*(2*c*d*(3 + 2*p)*(2 + 3*p + p^2)))) + (e*(d + e*x^2)^(1 + p)*(a + b*ArcTan[c*x]))/(x^(2*(1 + p))*(2*d^2*(1 + p)*(2 + p))) - ((d + e*x^2)^(1 + p)*(a + b*ArcTan[c*x]))/(x^(2*(2 + p))*(2*d*(2 + p))) + (b*e*x^(-3 - 2*p)*(d + e*x^2)^p*Hypergeometric2F1[(1/2)*(-3 - 2*p), -1 - p, (1/2)*(-1 - 2*p), -((e*x^2)/d)])/((1 + (e*x^2)/d)^p*(2*c*d*(6 + 13*p + 9*p^2 + 2*p^3)))]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^p/x^(2*p + 6), x, 3, -((a*x^(-5 - 2*p)*(d + e*x^2)^(1 + p)*Hypergeometric2F1[-(3/2), 1, (1/2)*(-3 - 2*p), -((e*x^2)/d)])/(d*(5 + 2*p))) + b*Defer[Int][x^(-6 - 2*p)*(d + e*x^2)^p*ArcTan[c*x], x], -((a*x^(-5 - 2*p)*(d + e*x^2)^p*Hypergeometric2F1[(1/2)*(-5 - 2*p), -p, (1/2)*(-3 - 2*p), -((e*x^2)/d)])/((1 + (e*x^2)/d)^p*(5 + 2*p))) + b*Defer[Int][x^(-6 - 2*p)*(d + e*x^2)^p*ArcTan[c*x], x]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^p/x^(2*p + 7), x, 10, If[$VersionNumber>=8, -((b*(2*e^2 + 2*c^2*d*e*(1 + p) + c^4*d^2*(2 + 3*p + p^2))*x^(-5 - 2*p)*(d + e*x^2)^p*AppellF1[(1/2)*(-5 - 2*p), 1, -1 - p, (1/2)*(-3 - 2*p), (-c^2)*x^2, -((e*x^2)/d)])/((1 + (e*x^2)/d)^p*(2*c^3*d^2*(1 + p)*(2 + p)*(3 + p)*(5 + 2*p)))) - (e^2*(d + e*x^2)^(1 + p)*(a + b*ArcTan[c*x]))/(x^(2*(1 + p))*(d^3*(1 + p)*(2 + p)*(3 + p))) + (e*(d + e*x^2)^(1 + p)*(a + b*ArcTan[c*x]))/(x^(2*(2 + p))*(d^2*(2 + p)*(3 + p))) - ((d + e*x^2)^(1 + p)*(a + b*ArcTan[c*x]))/(x^(2*(3 + p))*(2*d*(3 + p))) + (b*e*(e + c^2*d*(1 + p))*x^(-5 - 2*p)*(d + e*x^2)^p*Hypergeometric2F1[(1/2)*(-5 - 2*p), -1 - p, (1/2)*(-3 - 2*p), -((e*x^2)/d)])/((1 + (e*x^2)/d)^p*(c^3*d^2*(1 + p)*(2 + p)*(3 + p)*(5 + 2*p))) - (b*e^2*x^(-3 - 2*p)*(d + e*x^2)^p*Hypergeometric2F1[(1/2)*(-3 - 2*p), -1 - p, (1/2)*(-1 - 2*p), -((e*x^2)/d)])/((1 + (e*x^2)/d)^p*(c*d^2*(1 + p)*(2 + p)*(3 + p)*(3 + 2*p))), -((b*(2*e^2 + 2*c^2*d*e*(1 + p) + c^4*d^2*(2 + 3*p + p^2))*x^(-5 - 2*p)*(d + e*x^2)^p*AppellF1[(1/2)*(-5 - 2*p), 1, -1 - p, (1/2)*(-3 - 2*p), (-c^2)*x^2, -((e*x^2)/d)])/((1 + (e*x^2)/d)^p*(2*c^3*d^2*(5 + 2*p)*(6 + 11*p + 6*p^2 + p^3)))) - (e^2*(d + e*x^2)^(1 + p)*(a + b*ArcTan[c*x]))/(x^(2*(1 + p))*(d^3*(2 + p)*(3 + 4*p + p^2))) + (e*(d + e*x^2)^(1 + p)*(a + b*ArcTan[c*x]))/(x^(2*(2 + p))*(d^2*(2 + p)*(3 + p))) - ((d + e*x^2)^(1 + p)*(a + b*ArcTan[c*x]))/(x^(2*(3 + p))*(2*d*(3 + p))) + (b*e*(e + c^2*d*(1 + p))*x^(-5 - 2*p)*(d + e*x^2)^p*Hypergeometric2F1[(1/2)*(-5 - 2*p), -1 - p, (1/2)*(-3 - 2*p), -((e*x^2)/d)])/((1 + (e*x^2)/d)^p*(c^3*d^2*(5 + 2*p)*(6 + 11*p + 6*p^2 + p^3))) - (b*e^2*x^(-3 - 2*p)*(d + e*x^2)^p*Hypergeometric2F1[(1/2)*(-3 - 2*p), -1 - p, (1/2)*(-1 - 2*p), -((e*x^2)/d)])/((1 + (e*x^2)/d)^p*(c*d^2*(3 + 2*p)*(6 + 11*p + 6*p^2 + p^3)))]}
{(a + b*ArcTan[c*x])*(d + e*x^2)^p/x^(2*p + 8), x, 3, -((a*x^(-7 - 2*p)*(d + e*x^2)^(1 + p)*Hypergeometric2F1[-(5/2), 1, (1/2)*(-5 - 2*p), -((e*x^2)/d)])/(d*(7 + 2*p))) + b*Defer[Int][x^(-8 - 2*p)*(d + e*x^2)^p*ArcTan[c*x], x], -((a*x^(-7 - 2*p)*(d + e*x^2)^p*Hypergeometric2F1[(1/2)*(-7 - 2*p), -p, (1/2)*(-5 - 2*p), -((e*x^2)/d)])/((1 + (e*x^2)/d)^p*(7 + 2*p))) + b*Defer[Int][x^(-8 - 2*p)*(d + e*x^2)^p*ArcTan[c*x], x]}


(* ::Section:: *)
(*Integrands of the form (f x)^m (d+e x^2)^p (a+b ArcTan[c x])^2*)
