(* ::Package:: *)

(* ::Title:: *)
(*Integrands of the form x^m (a+b x)^n (c+d x)^p (e+f x)^q*)


(* ::Section::Closed:: *)
(*Integrands of the form x^m (a+b x)^n (c+d x)^p (e+f x)^q*)


{x^3*(1 + a*x)/(Sqrt[a*x]*Sqrt[1 - a*x]), x, 8, -((75*Sqrt[a*x]*Sqrt[1 - a*x])/(64*a^4)) - (25*(a*x)^(3/2)*Sqrt[1 - a*x])/(32*a^4) - (5*(a*x)^(5/2)*Sqrt[1 - a*x])/(8*a^4) - ((a*x)^(7/2)*Sqrt[1 - a*x])/(4*a^4) - (75*ArcSin[1 - 2*a*x])/(128*a^4)}
{x^2*(1 + a*x)/(Sqrt[a*x]*Sqrt[1 - a*x]), x, 7, -((11*Sqrt[a*x]*Sqrt[1 - a*x])/(8*a^3)) - (11*(a*x)^(3/2)*Sqrt[1 - a*x])/(12*a^3) - ((a*x)^(5/2)*Sqrt[1 - a*x])/(3*a^3) - (11*ArcSin[1 - 2*a*x])/(16*a^3)}
{x^1*(1 + a*x)/(Sqrt[a*x]*Sqrt[1 - a*x]), x, 6, -((7*Sqrt[a*x]*Sqrt[1 - a*x])/(4*a^2)) - ((a*x)^(3/2)*Sqrt[1 - a*x])/(2*a^2) - (7*ArcSin[1 - 2*a*x])/(8*a^2)}
{x^0*(1 + a*x)/(Sqrt[a*x]*Sqrt[1 - a*x]), x, 4, -((Sqrt[a*x]*Sqrt[1 - a*x])/a) - (3*ArcSin[1 - 2*a*x])/(2*a)}
{(1 + a*x)/(x^1*Sqrt[a*x]*Sqrt[1 - a*x]), x, 5, -((2*Sqrt[1 - a*x])/Sqrt[a*x]) - ArcSin[1 - 2*a*x]}
{(1 + a*x)/(x^2*Sqrt[a*x]*Sqrt[1 - a*x]), x, 3, -((2*a*Sqrt[1 - a*x])/(3*(a*x)^(3/2))) - (10*a*Sqrt[1 - a*x])/(3*Sqrt[a*x])}
{(1 + a*x)/(x^3*Sqrt[a*x]*Sqrt[1 - a*x]), x, 4, -((2*a^2*Sqrt[1 - a*x])/(5*(a*x)^(5/2))) - (6*a^2*Sqrt[1 - a*x])/(5*(a*x)^(3/2)) - (12*a^2*Sqrt[1 - a*x])/(5*Sqrt[a*x])}
{(1 + a*x)/(x^4*Sqrt[a*x]*Sqrt[1 - a*x]), x, 5, -((2*a^3*Sqrt[1 - a*x])/(7*(a*x)^(7/2))) - (26*a^3*Sqrt[1 - a*x])/(35*(a*x)^(5/2)) - (104*a^3*Sqrt[1 - a*x])/(105*(a*x)^(3/2)) - (208*a^3*Sqrt[1 - a*x])/(105*Sqrt[a*x])}
{(1 + a*x)/(x^5*Sqrt[a*x]*Sqrt[1 - a*x]), x, 6, -((2*a^4*Sqrt[1 - a*x])/(9*(a*x)^(9/2))) - (34*a^4*Sqrt[1 - a*x])/(63*(a*x)^(7/2)) - (68*a^4*Sqrt[1 - a*x])/(105*(a*x)^(5/2)) - (272*a^4*Sqrt[1 - a*x])/(315*(a*x)^(3/2)) - (544*a^4*Sqrt[1 - a*x])/(315*Sqrt[a*x])}


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x)^n (c+d x)^(p/2) (e+f x) / x*)


{(a + b*x)^3*Sqrt[c + d*x]*(e + f*x)/x, x, 6, 2*a^3*e*Sqrt[c + d*x] + (2*(3*b*d*e - 2*b*c*f + 2*a*d*f)*(a + b*x)^2*(c + d*x)^(3/2))/(21*d^2) + (2*f*(a + b*x)^3*(c + d*x)^(3/2))/(9*d) + (2*(c + d*x)^(3/2)*(2*(20*a^3*d^3*f + 3*a^2*b*d^2*(45*d*e - 16*c*f) - 9*a*b^2*c*d*(7*d*e - 4*c*f) + 4*b^3*c^2*(3*d*e - 2*c*f)) + 3*b*d*(21*a*b*d^2*e - 4*(b*c - a*d)*(3*b*d*e - 2*b*c*f + 2*a*d*f))*x))/(315*d^4) - 2*a^3*Sqrt[c]*e*ArcTanh[Sqrt[c + d*x]/Sqrt[c]]}
{(a + b*x)^2*Sqrt[c + d*x]*(e + f*x)/x, x, 5, 2*a^2*e*Sqrt[c + d*x] + (2*f*(a + b*x)^2*(c + d*x)^(3/2))/(7*d) + (2*(c + d*x)^(3/2)*(2*(10*a^2*d^2*f - b^2*c*(7*d*e - 4*c*f) + 7*a*b*d*(5*d*e - 2*c*f)) + 3*b*d*(7*b*d*e - 4*b*c*f + 4*a*d*f)*x))/(105*d^3) - 2*a^2*Sqrt[c]*e*ArcTanh[Sqrt[c + d*x]/Sqrt[c]]}
{(a + b*x)^1*Sqrt[c + d*x]*(e + f*x)/x, x, 4, 2*a*e*Sqrt[c + d*x] - (2*(c + d*x)^(3/2)*(2*b*c*f - 5*d*(b*e + a*f) - 3*b*d*f*x))/(15*d^2) - 2*a*Sqrt[c]*e*ArcTanh[Sqrt[c + d*x]/Sqrt[c]]}
{(a + b*x)^0*Sqrt[c + d*x]*(e + f*x)/x, x, 4, 2*e*Sqrt[c + d*x] + (2*f*(c + d*x)^(3/2))/(3*d) - 2*Sqrt[c]*e*ArcTanh[Sqrt[c + d*x]/Sqrt[c]]}
{1/(a + b*x)^1*Sqrt[c + d*x]*(e + f*x)/x, x, 6, (2*f*Sqrt[c + d*x])/b - (2*Sqrt[c]*e*ArcTanh[Sqrt[c + d*x]/Sqrt[c]])/a + (2*Sqrt[b*c - a*d]*(b*e - a*f)*ArcTanh[(Sqrt[b]*Sqrt[c + d*x])/Sqrt[b*c - a*d]])/(a*b^(3/2))}
{1/(a + b*x)^2*Sqrt[c + d*x]*(e + f*x)/x, x, 6, ((b*e - a*f)*Sqrt[c + d*x])/(a*b*(a + b*x)) - (2*Sqrt[c]*e*ArcTanh[Sqrt[c + d*x]/Sqrt[c]])/a^2 + ((2*b^2*c*e - a*d*(b*e + a*f))*ArcTanh[(Sqrt[b]*Sqrt[c + d*x])/Sqrt[b*c - a*d]])/(a^2*b^(3/2)*Sqrt[b*c - a*d])}
{1/(a + b*x)^3*Sqrt[c + d*x]*(e + f*x)/x, x, 7, ((b*e - a*f)*Sqrt[c + d*x])/(2*a*b*(a + b*x)^2) + ((4*b^2*c*e - 3*a*b*d*e - a^2*d*f)*Sqrt[c + d*x])/(4*a^2*b*(b*c - a*d)*(a + b*x)) - (2*Sqrt[c]*e*ArcTanh[Sqrt[c + d*x]/Sqrt[c]])/a^3 + ((8*b^3*c^2*e - 12*a*b^2*c*d*e + 3*a^2*b*d^2*e + a^3*d^2*f)*ArcTanh[(Sqrt[b]*Sqrt[c + d*x])/Sqrt[b*c - a*d]])/(4*a^3*b^(3/2)*(b*c - a*d)^(3/2))}


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x)^(n/2) (c+d x)^p (e+f x) / x*)


{Sqrt[a + b*x]*(c + d*x)^3*(e + f*x)/x, x, 6, 2*c^3*e*Sqrt[a + b*x] + (2*(3*b*d*e + 2*b*c*f - 2*a*d*f)*(a + b*x)^(3/2)*(c + d*x)^2)/(21*b^2) + (2*f*(a + b*x)^(3/2)*(c + d*x)^3)/(9*b) - (2*(a + b*x)^(3/2)*(2*(8*a^3*d^3*f - 12*a^2*b*d^2*(d*e + 3*c*f) - 5*b^3*c^2*(27*d*e + 4*c*f) + 3*a*b^2*c*d*(21*d*e + 16*c*f)) - 3*b*d*(21*b^2*c*d*e + 4*(b*c - a*d)*(3*b*d*e + 2*b*c*f - 2*a*d*f))*x))/(315*b^4) - 2*Sqrt[a]*c^3*e*ArcTanh[Sqrt[a + b*x]/Sqrt[a]]}
{Sqrt[a + b*x]*(c + d*x)^2*(e + f*x)/x, x, 5, 2*c^2*e*Sqrt[a + b*x] + (2*f*(a + b*x)^(3/2)*(c + d*x)^2)/(7*b) + (2*(a + b*x)^(3/2)*(2*(4*a^2*d^2*f - 7*a*b*d*(d*e + 2*c*f) + 5*b^2*c*(7*d*e + 2*c*f)) + 3*b*d*(7*b*d*e + 4*b*c*f - 4*a*d*f)*x))/(105*b^3) - 2*Sqrt[a]*c^2*e*ArcTanh[Sqrt[a + b*x]/Sqrt[a]]}
{Sqrt[a + b*x]*(c + d*x)^1*(e + f*x)/x, x, 4, 2*c*e*Sqrt[a + b*x] - (2*(a + b*x)^(3/2)*(2*a*d*f - 5*b*(d*e + c*f) - 3*b*d*f*x))/(15*b^2) - 2*Sqrt[a]*c*e*ArcTanh[Sqrt[a + b*x]/Sqrt[a]]}
{Sqrt[a + b*x]*(c + d*x)^0*(e + f*x)/x, x, 4, 2*e*Sqrt[a + b*x] + (2*f*(a + b*x)^(3/2))/(3*b) - 2*Sqrt[a]*e*ArcTanh[Sqrt[a + b*x]/Sqrt[a]]}
{Sqrt[a + b*x]/(c + d*x)^1*(e + f*x)/x, x, 6, (2*f*Sqrt[a + b*x])/d + (2*Sqrt[b*c - a*d]*(d*e - c*f)*ArcTan[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[b*c - a*d]])/(c*d^(3/2)) - (2*Sqrt[a]*e*ArcTanh[Sqrt[a + b*x]/Sqrt[a]])/c}
{Sqrt[a + b*x]/(c + d*x)^2*(e + f*x)/x, x, 6, ((d*e - c*f)*Sqrt[a + b*x])/(c*d*(c + d*x)) - ((2*a*d^2*e - b*c*(d*e + c*f))*ArcTan[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[b*c - a*d]])/(c^2*d^(3/2)*Sqrt[b*c - a*d]) - (2*Sqrt[a]*e*ArcTanh[Sqrt[a + b*x]/Sqrt[a]])/c^2}
{Sqrt[a + b*x]/(c + d*x)^3*(e + f*x)/x, x, 7, ((d*e - c*f)*Sqrt[a + b*x])/(2*c*d*(c + d*x)^2) - ((4*a*d^2*e - b*c*(3*d*e + c*f))*Sqrt[a + b*x])/(4*c^2*d*(b*c - a*d)*(c + d*x)) - ((12*a*b*c*d^2*e - 8*a^2*d^3*e - b^2*c^2*(3*d*e + c*f))*ArcTan[(Sqrt[d]*Sqrt[a + b*x])/Sqrt[b*c - a*d]])/(4*c^3*d^(3/2)*(b*c - a*d)^(3/2)) - (2*Sqrt[a]*e*ArcTanh[Sqrt[a + b*x]/Sqrt[a]])/c^3}


(* ::Section::Closed:: *)
(*Integrands of the form x^m (a+b x)^n (c+d x)^p (e+f x)^q with n symbolic*)


{x^m*(e + f*x)^n/((a + b*x)*(c + d*x)), x, 6, (b*x^(1 + m)*(e + f*x)^n*AppellF1[1 + m, -n, 1, 2 + m, -((f*x)/e), -((b*x)/a)])/((1 + (f*x)/e)^n*(a*(b*c - a*d)*(1 + m))) - (d*x^(1 + m)*(e + f*x)^n*AppellF1[1 + m, -n, 1, 2 + m, -((f*x)/e), -((d*x)/c)])/((1 + (f*x)/e)^n*(c*(b*c - a*d)*(1 + m)))}

{x^4*(e + f*x)^n/((a + b*x)*(c + d*x)), x, 8, (e^2*(e + f*x)^(1 + n))/(b*d*f^3*(1 + n)) + ((b*c + a*d)*e*(e + f*x)^(1 + n))/(b^2*d^2*f^2*(1 + n)) + ((b^2*c^2 + a*b*c*d + a^2*d^2)*(e + f*x)^(1 + n))/(b^3*d^3*f*(1 + n)) - (2*e*(e + f*x)^(2 + n))/(b*d*f^3*(2 + n)) - ((b*c + a*d)*(e + f*x)^(2 + n))/(b^2*d^2*f^2*(2 + n)) + (e + f*x)^(3 + n)/(b*d*f^3*(3 + n)) - (a^4*(e + f*x)^(1 + n)*Hypergeometric2F1[1, 1 + n, 2 + n, (b*(e + f*x))/(b*e - a*f)])/(b^3*(b*c - a*d)*(b*e - a*f)*(1 + n)) + (c^4*(e + f*x)^(1 + n)*Hypergeometric2F1[1, 1 + n, 2 + n, (d*(e + f*x))/(d*e - c*f)])/(d^3*(b*c - a*d)*(d*e - c*f)*(1 + n))}
{x^3*(e + f*x)^n/((a + b*x)*(c + d*x)), x, 6, -((e*(e + f*x)^(1 + n))/(b*d*f^2*(1 + n))) - ((b*c + a*d)*(e + f*x)^(1 + n))/(b^2*d^2*f*(1 + n)) + (e + f*x)^(2 + n)/(b*d*f^2*(2 + n)) + (a^3*(e + f*x)^(1 + n)*Hypergeometric2F1[1, 1 + n, 2 + n, (b*(e + f*x))/(b*e - a*f)])/(b^2*(b*c - a*d)*(b*e - a*f)*(1 + n)) - (c^3*(e + f*x)^(1 + n)*Hypergeometric2F1[1, 1 + n, 2 + n, (d*(e + f*x))/(d*e - c*f)])/(d^2*(b*c - a*d)*(d*e - c*f)*(1 + n))}
{x^2*(e + f*x)^n/((a + b*x)*(c + d*x)), x, 4, (e + f*x)^(1 + n)/(b*d*f*(1 + n)) - (a^2*(e + f*x)^(1 + n)*Hypergeometric2F1[1, 1 + n, 2 + n, (b*(e + f*x))/(b*e - a*f)])/(b*(b*c - a*d)*(b*e - a*f)*(1 + n)) + (c^2*(e + f*x)^(1 + n)*Hypergeometric2F1[1, 1 + n, 2 + n, (d*(e + f*x))/(d*e - c*f)])/(d*(b*c - a*d)*(d*e - c*f)*(1 + n))}
{x^1*(e + f*x)^n/((a + b*x)*(c + d*x)), x, 3, (a*(e + f*x)^(1 + n)*Hypergeometric2F1[1, 1 + n, 2 + n, (b*(e + f*x))/(b*e - a*f)])/((b*c - a*d)*(b*e - a*f)*(1 + n)) - (c*(e + f*x)^(1 + n)*Hypergeometric2F1[1, 1 + n, 2 + n, (d*(e + f*x))/(d*e - c*f)])/((b*c - a*d)*(d*e - c*f)*(1 + n))}
{x^0*(e + f*x)^n/((a + b*x)*(c + d*x)), x, 3, -((b*(e + f*x)^(1 + n)*Hypergeometric2F1[1, 1 + n, 2 + n, (b*(e + f*x))/(b*e - a*f)])/((b*c - a*d)*(b*e - a*f)*(1 + n))) + (d*(e + f*x)^(1 + n)*Hypergeometric2F1[1, 1 + n, 2 + n, (d*(e + f*x))/(d*e - c*f)])/((b*c - a*d)*(d*e - c*f)*(1 + n))}
{(e + f*x)^n/(x^1*(a + b*x)*(c + d*x)), x, 5, (b^2*(e + f*x)^(1 + n)*Hypergeometric2F1[1, 1 + n, 2 + n, (b*(e + f*x))/(b*e - a*f)])/(a*(b*c - a*d)*(b*e - a*f)*(1 + n)) - (d^2*(e + f*x)^(1 + n)*Hypergeometric2F1[1, 1 + n, 2 + n, (d*(e + f*x))/(d*e - c*f)])/(c*(b*c - a*d)*(d*e - c*f)*(1 + n)) - ((e + f*x)^(1 + n)*Hypergeometric2F1[1, 1 + n, 2 + n, 1 + (f*x)/e])/(a*c*e*(1 + n))}
{(e + f*x)^n/(x^2*(a + b*x)*(c + d*x)), x, 6, -((b^3*(e + f*x)^(1 + n)*Hypergeometric2F1[1, 1 + n, 2 + n, (b*(e + f*x))/(b*e - a*f)])/(a^2*(b*c - a*d)*(b*e - a*f)*(1 + n))) + (d^3*(e + f*x)^(1 + n)*Hypergeometric2F1[1, 1 + n, 2 + n, (d*(e + f*x))/(d*e - c*f)])/(c^2*(b*c - a*d)*(d*e - c*f)*(1 + n)) + ((b*c + a*d)*(e + f*x)^(1 + n)*Hypergeometric2F1[1, 1 + n, 2 + n, 1 + (f*x)/e])/(a^2*c^2*e*(1 + n)) + (f*(e + f*x)^(1 + n)*Hypergeometric2F1[2, 1 + n, 2 + n, 1 + (f*x)/e])/(a*c*e^2*(1 + n))}


(* ::Title:: *)
(*Integrands of the form (a+b x)^m (c+d x)^n (e+f x)^p (g+h x)^q*)


(* ::Section::Closed:: *)
(*Integrands of the form (a+b x)^m (c+d x)^n (e+f x)^p (g+h x)*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x)^m (c+d x)^n (e+f x) (g+h x)*)


{(a + b*x)^m*(c + d*x)^n*(e + f*x)*(g + h*x), x, 3, -(((a + b*x)^(1 + m)*(c + d*x)^(1 + n)*(b*c*f*h*(2 + m) + a*d*f*h*(2 + n) - b*d*(f*g + e*h)*(3 + m + n) - b*d*f*h*(2 + m + n)*x))/(b^2*d^2*(2 + m + n)*(3 + m + n))) + (1/(b^3*d^2*(1 + m)*(2 + m + n)*(3 + m + n)))*(((a^2*d^2*f*h*(1 + n)*(2 + n) + a*b*d*(1 + n)*(2*c*f*h*(1 + m) - d*(f*g + e*h)*(3 + m + n)) + b^2*(c^2*f*h*(1 + m)*(2 + m) - c*d*(f*g + e*h)*(1 + m)*(3 + m + n) + d^2*e*g*(2 + m + n)*(3 + m + n)))*(a + b*x)^(1 + m)*(c + d*x)^n*Hypergeometric2F1[1 + m, -n, 2 + m, -((d*(a + b*x))/(b*c - a*d))])/((b*(c + d*x))/(b*c - a*d))^n)}


{(a + b*x)^m/(c + d*x)^(m - 1)*(e + f*x)*(g + h*x), x, 3, ((a + b*x)^(1 + m)*(c + d*x)^(2 - m)*(4*b*d*(f*g + e*h) - a*d*f*h*(3 - m) - b*c*f*h*(2 + m) + 3*b*d*f*h*x))/(12*b^2*d^2) + ((b*c - a*d)*(a^2*d^2*f*h*(6 - 5*m + m^2) - 2*a*b*d*(2 - m)*(2*d*(f*g + e*h) - c*f*h*(1 + m)) + b^2*(12*d^2*e*g - 4*c*d*(f*g + e*h)*(1 + m) + c^2*f*h*(2 + 3*m + m^2)))*(a + b*x)^(1 + m)*((b*(c + d*x))/(b*c - a*d))^m*Hypergeometric2F1[-1 + m, 1 + m, 2 + m, -((d*(a + b*x))/(b*c - a*d))])/((c + d*x)^m*(12*b^4*d^2*(1 + m)))}
{(a + b*x)^m/(c + d*x)^(m + 0)*(e + f*x)*(g + h*x), x, 3, ((a + b*x)^(1 + m)*(c + d*x)^(1 - m)*(3*b*d*(f*g + e*h) - a*d*f*h*(2 - m) - b*c*f*h*(2 + m) + 2*b*d*f*h*x))/(6*b^2*d^2) + ((a^2*d^2*f*h*(2 - 3*m + m^2) - a*b*d*(1 - m)*(3*d*(f*g + e*h) - 2*c*f*h*(1 + m)) + b^2*(6*d^2*e*g - 3*c*d*(f*g + e*h)*(1 + m) + c^2*f*h*(2 + 3*m + m^2)))*(a + b*x)^(1 + m)*((b*(c + d*x))/(b*c - a*d))^m*Hypergeometric2F1[m, 1 + m, 2 + m, -((d*(a + b*x))/(b*c - a*d))])/((c + d*x)^m*(6*b^3*d^2*(1 + m)))}
{(a + b*x)^m/(c + d*x)^(m + 1)*(e + f*x)*(g + h*x), x, 3, ((a + b*x)^(1 + m)*(2*b*d^2*e*g + b*c^2*f*h*(2 + m) - c*d*(2*b*(f*g + e*h) + a*f*h*m) + d*(b*c - a*d)*f*h*m*x))/((c + d*x)^m*(2*b*d^2*(b*c - a*d)*m)) - ((b^2*c^2*f*h*(1 + m)*(2 + m) - 2*b*c*d*(1 + m)*(b*f*g + b*e*h + a*f*h*m) + d^2*(2*b^2*e*g + 2*a*b*(f*g + e*h)*m - a^2*f*h*(1 - m)*m))*(a + b*x)^(1 + m)*((b*(c + d*x))/(b*c - a*d))^m*Hypergeometric2F1[m, 1 + m, 2 + m, -((d*(a + b*x))/(b*c - a*d))])/((c + d*x)^m*(2*b^2*d^2*(b*c - a*d)*m*(1 + m)))}
{(a + b*x)^m/(c + d*x)^(m + 2)*(e + f*x)*(g + h*x), x, 3, ((a + b*x)^(1 + m)*(c + d*x)^(-1 - m)*(b*d^2*e*g + b*c^2*f*h*(2 + m) - c*d*(b*(f*g + e*h) + a*f*h*(1 + m)) + d*(b*c - a*d)*f*h*(1 + m)*x))/(b*d^2*(b*c - a*d)*(1 + m)) - ((a*d*f*h*m + b*(d*(f*g + e*h) - c*f*h*(2 + m)))*(a + b*x)^m*Hypergeometric2F1[-m, -m, 1 - m, (b*(c + d*x))/(b*c - a*d)])/((-((d*(a + b*x))/(b*c - a*d)))^m*(c + d*x)^m*(b*d^3*m))}
{(a + b*x)^m/(c + d*x)^(m + 3)*(e + f*x)*(g + h*x), x, 3, -((1/(b^2*(b*c - a*d)^2*(1 + m)*(2 + m)))*((a + b*x)^(1 + m)*(c + d*x)^(-2 - m)*(a^2*b*c*f*h*m - a^3*d*f*h*(1 + m) - b^3*c*e*g*(2 + m) + a*b^2*(c*(f*g + e*h) + d*e*g*(1 + m)) - b*(a^2*d*f*h*(3 + 2*m) + b^2*(d*e*g + c*(f*g + e*h)*(1 + m)) - a*b*(2*c*f*h*(1 + m) + d*(f*g + e*h)*(2 + m)))*x))) - ((b*c - a*d)^2*f*h*(a + b*x)^m*(c + d*x)^(-2 - m)*Hypergeometric2F1[-2 - m, -2 - m, -1 - m, (b*(c + d*x))/(b*c - a*d)])/((-((d*(a + b*x))/(b*c - a*d)))^m*(b^2*d^3*(2 + m)))}
{(a + b*x)^m/(c + d*x)^(m + 4)*(e + f*x)*(g + h*x), x, 3, ((a^2*d^2*f*h*(6 + 5*m + m^2) - a*b*d*(3 + m)*(d*(f*g + e*h) + 2*c*f*h*(1 + m)) + b^2*(2*d^2*e*g + c*d*(f*g + e*h)*(1 + m) + c^2*f*h*(2 + 3*m + m^2)))*(a + b*x)^(1 + m)*(c + d*x)^(-2 - m))/(b*d^2*(b*c - a*d)^2*(2 + m)*(3 + m)) + ((a^2*d^2*f*h*(6 + 5*m + m^2) - a*b*d*(3 + m)*(d*(f*g + e*h) + 2*c*f*h*(1 + m)) + b^2*(2*d^2*e*g + c*d*(f*g + e*h)*(1 + m) + c^2*f*h*(2 + 3*m + m^2)))*(a + b*x)^(1 + m)*(c + d*x)^(-1 - m))/(d^2*(b*c - a*d)^3*(1 + m)*(2 + m)*(3 + m)) + ((a + b*x)^(1 + m)*(c + d*x)^(-3 - m)*(a*c*d*f*h*(3 + m) + b*(d^2*e*g - c*d*(f*g + e*h) - c^2*f*h*(2 + m)) - d*(b*c - a*d)*f*h*(3 + m)*x))/(b*d^2*(b*c - a*d)*(3 + m))}
{(a + b*x)^m/(c + d*x)^(m + 5)*(e + f*x)*(g + h*x), x, 4, ((a^2*d^2*f*h*(12 + 7*m + m^2) - 2*a*b*d*(4 + m)*(d*(f*g + e*h) + c*f*h*(1 + m)) + b^2*(6*d^2*e*g + 2*c*d*(f*g + e*h)*(1 + m) + c^2*f*h*(2 + 3*m + m^2)))*(a + b*x)^(1 + m)*(c + d*x)^(-3 - m))/(2*b*d^2*(b*c - a*d)^2*(3 + m)*(4 + m)) + ((a^2*d^2*f*h*(12 + 7*m + m^2) - 2*a*b*d*(4 + m)*(d*(f*g + e*h) + c*f*h*(1 + m)) + b^2*(6*d^2*e*g + 2*c*d*(f*g + e*h)*(1 + m) + c^2*f*h*(2 + 3*m + m^2)))*(a + b*x)^(1 + m)*(c + d*x)^(-2 - m))/(d^2*(b*c - a*d)^3*(2 + m)*(3 + m)*(4 + m)) + (b*(a^2*d^2*f*h*(12 + 7*m + m^2) - 2*a*b*d*(4 + m)*(d*(f*g + e*h) + c*f*h*(1 + m)) + b^2*(6*d^2*e*g + 2*c*d*(f*g + e*h)*(1 + m) + c^2*f*h*(2 + 3*m + m^2)))*(a + b*x)^(1 + m)*(c + d*x)^(-1 - m))/(d^2*(b*c - a*d)^4*(1 + m)*(2 + m)*(3 + m)*(4 + m)) + ((a + b*x)^(1 + m)*(c + d*x)^(-4 - m)*(a*c*d*f*h*(4 + m) + b*(2*d^2*e*g - 2*c*d*(f*g + e*h) - c^2*f*h*(2 + m)) - d*(b*c - a*d)*f*h*(4 + m)*x))/(2*b*d^2*(b*c - a*d)*(4 + m))}


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x)^m (c+d x)^n (e+f x)^p (g+h x) with m, n and p symbolic*)


{(a + b*x)^3*(c + d*x)^(-4 - m)*(e + f*x)^m*(g + h*x), x, 10, ((b*c - a*d)^2*(a*d*f + b*(c*f*(2 + m) - d*e*(3 + m)))*(c*f*h*(4 + m) - d*(f*g + e*h*(3 + m)))*(c + d*x)^(-3 - m)*(e + f*x)^(1 + m))/(d^4*f^2*(d*e - c*f)*(3 + m)) - (b*(b*c - a*d)*(c*f*h*(4 + m) - d*(f*g + e*h*(3 + m)))*(a + b*x)*(c + d*x)^(-3 - m)*(e + f*x)^(1 + m))/(d^3*f^2) + (h*(a + b*x)^3*(c + d*x)^(-3 - m)*(e + f*x)^(1 + m))/(d*f) - ((b*c - a*d)^2*(3*a*d*f*h - b*(c*f*h*(4 + m) - d*(f*g + e*h*m)))*(c + d*x)^(-2 - m)*(e + f*x)^(1 + m))/(d^4*f*(d*e - c*f)*(2 + m)) + ((b*c - a*d)*(c*f*h*(4 + m) - d*(f*g + e*h*(3 + m)))*(2*a^2*d^2*f^2 + 2*a*b*d*f*(c*f*(1 + m) - d*e*(3 + m)) + b^2*(c^2*f^2*(2 + 3*m + m^2) - 2*c*d*e*f*(3 + 4*m + m^2) + d^2*e^2*(6 + 5*m + m^2)))*(c + d*x)^(-2 - m)*(e + f*x)^(1 + m))/(d^4*f^2*(d*e - c*f)^2*(2 + m)*(3 + m)) - ((b*c - a*d)*(a*d*f - b*(2*d*e*(2 + m) - c*f*(3 + 2*m)))*(3*a*d*f*h - b*(c*f*h*(4 + m) - d*(f*g + e*h*m)))*(c + d*x)^(-1 - m)*(e + f*x)^(1 + m))/(d^4*f*(d*e - c*f)^2*(1 + m)*(2 + m)) - ((b*c - a*d)*(c*f*h*(4 + m) - d*(f*g + e*h*(3 + m)))*(2*a^2*d^2*f^2 + 2*a*b*d*f*(c*f*(1 + m) - d*e*(3 + m)) + b^2*(c^2*f^2*(2 + 3*m + m^2) - 2*c*d*e*f*(3 + 4*m + m^2) + d^2*e^2*(6 + 5*m + m^2)))*(c + d*x)^(-1 - m)*(e + f*x)^(1 + m))/(d^4*f*(d*e - c*f)^3*(1 + m)*(2 + m)*(3 + m)) - (b^2*(3*a*d*f*h - b*(c*f*h*(4 + m) - d*(f*g + e*h*m)))*(e + f*x)^m*Hypergeometric2F1[-m, -m, 1 - m, -((f*(c + d*x))/(d*e - c*f))])/((c + d*x)^m*((d*(e + f*x))/(d*e - c*f))^m*(d^5*f*m))}
{(a + b*x)^2*(c + d*x)^(-4 - m)*(e + f*x)^m*(g + h*x), x, 9, ((b*c - a*d)*(d*g - c*h)*(a*d*f + b*(c*f*(2 + m) - d*e*(3 + m)))*(c + d*x)^(-3 - m)*(e + f*x)^(1 + m))/(d^3*f*(d*e - c*f)*(3 + m)) - (b*(d*g - c*h)*(a + b*x)*(c + d*x)^(-3 - m)*(e + f*x)^(1 + m))/(d^2*f) - ((b*c - a*d)^2*h*(c + d*x)^(-2 - m)*(e + f*x)^(1 + m))/(d^3*(d*e - c*f)*(2 + m)) - ((d*g - c*h)*(b^2*(d*e - c*f)*(2 + m)*(c*f*(1 + m) - d*e*(3 + m)) - 2*d*f*(b^2*c*e + a^2*d*f + a*b*(c*f*(1 + m) - d*e*(3 + m))))*(c + d*x)^(-2 - m)*(e + f*x)^(1 + m))/(d^3*f*(d*e - c*f)^2*(2 + m)*(3 + m)) - ((b*c - a*d)*h*(a*d*f - b*(2*d*e*(2 + m) - c*f*(3 + 2*m)))*(c + d*x)^(-1 - m)*(e + f*x)^(1 + m))/(d^3*(d*e - c*f)^2*(1 + m)*(2 + m)) + ((d*g - c*h)*(b^2*(d*e - c*f)*(2 + m)*(c*f*(1 + m) - d*e*(3 + m)) - 2*d*f*(b^2*c*e + a^2*d*f + a*b*(c*f*(1 + m) - d*e*(3 + m))))*(c + d*x)^(-1 - m)*(e + f*x)^(1 + m))/(d^3*(d*e - c*f)^3*(1 + m)*(2 + m)*(3 + m)) - (b^2*h*(e + f*x)^m*Hypergeometric2F1[-m, -m, 1 - m, -((f*(c + d*x))/(d*e - c*f))])/((c + d*x)^m*((d*(e + f*x))/(d*e - c*f))^m*(d^4*m))}
{(a + b*x)^1*(c + d*x)^(-4 - m)*(e + f*x)^m*(g + h*x), x, 3, ((b*(c^2*f^2*h*(2 + 3*m + m^2) - d^2*e*(3 + m)*(f*g - e*h*(2 + m)) + c*d*f*(1 + m)*(f*g - 2*e*h*(3 + m))) + a*d*f*(c*f*h*(1 + m) + d*(2*f*g - e*h*(3 + m))))*(c + d*x)^(-2 - m)*(e + f*x)^(1 + m))/(d^2*f*(d*e - c*f)^2*(2 + m)*(3 + m)) - ((b*(c^2*f^2*h*(2 + 3*m + m^2) - d^2*e*(3 + m)*(f*g - e*h*(2 + m)) + c*d*f*(1 + m)*(f*g - 2*e*h*(3 + m))) + a*d*f*(c*f*h*(1 + m) + d*(2*f*g - e*h*(3 + m))))*(c + d*x)^(-1 - m)*(e + f*x)^(1 + m))/(d^2*(d*e - c*f)^3*(1 + m)*(2 + m)*(3 + m)) - ((c + d*x)^(-3 - m)*(e + f*x)^(1 + m)*(a*d*f*(d*g - c*h) - b*c*(c*f*h*(2 + m) + d*(f*g - e*h*(3 + m))) + b*d*(d*e - c*f)*h*(3 + m)*x))/(d^2*f*(d*e - c*f)*(3 + m))}
{(a + b*x)^0*(c + d*x)^(-4 - m)*(e + f*x)^m*(g + h*x), x, 3, -(((d*g - c*h)*(c + d*x)^(-3 - m)*(e + f*x)^(1 + m))/(d*(d*e - c*f)*(3 + m))) + ((c*f*h*(1 + m) + d*(2*f*g - e*h*(3 + m)))*(c + d*x)^(-2 - m)*(e + f*x)^(1 + m))/(d*(d*e - c*f)^2*(2 + m)*(3 + m)) - (f*(c*f*h*(1 + m) + d*(2*f*g - e*h*(3 + m)))*(c + d*x)^(-1 - m)*(e + f*x)^(1 + m))/(d*(d*e - c*f)^3*(1 + m)*(2 + m)*(3 + m))}


{(a + b*x)^m*(c + d*x)^n*(e + f*x)^p*(A + B*x), x, 7, ((A*b - a*B)*(a + b*x)^(1 + m)*(c + d*x)^n*(e + f*x)^p*AppellF1[1 + m, -n, -p, 2 + m, -((d*(a + b*x))/(b*c - a*d)), -((f*(a + b*x))/(b*e - a*f))])/(((b*(c + d*x))/(b*c - a*d))^n*((b*(e + f*x))/(b*e - a*f))^p*(b^2*(1 + m))) + (B*(a + b*x)^(2 + m)*(c + d*x)^n*(e + f*x)^p*AppellF1[2 + m, -n, -p, 3 + m, -((d*(a + b*x))/(b*c - a*d)), -((f*(a + b*x))/(b*e - a*f))])/(((b*(c + d*x))/(b*c - a*d))^n*((b*(e + f*x))/(b*e - a*f))^p*(b^2*(2 + m)))}

{(a + b*x)^m*(c + d*x)^n/(e + f*x)^(m + n + 0)*(A + B*x), x, 7, ((A*b - a*B)*(a + b*x)^(1 + m)*(c + d*x)^n*(e + f*x)^(-m - n)*((b*(e + f*x))/(b*e - a*f))^(m + n)*AppellF1[1 + m, -n, m + n, 2 + m, -((d*(a + b*x))/(b*c - a*d)), -((f*(a + b*x))/(b*e - a*f))])/(((b*(c + d*x))/(b*c - a*d))^n*(b^2*(1 + m))) + (B*(a + b*x)^(2 + m)*(c + d*x)^n*(e + f*x)^(-m - n)*((b*(e + f*x))/(b*e - a*f))^(m + n)*AppellF1[2 + m, -n, m + n, 3 + m, -((d*(a + b*x))/(b*c - a*d)), -((f*(a + b*x))/(b*e - a*f))])/(((b*(c + d*x))/(b*c - a*d))^n*(b^2*(2 + m)))}
{(a + b*x)^m*(c + d*x)^n/(e + f*x)^(m + n + 1)*(A + B*x), x, 7, (B*(a + b*x)^(1 + m)*(c + d*x)^n*(e + f*x)^(-m - n)*((b*(e + f*x))/(b*e - a*f))^(m + n)*AppellF1[1 + m, -n, m + n, 2 + m, -((d*(a + b*x))/(b*c - a*d)), -((f*(a + b*x))/(b*e - a*f))])/(((b*(c + d*x))/(b*c - a*d))^n*(b*f*(1 + m))) - ((B*e - A*f)*(a + b*x)^(1 + m)*(c + d*x)^n*(e + f*x)^(-m - n)*((b*(e + f*x))/(b*e - a*f))^(m + n)*AppellF1[1 + m, -n, 1 + m + n, 2 + m, -((d*(a + b*x))/(b*c - a*d)), -((f*(a + b*x))/(b*e - a*f))])/(((b*(c + d*x))/(b*c - a*d))^n*(f*(b*e - a*f)*(1 + m)))}
{(a + b*x)^m*(c + d*x)^n/(e + f*x)^(m + n + 2)*(A + B*x), x, 5, (B*(a + b*x)^(1 + m)*(c + d*x)^n*(e + f*x)^(-m - n)*((b*(e + f*x))/(b*e - a*f))^(m + n)*AppellF1[1 + m, -n, 1 + m + n, 2 + m, -((d*(a + b*x))/(b*c - a*d)), -((f*(a + b*x))/(b*e - a*f))])/(((b*(c + d*x))/(b*c - a*d))^n*(f*(b*e - a*f)*(1 + m))) - ((B*e - A*f)*(a + b*x)^(1 + m)*(c + d*x)^n*(e + f*x)^(-1 - m - n)*Hypergeometric2F1[1 + m, -n, 2 + m, -(((d*e - c*f)*(a + b*x))/((b*c - a*d)*(e + f*x)))])/((((b*e - a*f)*(c + d*x))/((b*c - a*d)*(e + f*x)))^n*(f*(b*e - a*f)*(1 + m)))}
{(a + b*x)^m*(c + d*x)^n/(e + f*x)^(m + n + 3)*(A + B*x), x, 3, ((B*e - A*f)*(a + b*x)^(1 + m)*(c + d*x)^(1 + n)*(e + f*x)^(-2 - m - n))/((b*e - a*f)*(d*e - c*f)*(2 + m + n)) - (1/((b*e - a*f)^2*(d*e - c*f)*(1 + m)*(2 + m + n)))*(((b*(B*c*e*(1 + m) + A*(c*f*(1 + n) - d*e*(2 + m + n))) + a*(A*d*f*(1 + m) + B*(d*e*(1 + n) - c*f*(2 + m + n))))*(a + b*x)^(1 + m)*(c + d*x)^n*(e + f*x)^(-1 - m - n)*Hypergeometric2F1[1 + m, -n, 2 + m, -(((d*e - c*f)*(a + b*x))/((b*c - a*d)*(e + f*x)))])/(((b*e - a*f)*(c + d*x))/((b*c - a*d)*(e + f*x)))^n)}
{(a + b*x)^m*(c + d*x)^n/(e + f*x)^(m + n + 4)*(A + B*x), x, 4, ((B*e - A*f)*(a + b*x)^(1 + m)*(c + d*x)^(1 + n)*(e + f*x)^(-3 - m - n))/((b*e - a*f)*(d*e - c*f)*(3 + m + n)) + ((a*f*(A*d*f*(2 + m) + B*(d*e*(1 + n) - c*f*(3 + m + n))) + b*(B*e*(d*e + c*f*(1 + m)) + A*f*(c*f*(2 + n) - d*e*(4 + m + n))))*(a + b*x)^(1 + m)*(c + d*x)^(1 + n)*(e + f*x)^(-2 - m - n))/((b*e - a*f)^2*(d*e - c*f)^2*(2 + m + n)*(3 + m + n)) + (1/((b*e - a*f)^3*(d*e - c*f)^2*(1 + m)*(2 + m + n)*(3 + m + n)))*((((2 + m + n)*(a*b*c*d*f*(B*e - A*f) + b*d*e*((a*B*c*f + A*(b*d*e - b*c*f - a*d*f))*(3 + m + n) - (B*e - A*f)*(b*c*(1 + m) + a*d*(1 + n))) - (b*c + a*d)*f*((a*B*c*f + A*(b*d*e - b*c*f - a*d*f))*(3 + m + n) - (B*e - A*f)*(b*c*(1 + m) + a*d*(1 + n)))) - (b*c*(1 + m) + a*d*(1 + n))*(a*f*(A*d*f*(2 + m) + B*(d*e*(1 + n) - c*f*(3 + m + n))) + b*(B*e*(d*e + c*f*(1 + m)) + A*f*(c*f*(2 + n) - d*e*(4 + m + n)))))*(a + b*x)^(1 + m)*(c + d*x)^n*(e + f*x)^(-1 - m - n)*Hypergeometric2F1[1 + m, -n, 2 + m, -(((d*e - c*f)*(a + b*x))/((b*c - a*d)*(e + f*x)))])/(((b*e - a*f)*(c + d*x))/((b*c - a*d)*(e + f*x)))^n)}
(* {(a + b*x)^m*(c + d*x)^n/(e + f*x)^(m + n + 5)*(A + B*x), x, 5, ((B*e - A*f)*(a + b*x)^(1 + m)*(c + d*x)^(1 + n)*(e + f*x)^(-4 - m - n))/((b*e - a*f)*(d*e - c*f)*(4 + m + n)) + ((a*f*(A*d*f*(3 + m) + B*(d*e*(1 + n) - c*f*(4 + m + n))) + b*(B*e*(2*d*e + c*f*(1 + m)) + A*f*(c*f*(3 + n) - d*e*(6 + m + n))))*(a + b*x)^(1 + m)*(c + d*x)^(1 + n)*(e + f*x)^(-3 - m - n))/((b*e - a*f)^2*(d*e - c*f)^2*(3 + m + n)*(4 + m + n)) + ((b*d*e*(a*f*(A*d*f*(3 + m) + B*(d*e*(1 + n) - c*f*(4 + m + n))) + b*(B*e*(2*d*e + c*f*(1 + m)) + A*f*(c*f*(3 + n) - d*e*(6 + m + n)))) - f*((3 + m + n)*(2*a*b*c*d*f*(B*e - A*f) + b*d*e*((a*B*c*f + A*(b*d*e - b*c*f - a*d*f))*(4 + m + n) - (B*e - A*f)*(b*c*(1 + m) + a*d*(1 + n))) - (b*c + a*d)*f*((a*B*c*f + A*(b*d*e - b*c*f - a*d*f))*(4 + m + n) - (B*e - A*f)*(b*c*(1 + m) + a*d*(1 + n)))) - (b*c*(1 + m) + a*d*(1 + n))*(a*f*(A*d*f*(3 + m) + B*(d*e*(1 + n) - c*f*(4 + m + n))) + b*(B*e*(2*d*e + c*f*(1 + m)) + A*f*(c*f*(3 + n) - d*e*(6 + m + n))))))*(a + b*x)^(1 + m)*(c + d*x)^(1 + n)*(e + f*x)^(-2 - m - n))/((b*e - a*f)^3*(d*e - c*f)^3*(2 + m + n)*(3 + m + n)*(4 + m + n)) - (((b*c*(1 + m) + a*d*(1 + n))*(b*d*e*(a*f*(A*d*f*(3 + m) + B*(d*e*(1 + n) - c*f*(4 + m + n))) + b*(B*e*(2*d*e + c*f*(1 + m)) + A*f*(c*f*(3 + n) - d*e*(6 + m + n)))) - f*((3 + m + n)*(2*a*b*c*d*f*(B*e - A*f) + b*d*e*((a*B*c*f + A*(b*d*e - b*c*f - a*d*f))*(4 + m + n) - (B*e - A*f)*(b*c*(1 + m) + a*d*(1 + n))) - (b*c + a*d)*f*((a*B*c*f + A*(b*d*e - b*c*f - a*d*f))*(4 + m + n) - (B*e - A*f)*(b*c*(1 + m) + a*d*(1 + n)))) - (b*c*(1 + m) + a*d*(1 + n))*(a*f*(A*d*f*(3 + m) + B*(d*e*(1 + n) - c*f*(4 + m + n))) + b*(B*e*(2*d*e + c*f*(1 + m)) + A*f*(c*f*(3 + n) - d*e*(6 + m + n)))))) - (2 + m + n)*(a*b*c*d*f*(a*f*(A*d*f*(3 + m) + B*(d*e*(1 + n) - c*f*(4 + m + n))) + b*(B*e*(2*d*e + c*f*(1 + m)) + A*f*(c*f*(3 + n) - d*e*(6 + m + n)))) + b*d*e*((3 + m + n)*(2*a*b*c*d*f*(B*e - A*f) + b*d*e*((a*B*c*f + A*(b*d*e - b*c*f - a*d*f))*(4 + m + n) - (B*e - A*f)*(b*c*(1 + m) + a*d*(1 + n))) - (b*c + a*d)*f*((a*B*c*f + A*(b*d*e - b*c*f - a*d*f))*(4 + m + n) - (B*e - A*f)*(b*c*(1 + m) + a*d*(1 + n)))) - (b*c*(1 + m) + a*d*(1 + n))*(a*f*(A*d*f*(3 + m) + B*(d*e*(1 + n) - c*f*(4 + m + n))) + b*(B*e*(2*d*e + c*f*(1 + m)) + A*f*(c*f*(3 + n) - d*e*(6 + m + n))))) - (b*c + a*d)*f*((3 + m + n)*(2*a*b*c*d*f*(B*e - A*f) + b*d*e*((a*B*c*f + A*(b*d*e - b*c*f - a*d*f))*(4 + m + n) - (B*e - A*f)*(b*c*(1 + m) + a*d*(1 + n))) - (b*c + a*d)*f*((a*B*c*f + A*(b*d*e - b*c*f - a*d*f))*(4 + m + n) - (B*e - A*f)*(b*c*(1 + m) + a*d*(1 + n)))) - (b*c*(1 + m) + a*d*(1 + n))*(a*f*(A*d*f*(3 + m) + B*(d*e*(1 + n) - c*f*(4 + m + n))) + b*(B*e*(2*d*e + c*f*(1 + m)) + A*f*(c*f*(3 + n) - d*e*(6 + m + n)))))))*(a + b*x)^(1 + m)*(c + d*x)^n*(e + f*x)^(-1 - m - n)*Hypergeometric2F1[1 + m, -n, 2 + m, -(((d*e - c*f)*(a + b*x))/((b*c - a*d)*(e + f*x)))])/(((b*e - a*f)*(c + d*x))/((b*c - a*d)*(e + f*x)))^n/((b*e - a*f)^4*(d*e - c*f)^3*(1 + m)*(2 + m + n)*(3 + m + n)*(4 + m + n))} *)


{((c + d*x)^n*(e + f*x)^p*(A + B*x))/(a + b*x), x, 5, -(((A*b - a*B)*(c + d*x)^(1 + n)*(e + f*x)^p*AppellF1[1 + n, 1, -p, 2 + n, (b*(c + d*x))/(b*c - a*d), -((f*(c + d*x))/(d*e - c*f))])/(((d*(e + f*x))/(d*e - c*f))^p*(b*(b*c - a*d)*(1 + n)))) - (B*(c + d*x)^(1 + n)*(e + f*x)^(1 + p)*Hypergeometric2F1[1, 2 + n + p, 2 + p, (d*(e + f*x))/(d*e - c*f)])/(b*(d*e - c*f)*(1 + p)), -(((A*b - a*B)*(c + d*x)^(1 + n)*(e + f*x)^p*AppellF1[1 + n, -p, 1, 2 + n, -((f*(c + d*x))/(d*e - c*f)), (b*(c + d*x))/(b*c - a*d)])/(((d*(e + f*x))/(d*e - c*f))^p*(b*(b*c - a*d)*(1 + n)))) + (B*(c + d*x)^(1 + n)*(e + f*x)^p*Hypergeometric2F1[1 + n, -p, 2 + n, -((f*(c + d*x))/(d*e - c*f))])/(((d*(e + f*x))/(d*e - c*f))^p*(b*d*(1 + n)))}
{((c + d*x)^n*(e + f*x)^p*(A + B*x))/Sqrt[a + b*x], x, 7, (2*(A*b - a*B)*Sqrt[a + b*x]*(c + d*x)^n*(e + f*x)^p*AppellF1[1/2, -n, -p, 3/2, -((d*(a + b*x))/(b*c - a*d)), -((f*(a + b*x))/(b*e - a*f))])/(((b*(c + d*x))/(b*c - a*d))^n*((b*(e + f*x))/(b*e - a*f))^p*b^2) + (2*B*(a + b*x)^(3/2)*(c + d*x)^n*(e + f*x)^p*AppellF1[3/2, -n, -p, 5/2, -((d*(a + b*x))/(b*c - a*d)), -((f*(a + b*x))/(b*e - a*f))])/(((b*(c + d*x))/(b*c - a*d))^n*((b*(e + f*x))/(b*e - a*f))^p*(3*b^2))}


(* ::Section:: *)
(*Integrands of the form (a+b x)^m (c+d x)^n (e+f x)^p (g+h x)^q*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x)^m (c+d x)^n (e+f x)^p (g+h x)^q*)


{(a+b*x)*(c+d*x)*(e+f*x)*(g+h*x), x, 2, a*c*e*g*x + (1/2)*(b*c*e*g + a*(d*e*g + c*f*g + c*e*h))*x^2 + (1/3)*(b*(d*e*g + c*f*g + c*e*h) + a*(d*f*g + d*e*h + c*f*h))*x^3 + (1/4)*(a*d*f*h + b*(d*f*g + d*e*h + c*f*h))*x^4 + (1/5)*b*d*f*h*x^5}
{(a+b*x)*(c+d*x)*(e+f*x)/(g+h*x), x, 2, ((b*(d*g - c*h)*(f*g - e*h) - a*h*(d*f*g - d*e*h - c*f*h))*x)/h^3 + ((a*d*f*h - b*(d*f*g - d*e*h - c*f*h))*x^2)/(2*h^2) + (b*d*f*x^3)/(3*h) - ((b*g - a*h)*(d*g - c*h)*(f*g - e*h)*Log[g + h*x])/h^4}
{(a+b*x)*(c+d*x)/((e+f*x)*(g+h*x)), x, 2, (b*d*x)/(f*h) + ((b*e - a*f)*(d*e - c*f)*Log[e + f*x])/(f^2*(f*g - e*h)) - ((b*g - a*h)*(d*g - c*h)*Log[g + h*x])/(h^2*(f*g - e*h))}
{(a+b*x)/((c+d*x)*(e+f*x)*(g+h*x)), x, 2, -(((b*c - a*d)*Log[c + d*x])/((d*e - c*f)*(d*g - c*h))) + ((b*e - a*f)*Log[e + f*x])/((d*e - c*f)*(f*g - e*h)) - ((b*g - a*h)*Log[g + h*x])/((d*g - c*h)*(f*g - e*h))}
{1/((a+b*x)*(c+d*x)*(e+f*x)*(g+h*x)), x, 2, (b^2*Log[a + b*x])/((b*c - a*d)*(b*e - a*f)*(b*g - a*h)) - (d^2*Log[c + d*x])/((b*c - a*d)*(d*e - c*f)*(d*g - c*h)) + (f^2*Log[e + f*x])/((b*e - a*f)*(d*e - c*f)*(f*g - e*h)) - (h^2*Log[g + h*x])/((b*g - a*h)*(d*g - c*h)*(f*g - e*h))}


{x/((1 + x)*(2 + x)*(3 + x)), x, 2, (-(1/2))*Log[1 + x] + 2*Log[2 + x] - (3/2)*Log[3 + x]}


{(-x^2 + x^3)/((-6 + x)*(3 + 5*x)^3), x, 3, -(12/(1375*(3 + 5*x)^2)) + 201/(15125*(3 + 5*x)) + (20*Log[6 - x])/3993 + (1493*Log[3 + 5*x])/499125}


(* ::Subsection:: *)
(*Integrands of the form (a+b x)^m (c+d x)^n (e+f x)^p (g+h x)^(q/2)*)


(* ::Subsection:: *)
(*Integrands of the form (a+b x)^m (c+d x)^n (e+f x)^(p/2) (g+h x)^(q/2)*)


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x)^m (c+d x)^(n/2) (e+f x)^(p/2) (g+h x)^(q/2)*)


(* ::Subsubsection::Closed:: *)
(*p<0 & q<0*)


{1/((a + b*x)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 1, -((2*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticPi[-((b*(d*e - c*f))/((b*c - a*d)*f)), ArcSin[Sqrt[-(f/(d*e - c*f))]*Sqrt[c + d*x]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/((b*c - a*d)*Sqrt[-(f/(d*e - c*f))]*Sqrt[e + f*x]*Sqrt[g + h*x]))}
{(c*i + d*i*x)/(Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 3, (2*Sqrt[(-f)*g + e*h]*i*Sqrt[c + d*x]*Sqrt[(f*(g + h*x))/(f*g - e*h)]*EllipticE[ArcSin[(Sqrt[h]*Sqrt[e + f*x])/Sqrt[(-f)*g + e*h]], -((d*(f*g - e*h))/((d*e - c*f)*h))])/(f*Sqrt[h]*Sqrt[-((f*(c + d*x))/(d*e - c*f))]*Sqrt[g + h*x])}
{1/((a + b*x)*(c + d*x)^(5/2)*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 14, (2*d^2*Sqrt[e + f*x]*Sqrt[g + h*x])/(3*(b*c - a*d)*(d*e - c*f)*(d*g - c*h)*(c + d*x)^(3/2)) + (2*b*d^2*Sqrt[e + f*x]*Sqrt[g + h*x])/((b*c - a*d)^2*(d*e - c*f)*(d*g - c*h)*Sqrt[c + d*x]) - (4*d^2*(d*f*g + d*e*h - 2*c*f*h)*Sqrt[e + f*x]*Sqrt[g + h*x])/(3*(b*c - a*d)*(d*e - c*f)^2*(d*g - c*h)^2*Sqrt[c + d*x]) + (4*d*Sqrt[f]*(d*f*g + d*e*h - 2*c*f*h)*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[g + h*x]*EllipticE[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(3*(b*c - a*d)*((-d)*e + c*f)^(3/2)*(d*g - c*h)^2*Sqrt[e + f*x]*Sqrt[(d*(g + h*x))/(d*g - c*h)]) - (2*b*d*Sqrt[h]*Sqrt[(-f)*g + e*h]*Sqrt[c + d*x]*Sqrt[(f*(g + h*x))/(f*g - e*h)]*EllipticE[ArcSin[(Sqrt[h]*Sqrt[e + f*x])/Sqrt[(-f)*g + e*h]], -((d*(f*g - e*h))/((d*e - c*f)*h))])/((b*c - a*d)^2*(d*e - c*f)*(d*g - c*h)*Sqrt[-((f*(c + d*x))/(d*e - c*f))]*Sqrt[g + h*x]) - (2*Sqrt[f]*(2*d*f*g + d*e*h - 3*c*f*h)*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticF[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(3*(b*c - a*d)*((-d)*e + c*f)^(3/2)*(d*g - c*h)*Sqrt[e + f*x]*Sqrt[g + h*x]) - (2*b^2*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticPi[-((b*(d*e - c*f))/((b*c - a*d)*f)), ArcSin[Sqrt[-(f/(d*e - c*f))]*Sqrt[c + d*x]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/((b*c - a*d)^3*Sqrt[-(f/(d*e - c*f))]*Sqrt[e + f*x]*Sqrt[g + h*x])}


{(c + d*x)^(3/2)/((a + b*x)*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 7, (2*d*Sqrt[(-f)*g + e*h]*Sqrt[c + d*x]*Sqrt[(f*(g + h*x))/(f*g - e*h)]*EllipticE[ArcSin[(Sqrt[h]*Sqrt[e + f*x])/Sqrt[(-f)*g + e*h]], -((d*(f*g - e*h))/((d*e - c*f)*h))])/(b*f*Sqrt[h]*Sqrt[-((f*(c + d*x))/(d*e - c*f))]*Sqrt[g + h*x]) + (2*(b*c - a*d)*Sqrt[(-d)*e + c*f]*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticF[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(b^2*Sqrt[f]*Sqrt[e + f*x]*Sqrt[g + h*x]) - (2*(b*c - a*d)*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticPi[-((b*(d*e - c*f))/((b*c - a*d)*f)), ArcSin[Sqrt[-(f/(d*e - c*f))]*Sqrt[c + d*x]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(b^2*Sqrt[-(f/(d*e - c*f))]*Sqrt[e + f*x]*Sqrt[g + h*x])}
{(c + d*x)^(1/2)/((a + b*x)*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 5, (2*Sqrt[(-d)*e + c*f]*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticF[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(b*Sqrt[f]*Sqrt[e + f*x]*Sqrt[g + h*x]) - (2*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticPi[-((b*(d*e - c*f))/((b*c - a*d)*f)), ArcSin[Sqrt[-(f/(d*e - c*f))]*Sqrt[c + d*x]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(b*Sqrt[-(f/(d*e - c*f))]*Sqrt[e + f*x]*Sqrt[g + h*x])}
{1/((c + d*x)^(1/2)*(a + b*x)*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 1, -((2*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticPi[-((b*(d*e - c*f))/((b*c - a*d)*f)), ArcSin[Sqrt[-(f/(d*e - c*f))]*Sqrt[c + d*x]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/((b*c - a*d)*Sqrt[-(f/(d*e - c*f))]*Sqrt[e + f*x]*Sqrt[g + h*x]))}
{1/((c + d*x)^(3/2)*(a + b*x)*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 7, (2*d^2*Sqrt[e + f*x]*Sqrt[g + h*x])/((b*c - a*d)*(d*e - c*f)*(d*g - c*h)*Sqrt[c + d*x]) - (2*d*Sqrt[h]*Sqrt[(-f)*g + e*h]*Sqrt[c + d*x]*Sqrt[(f*(g + h*x))/(f*g - e*h)]*EllipticE[ArcSin[(Sqrt[h]*Sqrt[e + f*x])/Sqrt[(-f)*g + e*h]], -((d*(f*g - e*h))/((d*e - c*f)*h))])/((b*c - a*d)*(d*e - c*f)*(d*g - c*h)*Sqrt[-((f*(c + d*x))/(d*e - c*f))]*Sqrt[g + h*x]) - (2*b*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticPi[-((b*(d*e - c*f))/((b*c - a*d)*f)), ArcSin[Sqrt[-(f/(d*e - c*f))]*Sqrt[c + d*x]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/((b*c - a*d)^2*Sqrt[-(f/(d*e - c*f))]*Sqrt[e + f*x]*Sqrt[g + h*x])}
{1/((c + d*x)^(5/2)*(a + b*x)*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 14, (2*d^2*Sqrt[e + f*x]*Sqrt[g + h*x])/(3*(b*c - a*d)*(d*e - c*f)*(d*g - c*h)*(c + d*x)^(3/2)) + (2*b*d^2*Sqrt[e + f*x]*Sqrt[g + h*x])/((b*c - a*d)^2*(d*e - c*f)*(d*g - c*h)*Sqrt[c + d*x]) - (4*d^2*(d*f*g + d*e*h - 2*c*f*h)*Sqrt[e + f*x]*Sqrt[g + h*x])/(3*(b*c - a*d)*(d*e - c*f)^2*(d*g - c*h)^2*Sqrt[c + d*x]) + (4*d*Sqrt[f]*(d*f*g + d*e*h - 2*c*f*h)*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[g + h*x]*EllipticE[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(3*(b*c - a*d)*((-d)*e + c*f)^(3/2)*(d*g - c*h)^2*Sqrt[e + f*x]*Sqrt[(d*(g + h*x))/(d*g - c*h)]) - (2*b*d*Sqrt[h]*Sqrt[(-f)*g + e*h]*Sqrt[c + d*x]*Sqrt[(f*(g + h*x))/(f*g - e*h)]*EllipticE[ArcSin[(Sqrt[h]*Sqrt[e + f*x])/Sqrt[(-f)*g + e*h]], -((d*(f*g - e*h))/((d*e - c*f)*h))])/((b*c - a*d)^2*(d*e - c*f)*(d*g - c*h)*Sqrt[-((f*(c + d*x))/(d*e - c*f))]*Sqrt[g + h*x]) - (2*Sqrt[f]*(2*d*f*g + d*e*h - 3*c*f*h)*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticF[ArcSin[(Sqrt[f]*Sqrt[c + d*x])/Sqrt[(-d)*e + c*f]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/(3*(b*c - a*d)*((-d)*e + c*f)^(3/2)*(d*g - c*h)*Sqrt[e + f*x]*Sqrt[g + h*x]) - (2*b^2*Sqrt[(d*(e + f*x))/(d*e - c*f)]*Sqrt[(d*(g + h*x))/(d*g - c*h)]*EllipticPi[-((b*(d*e - c*f))/((b*c - a*d)*f)), ArcSin[Sqrt[-(f/(d*e - c*f))]*Sqrt[c + d*x]], ((d*e - c*f)*h)/(f*(d*g - c*h))])/((b*c - a*d)^3*Sqrt[-(f/(d*e - c*f))]*Sqrt[e + f*x]*Sqrt[g + h*x])}


(* ::Subsection:: *)
(*Integrands of the form (a+b x)^(m/2) (c+d x)^(n/2) (e+f x)^(p/2) (g+h x)^(q/2)*)


{1/(Sqrt[a + b*x]*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 2, -((2*Sqrt[f*g - e*h]*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*Sqrt[1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x))]*EllipticF[ArcTan[(Sqrt[b*e - a*f]*Sqrt[g + h*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], ((d*e - c*f)*(b*g - a*h))/((b*e - a*f)*(d*g - c*h))])/(Sqrt[b*e - a*f]*(b*g - a*h)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[(1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x)))/(1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]*Sqrt[1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x))]))}
{Sqrt[c + d*x]/((a + b*x)^(3/2)*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 5, -((2*(d*g - c*h)*Sqrt[a + b*x]*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*Sqrt[g + h*x]*Sqrt[1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x))])/((b*g - a*h)^2*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x))])) + (2*(d*g - c*h)*Sqrt[f*g - e*h]*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*Sqrt[1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x))]*EllipticE[ArcTan[(Sqrt[b*e - a*f]*Sqrt[g + h*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], ((d*e - c*f)*(b*g - a*h))/((b*e - a*f)*(d*g - c*h))])/(Sqrt[b*e - a*f]*(b*g - a*h)^2*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[(1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x)))/(1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]*Sqrt[1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x))]) - (2*(d*g - c*h)*Sqrt[f*g - e*h]*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*Sqrt[1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x))]*EllipticF[ArcTan[(Sqrt[b*e - a*f]*Sqrt[g + h*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], ((d*e - c*f)*(b*g - a*h))/((b*e - a*f)*(d*g - c*h))])/(Sqrt[b*e - a*f]*(b*g - a*h)^2*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[(1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x)))/(1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]*Sqrt[1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x))])}
{Sqrt[a + b*x]/(Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 4, (2*Sqrt[b*e - a*f]*Sqrt[f*g - e*h]*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*Sqrt[1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x))]*EllipticF[ArcTan[(Sqrt[b*e - a*f]*Sqrt[g + h*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], ((d*e - c*f)*(b*g - a*h))/((b*e - a*f)*(d*g - c*h))])/(f*(b*g - a*h)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[(1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x)))/(1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]*Sqrt[1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x))]) + (2*b*(f*g - e*h)^(3/2)*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*Sqrt[1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x))]*EllipticPi[(f*(b*g - a*h))/((b*e - a*f)*h), ArcTan[(Sqrt[b*e - a*f]*Sqrt[g + h*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], ((d*e - c*f)*(b*g - a*h))/((b*e - a*f)*(d*g - c*h))])/(f*Sqrt[b*e - a*f]*h*(b*g - a*h)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[(1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x)))/(1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]*Sqrt[1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x))])}
{1/((a + b*x)^(3/2)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 8, -((2*b*Sqrt[c + d*x]*Sqrt[g + h*x])/((b*c - a*d)*(b*g - a*h)*Sqrt[a + b*x]*Sqrt[e + f*x])) + (2*b*Sqrt[f*g - e*h]*Sqrt[c + d*x]*EllipticE[ArcTan[(Sqrt[b*e - a*f]*Sqrt[g + h*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], ((d*e - c*f)*(b*g - a*h))/((b*e - a*f)*(d*g - c*h))])/((b*c - a*d)*Sqrt[b*e - a*f]*(b*g - a*h)*Sqrt[((f*g - e*h)*(c + d*x))/((d*g - c*h)*(e + f*x))]*Sqrt[e + f*x]) + (2*h*Sqrt[((f*g - e*h)*(c + d*x))/((d*g - c*h)*(e + f*x))]*Sqrt[e + f*x]*EllipticF[ArcTan[(Sqrt[b*e - a*f]*Sqrt[g + h*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], ((d*e - c*f)*(b*g - a*h))/((b*e - a*f)*(d*g - c*h))])/(Sqrt[b*e - a*f]*(b*g - a*h)*Sqrt[f*g - e*h]*Sqrt[c + d*x]), -((2*b*(d*g - c*h)*Sqrt[a + b*x]*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*Sqrt[g + h*x]*Sqrt[1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x))])/((b*c - a*d)*(b*g - a*h)^2*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x))])) + (2*b*(d*g - c*h)*Sqrt[f*g - e*h]*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*Sqrt[1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x))]*EllipticE[ArcTan[(Sqrt[b*e - a*f]*Sqrt[g + h*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], ((d*e - c*f)*(b*g - a*h))/((b*e - a*f)*(d*g - c*h))])/((b*c - a*d)*Sqrt[b*e - a*f]*(b*g - a*h)^2*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[(1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x)))/(1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]*Sqrt[1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x))]) + (2*d*Sqrt[f*g - e*h]*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*Sqrt[1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x))]*EllipticF[ArcTan[(Sqrt[b*e - a*f]*Sqrt[g + h*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], ((d*e - c*f)*(b*g - a*h))/((b*e - a*f)*(d*g - c*h))])/((b*c - a*d)*Sqrt[b*e - a*f]*(b*g - a*h)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[(1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x)))/(1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]*Sqrt[1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x))]) - (2*b*(d*g - c*h)*Sqrt[f*g - e*h]*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*Sqrt[1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x))]*EllipticF[ArcTan[(Sqrt[b*e - a*f]*Sqrt[g + h*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], ((d*e - c*f)*(b*g - a*h))/((b*e - a*f)*(d*g - c*h))])/((b*c - a*d)*Sqrt[b*e - a*f]*(b*g - a*h)^2*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[(1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x)))/(1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]*Sqrt[1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x))])}
{Sqrt[a + b*x]*Sqrt[c + d*x]/(Sqrt[e + f*x]*Sqrt[g + h*x]), x, 7, (Sqrt[a + b*x]*Sqrt[c + d*x]*Sqrt[g + h*x])/(h*Sqrt[e + f*x]) + (Sqrt[d*e - c*f]*(b*g - a*h)*Sqrt[d*g - c*h]*Sqrt[((f*g - e*h)*(a + b*x))/((b*g - a*h)*(e + f*x))]*Sqrt[((f*g - e*h)*(c + d*x))/((d*g - c*h)*(e + f*x))]*(e + f*x)*EllipticE[ArcSin[(Sqrt[d*e - c*f]*Sqrt[g + h*x])/(Sqrt[d*g - c*h]*Sqrt[e + f*x])], ((b*e - a*f)*(d*g - c*h))/((d*e - c*f)*(b*g - a*h))])/(f*h*(f*g - e*h)*Sqrt[a + b*x]*Sqrt[c + d*x]) - ((d*e - c*f)*Sqrt[f*g - e*h]*(b*f*g + b*e*h - 2*a*f*h)*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*Sqrt[1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x))]*EllipticF[ArcTan[(Sqrt[b*e - a*f]*Sqrt[g + h*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], ((d*e - c*f)*(b*g - a*h))/((b*e - a*f)*(d*g - c*h))])/(f^2*Sqrt[b*e - a*f]*h*(b*g - a*h)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[(1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x)))/(1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]*Sqrt[1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x))]) + (Sqrt[b*g - a*h]*(a*d*f*h - b*(d*f*g + d*e*h - c*f*h))*Sqrt[((f*g - e*h)*(a + b*x))/((b*g - a*h)*(e + f*x))]*Sqrt[((f*g - e*h)*(c + d*x))/((d*g - c*h)*(e + f*x))]*(e + f*x)*EllipticPi[(f*(b*g - a*h))/((b*e - a*f)*h), ArcSin[(Sqrt[b*e - a*f]*Sqrt[g + h*x])/(Sqrt[b*g - a*h]*Sqrt[e + f*x])], ((d*e - c*f)*(b*g - a*h))/((b*e - a*f)*(d*g - c*h))])/(f^2*Sqrt[b*e - a*f]*h^2*Sqrt[a + b*x]*Sqrt[c + d*x])}
{(a + b*x)^(3/2)/(Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[g + h*x]), x, 12, (b*Sqrt[a + b*x]*Sqrt[c + d*x]*Sqrt[g + h*x])/(d*h*Sqrt[e + f*x]) + (b*Sqrt[d*e - c*f]*(b*g - a*h)*Sqrt[d*g - c*h]*Sqrt[((f*g - e*h)*(a + b*x))/((b*g - a*h)*(e + f*x))]*Sqrt[((f*g - e*h)*(c + d*x))/((d*g - c*h)*(e + f*x))]*(e + f*x)*EllipticE[ArcSin[(Sqrt[d*e - c*f]*Sqrt[g + h*x])/(Sqrt[d*g - c*h]*Sqrt[e + f*x])], ((b*e - a*f)*(d*g - c*h))/((d*e - c*f)*(b*g - a*h))])/(d*f*h*(f*g - e*h)*Sqrt[a + b*x]*Sqrt[c + d*x]) - (2*(b*c - a*d)*Sqrt[b*e - a*f]*Sqrt[f*g - e*h]*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*Sqrt[1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x))]*EllipticF[ArcTan[(Sqrt[b*e - a*f]*Sqrt[g + h*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], ((d*e - c*f)*(b*g - a*h))/((b*e - a*f)*(d*g - c*h))])/(d*f*(b*g - a*h)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[(1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x)))/(1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]*Sqrt[1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x))]) - (b*(d*e - c*f)*Sqrt[f*g - e*h]*(b*f*g + b*e*h - 2*a*f*h)*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*Sqrt[1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x))]*EllipticF[ArcTan[(Sqrt[b*e - a*f]*Sqrt[g + h*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], ((d*e - c*f)*(b*g - a*h))/((b*e - a*f)*(d*g - c*h))])/(d*f^2*Sqrt[b*e - a*f]*h*(b*g - a*h)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[(1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x)))/(1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]*Sqrt[1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x))]) + (b*Sqrt[b*g - a*h]*(a*d*f*h - b*(d*f*g + d*e*h - c*f*h))*Sqrt[((f*g - e*h)*(a + b*x))/((b*g - a*h)*(e + f*x))]*Sqrt[((f*g - e*h)*(c + d*x))/((d*g - c*h)*(e + f*x))]*(e + f*x)*EllipticPi[(f*(b*g - a*h))/((b*e - a*f)*h), ArcSin[(Sqrt[b*e - a*f]*Sqrt[g + h*x])/(Sqrt[b*g - a*h]*Sqrt[e + f*x])], ((d*e - c*f)*(b*g - a*h))/((b*e - a*f)*(d*g - c*h))])/(d*f^2*Sqrt[b*e - a*f]*h^2*Sqrt[a + b*x]*Sqrt[c + d*x]) - (2*b*(b*c - a*d)*(f*g - e*h)^(3/2)*(a + b*x)*Sqrt[((b*g - a*h)*(c + d*x))/((d*g - c*h)*(a + b*x))]*Sqrt[((b*g - a*h)*(e + f*x))/((f*g - e*h)*(a + b*x))]*Sqrt[1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x))]*EllipticPi[(f*(b*g - a*h))/((b*e - a*f)*h), ArcTan[(Sqrt[b*e - a*f]*Sqrt[g + h*x])/(Sqrt[f*g - e*h]*Sqrt[a + b*x])], ((d*e - c*f)*(b*g - a*h))/((b*e - a*f)*(d*g - c*h))])/(d*f*Sqrt[b*e - a*f]*h*(b*g - a*h)*Sqrt[c + d*x]*Sqrt[e + f*x]*Sqrt[(1 + ((b*c - a*d)*(g + h*x))/((d*g - c*h)*(a + b*x)))/(1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x)))]*Sqrt[1 + ((b*e - a*f)*(g + h*x))/((f*g - e*h)*(a + b*x))])}


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x)^m (c+d x)^n (e+f x)^p (g+h x)^q with m symbolic*)


{(a + b*x)^m*(c + d*x)*(e + f*x)*(g + h*x), x, 2, ((b*c - a*d)*(b*e - a*f)*(b*g - a*h)*(a + b*x)^(1 + m))/(b^4*(1 + m)) + ((3*a^2*d*f*h + b^2*(d*e*g + c*f*g + c*e*h) - 2*a*b*(d*f*g + d*e*h + c*f*h))*(a + b*x)^(2 + m))/(b^4*(2 + m)) - ((3*a*d*f*h - b*(d*f*g + d*e*h + c*f*h))*(a + b*x)^(3 + m))/(b^4*(3 + m)) + (d*f*h*(a + b*x)^(4 + m))/(b^4*(4 + m))}
{(a + b*x)^m*(c + d*x)*(e + f*x)/(g + h*x), x, 2, -(((a + b*x)^(1 + m)*(a*d*f*h + b*(d*f*g - d*e*h - c*f*h)*(2 + m) - b*d*f*h*(1 + m)*x))/(b^2*h^2*(1 + m)*(2 + m))) + ((d*g - c*h)*(f*g - e*h)*(a + b*x)^(1 + m)*Hypergeometric2F1[1, 1 + m, 2 + m, -((h*(a + b*x))/(b*g - a*h))])/(h^2*(b*g - a*h)*(1 + m))}
{(a + b*x)^m*(c + d*x)/((e + f*x)*(g + h*x)), x, 3, -(((d*e - c*f)*(a + b*x)^(1 + m)*Hypergeometric2F1[1, 1 + m, 2 + m, -((f*(a + b*x))/(b*e - a*f))])/((b*e - a*f)*(f*g - e*h)*(1 + m))) + ((d*g - c*h)*(a + b*x)^(1 + m)*Hypergeometric2F1[1, 1 + m, 2 + m, -((h*(a + b*x))/(b*g - a*h))])/((b*g - a*h)*(f*g - e*h)*(1 + m))}
{(a + b*x)^m/((c + d*x)*(e + f*x)*(g + h*x)), x, 5, (d^2*(a + b*x)^(1 + m)*Hypergeometric2F1[1, 1 + m, 2 + m, -((d*(a + b*x))/(b*c - a*d))])/((b*c - a*d)*(d*e - c*f)*(d*g - c*h)*(1 + m)) - (f^2*(a + b*x)^(1 + m)*Hypergeometric2F1[1, 1 + m, 2 + m, -((f*(a + b*x))/(b*e - a*f))])/((b*e - a*f)*(d*e - c*f)*(f*g - e*h)*(1 + m)) + (h^2*(a + b*x)^(1 + m)*Hypergeometric2F1[1, 1 + m, 2 + m, -((h*(a + b*x))/(b*g - a*h))])/((b*g - a*h)*(d*g - c*h)*(f*g - e*h)*(1 + m))}


(* ::Subsection::Closed:: *)
(*Integrands of the form (a+b x)^m (c+d x)^n (e+f x)^p (g+h x)^q with m, n and p symbolic*)


{(a + b*x)^m*(c + d*x)^n*(e + f*x)^p*(g + h*x)^3, x, 31, ((b*g - a*h)^3*(a + b*x)^(1 + m)*(c + d*x)^n*(e + f*x)^p*AppellF1[1 + m, -n, -p, 2 + m, -((d*(a + b*x))/(b*c - a*d)), -((f*(a + b*x))/(b*e - a*f))])/(((b*(c + d*x))/(b*c - a*d))^n*((b*(e + f*x))/(b*e - a*f))^p*(b^4*(1 + m))) + (3*h*(b*g - a*h)^2*(a + b*x)^(2 + m)*(c + d*x)^n*(e + f*x)^p*AppellF1[2 + m, -n, -p, 3 + m, -((d*(a + b*x))/(b*c - a*d)), -((f*(a + b*x))/(b*e - a*f))])/(((b*(c + d*x))/(b*c - a*d))^n*((b*(e + f*x))/(b*e - a*f))^p*(b^4*(2 + m))) + (3*h^2*(b*g - a*h)*(a + b*x)^(3 + m)*(c + d*x)^n*(e + f*x)^p*AppellF1[3 + m, -n, -p, 4 + m, -((d*(a + b*x))/(b*c - a*d)), -((f*(a + b*x))/(b*e - a*f))])/(((b*(c + d*x))/(b*c - a*d))^n*((b*(e + f*x))/(b*e - a*f))^p*(b^4*(3 + m))) + (h^3*(a + b*x)^(4 + m)*(c + d*x)^n*(e + f*x)^p*AppellF1[4 + m, -n, -p, 5 + m, -((d*(a + b*x))/(b*c - a*d)), -((f*(a + b*x))/(b*e - a*f))])/(((b*(c + d*x))/(b*c - a*d))^n*((b*(e + f*x))/(b*e - a*f))^p*(b^4*(4 + m)))}
{(a + b*x)^m*(c + d*x)^n*(e + f*x)^p*(g + h*x)^2, x, 15, ((b*g - a*h)^2*(a + b*x)^(1 + m)*(c + d*x)^n*(e + f*x)^p*AppellF1[1 + m, -n, -p, 2 + m, -((d*(a + b*x))/(b*c - a*d)), -((f*(a + b*x))/(b*e - a*f))])/(((b*(c + d*x))/(b*c - a*d))^n*((b*(e + f*x))/(b*e - a*f))^p*(b^3*(1 + m))) + (2*h*(b*g - a*h)*(a + b*x)^(2 + m)*(c + d*x)^n*(e + f*x)^p*AppellF1[2 + m, -n, -p, 3 + m, -((d*(a + b*x))/(b*c - a*d)), -((f*(a + b*x))/(b*e - a*f))])/(((b*(c + d*x))/(b*c - a*d))^n*((b*(e + f*x))/(b*e - a*f))^p*(b^3*(2 + m))) + (h^2*(a + b*x)^(3 + m)*(c + d*x)^n*(e + f*x)^p*AppellF1[3 + m, -n, -p, 4 + m, -((d*(a + b*x))/(b*c - a*d)), -((f*(a + b*x))/(b*e - a*f))])/(((b*(c + d*x))/(b*c - a*d))^n*((b*(e + f*x))/(b*e - a*f))^p*(b^3*(3 + m)))}
{(a + b*x)^m*(c + d*x)^n*(e + f*x)^p*(g + h*x)^1, x, 7, ((b*g - a*h)*(a + b*x)^(1 + m)*(c + d*x)^n*(e + f*x)^p*AppellF1[1 + m, -n, -p, 2 + m, -((d*(a + b*x))/(b*c - a*d)), -((f*(a + b*x))/(b*e - a*f))])/(((b*(c + d*x))/(b*c - a*d))^n*((b*(e + f*x))/(b*e - a*f))^p*(b^2*(1 + m))) + (h*(a + b*x)^(2 + m)*(c + d*x)^n*(e + f*x)^p*AppellF1[2 + m, -n, -p, 3 + m, -((d*(a + b*x))/(b*c - a*d)), -((f*(a + b*x))/(b*e - a*f))])/(((b*(c + d*x))/(b*c - a*d))^n*((b*(e + f*x))/(b*e - a*f))^p*(b^2*(2 + m)))}
{(a + b*x)^m*(c + d*x)^n*(e + f*x)^p*(g + h*x)^0, x, 3, ((a + b*x)^(1 + m)*(c + d*x)^n*(e + f*x)^p*AppellF1[1 + m, -n, -p, 2 + m, -((d*(a + b*x))/(b*c - a*d)), -((f*(a + b*x))/(b*e - a*f))])/(((b*(c + d*x))/(b*c - a*d))^n*((b*(e + f*x))/(b*e - a*f))^p*(b*(1 + m)))}
{(a + b*x)^m*(c + d*x)^n*(e + f*x)^p/(g + h*x)^1, x, 0, Defer[Int][((a + b*x)^m*(c + d*x)^n*(e + f*x)^p)/(g + h*x), x]}
